### ISSUE TITLE
Add new project with API management

### ISSUE THREAD

**Issue by skoruba** [skoruba/IdentityServer4.Admin#105]
Add new project - `Skoruba.IdentityServer4.Admin.Api`:
- Create a list of API controllers - for managing of the `IdentityServer4` and `Asp.Net Core Identity`
- Add swagger support

**Comment by ekjuanrejon** [comment]
hello @skoruba 

any plans on this?

**Comment by skoruba** [comment]
Hi @ekjuanrejon
In the future yes, but if you want to start with this task, feel free send a PR. :)
Thanks!

**Comment by skoruba** [comment]
- Create projects:
  - `Skoruba.IdentityServer4.Admin.Api`
  - `Skoruba.IdentityServer4.Admin.Api.BusinessLogic` - There will be great to reuse the existing repositories and create new services for API, including new Dtos etc.

**Comment by ekjuanrejon** [comment]
@skoruba why can't the business logic of the mvc and the api be shared?

On another note. I see that mvc uses a bit of reflection. Not how how it will play with the api and swagger.

**Comment by skoruba** [comment]
That is great question, I think some of Dtos are very specific for views in MVC app, thefore I am thinking about this separation.
But you are right, maybe it would be fine - create shared business logic layer for both - mvc and api. I will try to consider it.
Good point. :)
Which part of code with reflection do you mean?
Thanks!

**Comment by JimBobSquarePants** [comment]
The missing APIs are the only feature that devalues this product from competition. The company I work for are unfortunately having to evaluate another product because we need those APIs and are under so much time pressure we cannot currently dedicate the time to PR the functionality. 😞 

👍 on reusing logic.

**Comment by skoruba** [comment]
Thanks for your feedback, I will work on it. :)

**Comment by kjbetz** [comment]
I'd like to start taking a look at this and offer some help. I worked on a project for myself that implemented a free UI for the PolicyServer... would be good to implement that all together. I'll start taking a look around of what you have already. Awesome stuff!

**Comment by skoruba** [comment]
Great, if you want to help, it would be perfect. :+1

**Comment by skoruba** [comment]
I am working on API:
https://github.com/skoruba/IdentityServer4.Admin/tree/feature/api
I am using the shared business logic from MVC project, but with new mapping for API dtos.

Currently still in progress, but with high priority. :)

**Comment by skoruba** [comment]
Done, please take a look at new release. 👍🏼
Thanks.

**Comment by JimBobSquarePants** [comment]
Ah fantastic @skoruba ! I'll have a good look asap.
