### ISSUE TITLE
Enhance Claim Management by Introducing Scope-Like Table for Claims

### ISSUE THREAD

**Issue by matiasvallejosdev** [skoruba/IdentityServer4.Admin#1064]
**Is your feature request related to a problem? Please describe.**

Yes, currently, claims are not managed as a shared table across the Identity Provider (IDP) in Skoruba.IdentityServer4.Admin. This necessitates defining claims repeatedly and maintaining conventions manually, which increases the risk of mistakes and inconsistency.

**Describe the solution you'd like**

I would like to introduce a shared table for claims within the Skoruba.IdentityServer4.Admin project. This table should allow for the creation, management, and reuse of claims across different users and clients, similar to the existing scope management system. This enhancement will ensure consistency, reduce repetitive tasks, and minimize the risk of errors due to manual definitions.

**Describe alternatives you've considered**

An alternative could be implementing a strict convention and validation system to ensure claims are defined correctly each time. However, this still involves manual definitions and does not fully eliminate the risk of inconsistencies and errors.

Additional context

I am currently using Skoruba.IdentityServer4.Admin for a company in Argentina and I love it. This feature would significantly improve the efficiency and reliability of managing claims in our environment. This enhancement would align the claim management process with best practices for handling scopes, providing a more streamlined and error-resistant approach to managing user and client claims in IdentityServer4.

**Comment by skoruba** [comment]
Hi @matiasvallejosdev - thank you for requesting this issue!

I will do it but for Duende Identity Server Admin UI.

**Comment by matiasvallejosdev** [comment]
Hi @skoruba,

Thank you for your prompt response and for agreeing to implement this feature for Duende Identity Server Admin UI. I appreciate your efforts and look forward to the enhancement. This will greatly improve the efficiency and reliability of claim management in our environment.

Please let me know if there's anything I can do to assist or if you need further input from my side.

Best regards,
Matias Vallejos.
