### ISSUE TITLE
InvalidOperationException accessing Persisted Grants page

### ISSUE THREAD

**Issue by renatoferreirarenatoferreira** [skoruba/IdentityServer4.Admin#107]
Hi,

I am receiving the following error while accessing the Persisted Grants page (/Grant/PersistedGrants):

> 
> An unhandled exception occurred while processing the request.
> InvalidOperationException: The binary operator Equal is not defined for the types 'System.Nullable`1[System.Int32]' and 'System.Object'.
> 
> System.Linq.Expressions.Expression.GetEqualityComparisonOperator(ExpressionType binaryType, string opName, Expression left, Expression right, bool liftToNull)
>

This is the useful stack trace information:

![image](https://user-images.githubusercontent.com/12613085/47971245-d2ab3b00-e076-11e8-83e7-064e261ae2df.png)

I have changed only 2 things:
- The project configuration to run it without IIS Express
- The database related code to run using SQLite following the [related instructions](https://github.com/skoruba/IdentityServer4.Admin/blob/master/docs/EFMigration.md)

The application seem to be working. Clicking everywhere I found this problem. I also tried adding the _page_ and _search_ arguments, but the error still persists.

Thanks!
Renato A. Ferreira

**Comment by skoruba** [comment]
Hi @renatoferreirarenatoferreira 
I will check it, thanks for reporting!

**Comment by skoruba** [comment]
Hey, which primary key do you use for UserIdentity? Int as default?
Have you used the latest version from master branch?
Thanks!

**Comment by renatoferreirarenatoferreira** [comment]
Yes, int as default. I think so, as I haven't changed it.

I was using the IdentityServer4.Admin-1.0.0-beta4 downloaded from releases page.

I tried again cloning the master branch and I received a different stack, but the problem is still there:

![image](https://user-images.githubusercontent.com/12613085/48572748-6ab7e880-e8f1-11e8-8804-c93a0d5303fb.png)

Isn't it something related to SQLite? I am using it during the prototyping phase, and also facing some issues.

**Comment by skoruba** [comment]
Please, try use latest release, everything should be fine. Thanks!
