### ISSUE TITLE
Newbee question :)

### ISSUE THREAD

**Issue by gwinnem** [skoruba/IdentityServer4.Admin#112]
Tnxs for a super project.
I am just starting playing around with it but i have 1 question.
My start screen in the admin project is not the same as in the readme section.
Am i missing something ?
![image](https://user-images.githubusercontent.com/6427120/48261551-c11fb580-e41f-11e8-8fbf-623fcf8ead65.png)

**Comment by skoruba** [comment]
Hi @gwinnem 
Please - try to Set Startup projects in Visual Studio:
- Skoruba.IdentityServer4.Admin
- Skoruba.IdentityServer4.STS.Identity

And then run it and try to access Admin UI on http://localhost:9000 - you should be redirected to IdentityServer4 instance - it is the screenshot as you have posted above.
And there you will be ask for putting the username and password. :)
Please take a look at Readme - Access Layer and EF Core section - migrations etc. 

If you will have any issues, let me know.
Thanks.

**Comment by gwinnem** [comment]
Thank you for the quick reply.

**Comment by gwinnem** [comment]
Another question, sorry for this
I am logged in but getting this error msg. I have not done anything to the database exept running the seed.
![image](https://user-images.githubusercontent.com/6427120/48269395-c4bf3680-e437-11e8-99d4-f5dba2072a2a.png)

**Comment by gwinnem** [comment]
As far as i managed to see, both of the values are http://localhost:9000/signin-oidc

**Comment by skoruba** [comment]
Thas is correct. ClientId for Admin is set as a default? skoruba_identity_admin? If I remember correctly :))
Maybe please try run STS in console app and check the console log for this error. 
Thanks!

**Comment by gwinnem** [comment]
Found the issue, the IdentityAdminRedirectUri in appsettings was wrong. :) Pointing to port 5000 instead of 9000

**Comment by skoruba** [comment]
Great catch! :)

**Comment by gwinnem** [comment]
Another tip, if someone do not want to see the identityserver page, set 
**"launchBrowser": false,**
In the Skoruba.IdentityServer4.STS.Identity launchSettings.json

**Comment by skoruba** [comment]
Good tip, I didn’t know it :)

**Comment by gwinnem** [comment]
Then the server launches without launching the browser :)

**Comment by gwinnem** [comment]
Is there a easy way to use email instead of username as login ?

**Comment by papyr** [comment]
hi, whats the default user name and password after uncommenting the `seed` function in startup. I did not find that in the docs.

**Comment by Sindrenj** [comment]
I guess you could fill in the email as the username in the username-field. That should work.

**Comment by xmichaelx** [comment]
You can check progress of using email instead of username as login in #139
