### ISSUE TITLE
AddAdminAspNetIdentityServices and DbContexts from IdentityServer4

### ISSUE THREAD

**Issue by wally666** [skoruba/IdentityServer4.Admin#114]
Hi Skoruba,

I have PersistedGrantDbContext defined in IdentityServer4 project. I have extended the context with your IAdminPersistedGrantDbContext interface and current it looks like following:

`public class PersistedGrantDbContext : IdentityServer4.EntityFramework.DbContexts.PersistedGrantDbContext<PersistedGrantDbContext>, 
        IAdminPersistedGrantDbContext
    {
        public PersistedGrantDbContext(DbContextOptions options, OperationalStoreOptions storeOptions) : base(options, storeOptions)
        {
        }
    }`

The problem is that I still cannot use the context in AddAdminAspNetIdentityServices:
The PersistedGrantDbContext based on IdentityServer4.EntityFramework.DbContexts.PersistedGrantDbContext (witch is based on DbContext).
The AddAdminAspNetIdentityServices extension metchod requires TPersistedGrantDbContext where  TIdentityDbContext : IdentityDbContext<...> and this a problem. We cannot use context from IdentityServer (with already defined mappings, migrations, ect). I do not want to create another DbContext or to use your implementation of AdminDbContext.

It is possible to use IdentityService context (PersistedGrantDbContext) and register in AddAdminAspNetIdentityServices? What are the steps? Please help. I'd like to use your project in my infrastructures :)

Cheers!

p.s.
I'm using version 1.0.0-beta3 and latest IdentityServer stable packages 
IdentityServer4 (2.2.0)
IdentityServer4.AspNetIdentity (2.1.0)
IdentityServer4.EntityFramework (2.1.1)

**Comment by wally666** [comment]
On the IdentityServer side I have 3xDbContext: 
1. DatabaseContext inherited from IdentityDbContext and registered with my impelmentation of user:

services.AddIdentity<ApplicationUser, IdentityRole>()
                  .AddEntityFrameworkStores<DatabaseContext>()
                  .AddDefaultTokenProviders();

2.  ConfigurationDbContext registered by AddConfigurationStore
3. PersistedGrantDbContext registered by AddOperationalStore

I we would like to be compatible with IdentityServer we need have similar aproach:

- use one complex type (like your implementation TAdminDbContext : DbContext, IAdminPersistedGrantDbContext, IAdminConfigurationDbContext, IAdminLogDbContext;) supporterd by AdminServicesExtensions

public static IServiceCollection AddAdminAspNetIdentityServices<TAdminDbContext, TUserDto, TUserDtoKey, TRoleDto, TRoleDtoKey, TUserKey, TRoleKey, TUser, TRole, TKey, TUserClaim, TUserRole, TUserLogin, TRoleClaim, TUserToken>(this IServiceCollection services)
            where TAdminDbContext : IdentityDbContext<TUser, TRole, TKey, TUserClaim, TUserRole, TUserLogin, TRoleClaim, TUserToken>, IAdminPersistedGrantIdentityDbContext
            where TUserDto : UserDto<TUserDtoKey>
            where TRoleDto : RoleDto<TRoleDtoKey>
            where TUser : IdentityUser<TKey>
            where TRole : IdentityRole<TKey>
            where TKey : IEquatable<TKey>
            where TUserClaim : IdentityUserClaim<TKey>
            where TUserRole : IdentityUserRole<TKey>
            where TUserLogin : IdentityUserLogin<TKey>
            where TRoleClaim : IdentityRoleClaim<TKey>
            where TUserToken : IdentityUserToken<TKey>;

or all of the 3 types:

public static IServiceCollection AddAdminAspNetIdentityServices<TPersistedGrantDbContext, TIdentityDbContext, TUserDto, TUserDtoKey, TRoleDto, TRoleDtoKey, TUserKey, TRoleKey, TUser, TRole, TKey, TUserClaim, TUserRole, TUserLogin, TRoleClaim, TUserToken>(this IServiceCollection services)
            where TPersistedGrantDbContext : **DbContext**<TUser, TRole, TKey, TUserClaim, TUserRole, TUserLogin, TRoleClaim, TUserToken>, IAdminPersistedGrantIdentityDbContext
            where TIdentityDbContext : IdentityDbContext<TUser, TRole, TKey, TUserClaim, TUserRole, TUserLogin, TRoleClaim, TUserToken>
            where TUserDto : UserDto<TUserDtoKey>
            where TRoleDto : RoleDto<TRoleDtoKey>
            where TUser : IdentityUser<TKey>
            where TRole : IdentityRole<TKey>
            where TKey : IEquatable<TKey>
            where TUserClaim : IdentityUserClaim<TKey>
            where TUserRole : IdentityUserRole<TKey>
            where TUserLogin : IdentityUserLogin<TKey>
            where TRoleClaim : IdentityRoleClaim<TKey>
            where TUserToken : IdentityUserToken<TKey>;

so my suggestionis to not merge TPersistedGrantDbContext with TIdentityDbContext. 
TPersistedGrantDbContext  should inherits just from DbContext + implements required interfaces. If views needs any data from IdentityDbContext - use registered TIdentityDbContext.
Maybe it will be enought to change TPersistedGrantDbContext base class in the AddAdminAspNetIdentityServices metchod declaration? Sorry, I havent checked deeper your source code.

**Comment by skoruba** [comment]
OK, I see your requirement, but currently is necessary to implement DbContext like you mentioned above, because some view which are bound with Identity and PersistedGrants. 
I will consider to create an alternative overload and remove this required inheritents.
Thank you for your great feedback!

**Comment by FieldMarshallVague** [comment]
@wally666 Did you manage to get this working?  I am having the same problem (using an existing IS4 instance with AspNetIdentity).  I'd really appreciate a code example or some guidance in making this change).

**Comment by FieldMarshallVague** [comment]
@skoruba When you say "but currently is necessary to implement DbContext like you mentioned above", do you mean that you can implement this by:
`where TPersistedGrantDbContext : DbContext` 
Or were you saying that it is not a simple change and would need a new overload to make this work?

**Comment by skoruba** [comment]
Done on `master`. Please check new release.
Thanks!
