### ISSUE TITLE
Upgrade db schema to Ids4 2.3

### ISSUE THREAD

**Issue by cerginio** [skoruba/IdentityServer4.Admin#115]
Consider to upgrade admin tool to the latest IdentityServer4.EntityFramework preview version.

 https://github.com/IdentityServer/IdentityServer4/releases/tag/nuget_2.3.0-preview2
https://github.com/IdentityServer/IdentityServer4.EntityFramework/releases/tag/nuget_2.3.0-preview2
Those versions tested and i find them  as very mature despite on preview status.
From critical improvements from administration perspective - fixed very annoying automapper exceptions after update client grant type.

Consequences:
50% unit tests and 100% integration tests broken (Entity mocks detect unmapped properties).
Push users to update IdentityServer4 as well.

**Comment by skoruba** [comment]
I will create new branch for this update to IS4 - 2.3
Thanks!

**Comment by cerginio** [comment]
I would keep preview in separate branch while 2.3 preview 2  it is not released as stable 2.3.3.
And also i would add tag Ids4.2.2 for current master to match Admin versions against Identity Server versions. Or even to have Ids4 version branches to explicitly provide compatibility for 3 recent ids4 versions.

**Comment by skoruba** [comment]
Currently available final version of IdentityServer4 - 2.3.0 - https://github.com/IdentityServer/IdentityServer4/releases/tag/2.3.0

**Comment by tiwari-abhishek** [comment]
This is a blocker. Please fix asap.

**Comment by skoruba** [comment]
@tiwari-abhishek Yes :)

**Comment by skoruba** [comment]
Here is updated project to IS4 2.3 - https://github.com/skoruba/IdentityServer4.Admin/tree/feature/upgrade-ids4-2-3
I will merge it into master.

**Comment by skoruba** [comment]
It is merged into `dev` branch. I will merge it into `master` soon - #137

**Comment by skoruba** [comment]
Done.
