### ISSUE TITLE
Question. How to extend user role and user details.

### ISSUE THREAD

**Issue by gwinnem** [skoruba/IdentityServer4.Admin#118]
I am working on extending the user and role details is there an easy way of doing this ?
I thought it was enough to update the role and user details in the classes and then extend the repository update functions.
But i was not able to do that.
Btw I have extended all the views and Dto's so it is only the Create and Update functions im not able to change.

**Comment by skoruba** [comment]
Hi @gwinnem 
Have you tried to use project via template or clone? :)
You can try to create your own implementation of `UserIdentity` and `UserDto` and these objects pass into generic repositories/services - BTW - you should start with `AddAdminAspNetIdentityServices` in Startup class and `IdentityController` as well. 
Thanks!

**Comment by gwinnem** [comment]
Hi @skoruba 
I suppose it is enough to replace all the Identity and Identity role references with a AppUser inheriting from the IdentityUser and a AppRole inheriting from the IdentityRole. Will try that later today and let you know if it worked.

**Comment by skoruba** [comment]
Done on `master`. Please check new release.
Thanks!
