### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by NTurakulov** [skoruba/IdentityServer4.Admin#121]
Hey guys!
I tried to pack the project into docker to make it easy to deploy and faced some problems, maybe some one could help here. Changes published to [docker branch](https://github.com/NTurakulov/IdentityServer4.Admin/tree/docker)

**Requirement**
Make it easy to deploy Identity Server Admin to use it in different apps as a part of micro service architecture. I saw somewhere in the feed that @skoruba planned to pack the project into NuGet but I think docker another way to make it portable

**Solution**
Pack the project (Admin and STS) into docker images and run them at any time with required port inside your cluster

**Implementation**
I added two Dockerfiles in target project folders, docker-compose.yml in root plus several powershell scripts in the folder with same name. It works but made dummy. To start run containers - run 'run-docker.ps1' script or execute commands from it one by one (for non-Windows platforms).

SQL server is also packed into an image and run as a part of compose with persistent external volume (skoruba-identityserver-sql). All three containers (SQL, STS, Admin) work within same docker network (skoruba-identityserver-network) and can interact with each other

**Note** 
- Admin project port 80 is mapped to host's port **5001** instead of 9000
- MS SQL container's port 1433 is mapped to host's 1433**3**! This made for compatibility with MS SQL instance on the host

**Problems**

- Dependency projects are not packed as NuGet and cannot be restored with 'dotnet restore'. Because of that instead of using single multi step Dockerfile I build it on host then just copy to aspnetcore-runtime image. This can be solved with modified Dockerfile which copies 'bin' folder with dependencies but prebuild on host is required anyway. Also projects use 'npm install' which is not preinstalled into default aspnetcore-sdk build image.
    - As dotnet CLI calls required before 'docker build' they're packed into build-docker-*.ps1 scripts
- I've added DockerRelease config file with overriden parameters but they don't apply so duplicated in docker-compose.yml and passed with 'environment'
- While STS and Admin containers can use short docker-compose.yml service names when reference to sql container successfully I can't access to sts/.well-known/openid-configuration from within Admin project
- Don't know how to apply EF migrations from within container. Before building docker image DbContext reference to host DB, after running a container not sure how to do that. Maybe something like 'EXEC dotnet ef database update'? Need to try this way
- Both projects are configured to run in 'Development' environment because certificate for HTTPS is not set up

**Comment by NTurakulov** [comment]
Accidentally I pushed changes into branch in my fork. I guess there should be a way to cherry pick them here?

**Comment by skoruba** [comment]
Hi @NTurakulov 
Thank you for your effort to run this admin in docker. I don't have any experience with docker yet. 
How can I help you with better preparing this project to running in docker?
Thanks!

**Comment by NielsOldenburg** [comment]
Hey Guys,
we are on the verge of trying something similar. Unfortunately i'm just starting to work with docker, so right now i might not be the best judge for this, but our software architect told me that splitting your solution in two different repos would make it easier to put the id4 server and the administration service in two different docker containers.

So far i have forked your repo and split it up, but that increases the complexity. Maybe a first step could be to split your solution up @skoruba . @NTurakulov since you are obviously more experienced with docker, would that help or is there a way to run both, the id4 server and the admin service from the same container?

I'll get back to you once i get my basic docker experiments runnning.

**Comment by skoruba** [comment]
@Seaear - add support for docker - #132 - please take a look. 
Thanks!

**Comment by brinehart** [comment]
So it looks like this functionality was merged. Should the main readme be updated to check off the Docker Support box and add instructions to run the project with Docker?

**Comment by skoruba** [comment]
For sure, I am working on it.

**Comment by brinehart** [comment]
Please let me know if you would like any help on that.

**Comment by skoruba** [comment]
I am closing this issue, it was released in master branch.

**Comment by thylux** [comment]
Hi, I'm trying to run a demo from source using docker compose on Visual Studio but I can't login because login on database failed.
Isn't this supposed to work without changing configuration?

If not maybe I can help to complement the documentation for that.

![image](https://user-images.githubusercontent.com/1215984/74596119-cb792800-5042-11ea-8d9c-673a7ceef68e.png)

**Comment by thylux** [comment]
So far I can see that there is connectivity between the 3 docker instances and that the login settings all match up.

![image](https://user-images.githubusercontent.com/1215984/74596607-8f959100-5049-11ea-9618-90ecbf9252ae.png)


![image](https://user-images.githubusercontent.com/1215984/74596611-9c19e980-5049-11ea-955d-8302822ca40d.png)


![image](https://user-images.githubusercontent.com/1215984/74596615-a936d880-5049-11ea-8c8d-b7bdfca90ebd.png)

![image](https://user-images.githubusercontent.com/1215984/74596625-b358d700-5049-11ea-81a1-7df50013f413.png)

**Comment by thylux** [comment]
Well, I tried again today and without any change all is working!

![Off and On again](https://media.giphy.com/media/F7yLXA5fJ5sLC/giphy.gif)
