### ISSUE TITLE
Picker not working

### ISSUE THREAD

**Issue by Ylvur** [skoruba/IdentityServer4.Admin#126]
Hi!

I have just set up the AdminGui but none of the pickers is working for me. 
Textboxes and checkboxes works fine.

First: it is only possible to enter one in the gui, for example scope. The next one we enter replace the first one in the gui even though multiple-select="true". 

Second: Noting is saved to the database, all list are empty in the inparam to the controller (ClientDto).

Third: If I enter scopes manually in the database I can see that they are sent to the model  selected-items="@Model.AllowedScopes" in front end but nothing is shown in GUI.

It is the same for all pickers.

Please help. What are we missing/doing wrong?

**Comment by skoruba** [comment]
Hi @Ylvur 
have you tried to click on item in search block?
Thanks!

**Comment by Ylvur** [comment]
Yes. The value get replaced every time and noting is saved to database. 
When manually entered in database values are not shown in GUI. 
[Picker.zip](https://github.com/skoruba/IdentityServer4.Admin/files/2675161/Picker.zip)

**Comment by skoruba** [comment]
Any javascript error in console?

**Comment by Munde** [comment]
Also in Skoruba.IdentityServer4.Admin pickers heavily depends on tag helpers if u have changes the project name to new name likely will break the pickers so in _viewImport.cshtml under shared folder remember to rename the add tag helper assembly name @addTagHelper *, Skoruba.IdentityServer4.Admin name to your project new assembly name

**Comment by skoruba** [comment]
@Munde Great idea! I can see in video, that your checkboxes are broken as well. Please take a look at TagHelper import or JS error as well.
Thanks!

**Comment by Ylvur** [comment]
Thank you so much @Munde, we changed the projectname so renaming the taghelper made all the difference. Now it works fine!
