### ISSUE TITLE
Numeric Ids vs Guids

### ISSUE THREAD

**Issue by smellogrand** [skoruba/IdentityServer4.Admin#127]
Great work, really appreciate it.
One suggestion, as many old timers using IS3/IS4 in real life projects I have used Guids for ids on entities and was somehow surprised  in seeing that your base implemantation is instead using numeric Ids.
Of course you have provided good documentation on how to change things to support Guids, thank you for that, but, as I assume you and colleagues also have experience in IS4 I wonder what is the reason of your preferred choice. 
In general i believe Guids are better also for slalability and merging of istances, and most benchmark show that in SQL Server newsequentialid() is even faster than autonumber. 
Thanks again for your effort, very nice and useful.

sergio, Italy

**Comment by skoruba** [comment]
@smellogrand Thanks for you suggestion, I will consider to use guid as default.

**Comment by Seaear** [comment]
@smellogrand 
https://github.com/Seaear/IdentityServer4.Admin/tree/pk-guid

**Comment by skoruba** [comment]
I've changed the int to string (guid) - here is preview:
https://github.com/skoruba/IdentityServer4.Admin/tree/feature/identity-default-key

**Comment by smellogrand** [comment]
Thanks, I believe this is more in line with recent patterns.
I suggest changing the wron title I inserted originally from mimeric to numeric.

thanks for your very useful development

sergio

**Comment by skoruba** [comment]
Done on `master`. Please check new release.
Thanks!

**Comment by smellogrand** [comment]
Thanks my friend, you are a good guy, I will check it by tomorrow and give feedback.
Hope someday to return the courtesy vistiting you in Prague. For sure you deserve more than a good beer. I will let you choose a good restaurant. 
stay well and keep up your good work, very helpful for many of us.
bye, sergio
