### ISSUE TITLE
UserIdentity

### ISSUE THREAD

**Issue by ekjuanrejon** [skoruba/IdentityServer4.Admin#128]
Hello

How to extend UserIdentity when using the nuget packages. The IoC does not seem to play nice

**Comment by skoruba** [comment]
Hi @ekjuanrejon 
Have you tried to create your UserIdentity object and pass it into DI?
Please, follow these steps - https://github.com/skoruba/IdentityServer4.Admin/blob/master/docs/Configure-To-Existing-Identity.md
Let me know if you will have any issues.
Thanks-

**Comment by ekjuanrejon** [comment]
Hello I wanted to added more properties like FacilityId and OrganizationId but I don't think it is not supported. I ended up updating Skoruba.IdentityServer4.Admin.EntityFramework.Identity.Entities.Identity.UserIdentity and created a new nuget package.

I tried to inherit from that class but the IoC was failing.

**Comment by pbros** [comment]
Hello,

I am trying to achieve the same thing. One of the issues that I see is that the AdminDbContext specifies "UserIdentity" directly and not a generic type that can be injected.

The documentation (https://github.com/skoruba/IdentityServer4.Admin/blob/master/docs/Configure-To-Existing-Identity.md) relies on changing the code in `Skoruba.IdentityServer4.Admin.EntityFramework.DbContexts` and `Skoruba.IdentityServer4.Admin.EntityFramework.Identity`. When using the project template, these 2 projects are included as Nuget, so we can't make these changings without forking and and compiling our own versions of these projects.

Would adding generic types to the AdminDbContext be possible and could it potentially allow specifying our own UserIdentity class to be done easily?

**Comment by skoruba** [comment]
Hello @pbros 
currently, it is designed that if you want to use another Identity model, you have to create your own DbContext. :)
Good point, I will think about generic version of DbContext as well.
Thanks.

**Comment by skoruba** [comment]
Done on `master`. Please check new release.
Thanks!
