### ISSUE TITLE
Update project to .NET Core 2.2

### ISSUE THREAD

**Issue by skoruba** [skoruba/IdentityServer4.Admin#131]

**Comment by skoruba** [comment]
Here is updated project to .NET Core 2.2 - https://github.com/skoruba/IdentityServer4.Admin/tree/feature/upgrade-ids4-2-3
I will merge it into master.

**Comment by skoruba** [comment]
It is merged into `dev` branch. I will merge it into `master` soon - #137

**Comment by shepax** [comment]
@skoruba, can you please update the info to use mysql.

**Comment by skoruba** [comment]
@svendu - Could you please check it - is it any update for mysql? 
Thanks!

**Comment by svendu** [comment]
@skoruba - I'll try to get my hands on it at the weekend.

**Comment by skoruba** [comment]
Done

**Comment by shepax** [comment]
Thank!!!
