### ISSUE TITLE
Migrate CI to Azure Pipelines

### ISSUE THREAD

**Issue by TomasHubelbauer** [skoruba/IdentityServer4.Admin#134]
Let's catch up and discuss migrating the CI to Azure Pipelines, they allow testing on all three platforms and there can be up to 10 parallel builds, which should be better than AppVeyor.

**Comment by skoruba** [comment]
I agree with you. Currently I get `The current .NET SDK does not support targeting .NET Core 2.2.` from appveyor build. I have to wait for update on AppVeyor. It will be nice to use Azure Pipelines.

**Comment by TomasHubelbauer** [comment]
I've set it up on my personal account for now:

[![Build Status](https://dev.azure.com/tomashubelbauer/IdentityServer4.Admin/_apis/build/status/IdentityServer4.Admin-CI?branchName=master)](https://dev.azure.com/tomashubelbauer/IdentityServer4.Admin/_build/latest?definitionId=8?branchName=master)

Right now it runs tests on `master`. I cannot set it up so that it runs on each commit yet, because I don't have the necessary permission to add a hook to this repository. There's a few things to finish:

- [ ] Move this project to your account
- [ ] Enable rolling tests once in your account
- [ ] Collect test results and upload them as artifacts
- [ ] Set up builds for all OSs, right now it's Windows only
- [ ] Explore reporting the test results back to GitHub
- [ ] Explore blocking PRs on test runs on GitHub

The last two integrations are optional, but will be nice to have.

**Comment by TomasHubelbauer** [comment]
I am going to close this issue as it has been completed now. I have created #138 for the Checks tab in PRs.
