### ISSUE TITLE
2FA with authenticator apps

### ISSUE THREAD

**Issue by xmichaelx** [skoruba/IdentityServer4.Admin#143]
As suggested by @skoruba it's important to support 2FA.

Here's one way of doing it:
https://dzone.com/articles/aspnet-core-two-factor-authentication-using-google

Basically app installed on you phone and QR code presented in UI:
https://play.google.com/store/apps/details?id=com.azure.authenticator&hl=en_US
https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en

And excellent tutorial from @damienbod on the topic of 2FA itself in IS4:
https://damienbod.com/2017/07/14/implementing-two-factor-authentication-with-identityserver4-and-twilio/

This way it's more accessible to everyone because you don't have to setup Twillio account and pay for sending messages.

**Comment by xmichaelx** [comment]
@Seaear how about 2FA apps in China? Do you have any preferences for those?

**Comment by damienbod** [comment]
I also have an example for TOTP (QR Codes) here, might help you.

https://github.com/damienbod/IdentityServer4AspNetCoreIdentityTemplate

**Comment by skoruba** [comment]
@damienbod - Thank you for your link - we will use your example for profile management in general.
I will add this reference of your project into readme as well.

**Comment by skoruba** [comment]
Done on `master`.
