### ISSUE TITLE
Signing Credential Management

### ISSUE THREAD

**Issue by RobCodemonkey** [skoruba/IdentityServer4.Admin#150]
**Task**: Create an easier way to handle signing credential changes.
**Description**: 
Currently, switching to production signing credentials is a little tricky. I know this has been partially handled using CertificateConfiguration and appsettings.json but aim is to make this switch easier.
 
@skoruba I have completed this for my fork that I'm working on, I'm testing it now - if you have no objection, once it's tested and confirmed I'd like to create a PR that you can then review and see if you'd like to incorporate it. 

Changelog
1. Initial Creation
2. Edited for clarity

**Comment by skoruba** [comment]
Hi @RobCodemonkey ,
Sure, please send a PR, I will check it. :)
Thanks!

**Comment by skoruba** [comment]
Any progress? :)

**Comment by skoruba** [comment]
Feel free to reopen.
