### ISSUE TITLE
[Question] IdentityUser<string> and default Idsrv4 DbContexts

### ISSUE THREAD

**Issue by lurumad** [skoruba/IdentityServer4.Admin#154]
Hi folks,

First, thank you for your awesome project and all your efforts to bring the community a free AdminUI for IdentityServer4.

I have a couple of questions about the Skoruba internals architecture: 

¿Why don't use the generic base for ASP.NET Identity Core IdentityUser<T>?
¿Why don't use Idsrv4 DbContexts instead of creating interfaces like IAdminConfigurationDbContext and IAdminPersistedGrantDbContext?
¿Why to force to implement IAdminLogDbContext in order to use Skoruba?

In my case, these two things are stoppers to use Skoruba in our existing projects, because works with default interfaces.

Regards!

**Comment by skoruba** [comment]
Hi @lurumad 

> Why don't use the generic base for ASP.NET Identity Core IdentityUser?
- You are right, I will change it back to the default - I get same feedback already.

> Why don't use Idsrv4 DbContexts instead of creating interfaces like IAdminConfigurationDbContext and IAdminPersistedGrantDbContext
- These intefaces are based on the default IS4 interfaces but extended with some extra stuff specific for Admin part - especially `IAdminConfigurationDbContext` where there is necessary to work with whole IS4 db model

>Why to force to implement IAdminLogDbContext in order to use Skoruba
- This is great question - I consider excluding it - good point. 

I will contact you with the progress later.

Thank you for your feedback! :)

**Comment by lurumad** [comment]
Thank you so much for your answers!

Regards!

**Comment by skoruba** [comment]
@lurumad - Here is preview - I've changed the primary key for Identity to `string`:
https://github.com/skoruba/IdentityServer4.Admin/tree/feature/identity-default-key

**Comment by TheEvilPenguin** [comment]
I did a little work a while back towards using generics to control the key type.  It's still a little rough around the edges and based on an old revision, but it does work:

[Dev branch](https://github.com/TheEvilPenguin/IdentityServer4.Admin/tree/dev)

If it looks promising I can merge later changes back in, tidy it up a bit and do a pull request.

**Comment by Bostrong** [comment]
@TheEvilPenguin  .. excellent !! Just the ticket to convince me to start using this Ids4 addition.

.. and also thanks for the great work on this @skoruba  ... will try to contribute where possible.

**Comment by skoruba** [comment]
@TheEvilPenguin - Your changes looks really good, much cleaner especially in views - where you are using the interface.
Can you please send the PR with your changes? Ideally into latest dev branch. :)
Thanks!

**Comment by skoruba** [comment]
Done on `master`. Please check new release.
Thanks!
