### ISSUE TITLE
dotnet run /seed   is error

### ISSUE THREAD

**Issue by hxjhaker** [skoruba/IdentityServer4.Admin#157]
![default](https://user-images.githubusercontent.com/5977354/51820409-981d0b80-2310-11e9-9ebc-1e6e77557498.png)

Cloning new project  1.0.0-beta5

**Comment by skoruba** [comment]
Do you have prepared migrations for this seed before?

Please, take a look at:
https://github.com/skoruba/IdentityServer4.Admin#ef-core--data-access

**Comment by hxjhaker** [comment]
Thank you !  You're right.

**Comment by skoruba** [comment]
Thank you for your feedback, that is working now. :)
