### ISSUE TITLE
iOS12 - authentication issue

### ISSUE THREAD

**Issue by skoruba** [skoruba/IdentityServer4.Admin#158]
> The recent iOS12 update has changed Safari's handling of SameSite cookies. - By default ASP.NET Core 2.0 and later protects its authentication cookies using the SameSite property. 

Available solutions:

1)
```
services.AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, options =>
{
    // Other options
    options.Cookie.SameSite = Microsoft.AspNetCore.Http.SameSiteMode.None;
})
```

2) https://brockallen.com/2019/01/11/same-site-cookies-asp-net-core-and-external-authentication-providers/

**Comment by xmichaelx** [comment]
I'd opt for 2 and even make it specific so that this change is made only for recent Safari browsers some user-agent detection logic like: https://github.com/wangkanai/Detection

If iOS12 has the issues let's fix it only for iOS12 and let's not downgrade security for everybody :)

**Comment by skoruba** [comment]
@xmichaelx - Good point, I will test the code from Brock above. :)
