### ISSUE TITLE
Migrations with Npgsql

### ISSUE THREAD

**Issue by knepe** [skoruba/IdentityServer4.Admin#160]
I cloned your project and change to use Npgsql instead in RegisterDbContexts. When I try to add migrations I get this error:
`Method 'Clone' in type 'Microsoft.EntityFrameworkCore.Infrastructure.Internal.NpgsqlOptionsExtension' from assembly 'Npgsql.EntityFrameworkCore.PostgreSQL, Version=1.1.1.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7' does not have an implementation.`

Any suggestion of what I can do to fix this?

**Comment by xmichaelx** [comment]
Make sure you've installed both `Npgsql.EntityFrameworkCore.PostgreSQL` and `Npgsql.EntityFrameworkCore.PostgreSQL.Design`. I remember having this issue once and uninstalling postgre dependencies and installing them again (with .Design) helped.

**Comment by knepe** [comment]
Thanks it worked when adding `Npgsql.EntityFrameworkCore.PostgreSQL` and not only `Npgsql.EntityFrameworkCore.PostgreSQL.Design`
Maybe update the docs to also include `Npgsql.EntityFrameworkCore.PostgreSQL` here https://github.com/skoruba/IdentityServer4.Admin/blob/master/docs/EFMigration.md#postgresql ?

**Comment by TomasHubelbauer** [comment]
@knepe Feel free to send a PR our way. :-) I agree that should be added to the docs.

**Comment by xmichaelx** [comment]
#167 Added pull request for this one.
