### ISSUE TITLE
Is it possible to Add a role to a user for a specified time period

### ISSUE THREAD

**Issue by Mehrdad-Davoudi** [skoruba/IdentityServer4.Admin#170]
Is it possible to Add a role to a user for a specified time period.
 For example, for a month and after that, this role will expire for that user.

**Comment by skoruba** [comment]
Hi @Mehrdad-Davoudi 
by default probable not, I don't know about this feature - you have to implement your own logic. :)

**Comment by xmichaelx** [comment]
In Admin panel for user management we just use the logic and database structure from [ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security) and there is a simple mapping between users and roles. Anything else would be a custom logic.

Sure we can add some expiration logic to user-role relationship but that would require more demand from the community or commercial cooperation.

**Comment by Mehrdad-Davoudi** [comment]
thank you for your answers hope to see new feature like this soon

**Comment by xmichaelx** [comment]
Ok, we're closing for now - if someone will be interested in this please feel free to +1 and reopen this thread.
