### ISSUE TITLE
Add missing translations for STS

### ISSUE THREAD

**Issue by skoruba** [skoruba/IdentityServer4.Admin#172]
Hi guys - @Seaear @alev7ina @saeedrahmo
please, can you add missing translations for new views/controllers in STS:
https://github.com/skoruba/IdentityServer4.Admin/tree/dev/src/Skoruba.IdentityServer4.STS.Identity/Resources

Thank you! :)

**Comment by Seaear** [comment]
ok

**Comment by skoruba** [comment]
Thanks guys for your translations, I really appreciate it. :)
Great job.
