### ISSUE TITLE
Consider add user registration into STS

### ISSUE THREAD

**Issue by skoruba** [skoruba/IdentityServer4.Admin#173]

**Comment by xmichaelx** [comment]
Makes sense as long there is configuration setting allowing to turn it of if admin wants to have more control over who has access to the system.

**Comment by skoruba** [comment]
Done on `dev` branch.
I added the parameter into configuration like this:
```
"RegisterConfiguration": {
        "Enabled": true
    }
```

**Comment by skoruba** [comment]
Done on `master`.
