### ISSUE TITLE
Create database migration error

### ISSUE THREAD

**Issue by Seaear** [skoruba/IdentityServer4.Admin#176]
Create a database migration error after
https://github.com/skoruba/IdentityServer4.Admin/commit/4573853636d5f6d3a9eb5d61220706b1f4b6a412

![image](https://user-images.githubusercontent.com/1687087/52991330-39e2d480-3447-11e9-9457-f29872ad6485.png)

**Comment by skoruba** [comment]
I’ll check it, thanks @Seaear.

**Comment by skoruba** [comment]
I fixed it - please take a look at latest dev branch. Thanks.

**Comment by Seaear** [comment]
Confirmed fixed.

**Comment by skoruba** [comment]
@Seaear - Thanks!
