### ISSUE TITLE
Use dotnet run /seed throw error

### ISSUE THREAD

**Issue by Seaear** [skoruba/IdentityServer4.Admin#179]
Use `dotnet run /seed` is error, But use `dotnet ef database update` is ok, Unable to create database automatically in Docker.
![image](https://user-images.githubusercontent.com/1687087/53033389-eb1b5600-34ab-11e9-8679-a6b608da855a.png)

**Comment by skoruba** [comment]
Is it configuration issue only? Because I have tried seed method and it works fine.

**Comment by Seaear** [comment]
Not a configuration issue,I merged the latest branch, Use commands
`dotnet ef migrations add InitAdminIdentityDb -c AdminIdentityDbContext -o Data/Migrations/AdminIdentityDb`
`dotnet ef migrations add InitIdentityServerConfigurationDb -c IdentityServerConfigurationDbContext -o Data/Migrations/IdentityServerConfigurationDb`
`dotnet ef migrations add InitIdentityServerPersistedGrantDb -c IdentityServerPersistedGrantDbContext -o Data/Migrations/IdentityServerPersistedGrantDb`
`dotnet ef migrations add InitAdminLogDb -c AdminLogDbContext -o Data/Migrations/AdminLogDb`

![image](https://user-images.githubusercontent.com/1687087/53063140-162e9580-34fe-11e9-9954-64339fa81e88.png)

**Comment by skoruba** [comment]
Ok, I will check it. Thank you

**Comment by skoruba** [comment]
I have tried it and works. Can you check please - @xmichaelx ? :)

**Comment by Seaear** [comment]
I tried again, download the zip file of the dev branch, also throw error

**Comment by xmichaelx** [comment]
From the command line I see that you've added the migrations but it seems that you haven't updated the database with them.

```
dotnet ef database update -c AdminIdentityDbContext
dotnet ef database update -c AdminLogDbContext
dotnet ef database update -c IdentityServerConfigurationDbContext
dotnet ef database update -c IdentityServerPersistedGrantDbContext
```

**Comment by xmichaelx** [comment]
Additionally it looks like you're failing during login so please check if your connection strings are correct.

**Comment by Seaear** [comment]
Previous versions can use /seed to create a database, using /seed to create a database automatically in docker.

**Comment by Seaear** [comment]
I did not modify any files after downloading the zip file.

**Comment by skoruba** [comment]
You are right - but we had only one DbContext, now it is necessary to do this manually - like Michal mentioned above.

**Comment by Seaear** [comment]
This will cause some difficulties for newcomers to use Docker in the future.

**Comment by xmichaelx** [comment]
This basically boils down to either issuing those commands (which you can automate in Docker build) or adding to code for each of 4 builtin context:

```context.Database.Migrate();```

From my POV it's a matter of preference and I would like the community to voice their preferences.

**Comment by Seaear** [comment]
Cannot be manipulated in Dockerfile, Dockerfile is only used to build images, and building image is independent of database operations.

**Comment by skoruba** [comment]
@Seaear - Please give us your preference about this issue. We'll modify it especially for better docker support.

**Comment by Seaear** [comment]
Use the command in the docker-compose.yml file to add the /seed parameter at runtime to automatically create the database

**Comment by xmichaelx** [comment]
@Seaear could check automatic-database-creation-during-seed branch? I've added database creation during seeding process.

**Comment by Seaear** [comment]
@xmichaelx Missing "\" in path when using localdb
![image](https://user-images.githubusercontent.com/1687087/53178207-5e4bd600-362c-11e9-9067-a9c932061fc3.png)

**Comment by xmichaelx** [comment]
`Server=(localdb)\\mssqllocaldb;Database=IdentityServer4Admin;Trusted_Connection=True;MultipleActiveResultSets=true` where here is the missing character?

**Comment by Seaear** [comment]
Great, use SQL Server it's working, localdb problem, I can try to find

**Comment by Seaear** [comment]
@xmichaelx Localdb problem, I can't find it, it's not affected in production environment or Docker, it doesn't matter for the time being.

**Comment by skoruba** [comment]
@Seaear - OK, I'll merge the changes from @xmichaelx .

**Comment by skoruba** [comment]
Done on `dev` branch @Seaear - you can test it. :)
Thanks!

**Comment by Seaear** [comment]
@skoruba Great, I tested it is working fine.
Thanks

**Comment by skoruba** [comment]
Thank you @xmichaelx as well.
May I close it?
