### ISSUE TITLE
Expect to add the Exceptionless log client support

### ISSUE THREAD

**Issue by Seaear** [skoruba/IdentityServer4.Admin#187]
https://github.com/exceptionless/Exceptionless

> The definition of the word exceptionless is: to be without exception. Exceptionless provides real-time error reporting for your JavaScript, Node, .NET Core, ASP.NET, Web API, WebForms, WPF, Console, and MVC apps. It organizes the gathered information into simple actionable data that will help your app become exceptionless!

**Comment by skoruba** [comment]
#268 - will be solved here.
