### ISSUE TITLE
 "Keyword not supported: 'port'." & "Unable to retrieve document from: '[PII is hidden]'" errors

### ISSUE THREAD

**Issue by gokayokutucu** [skoruba/IdentityServer4.Admin#192]
Hi,
I faced two different errors when I run Admin and STS.
STS is running on http://localhost:5000. Actually, this page is properly displayed but discovery document throws an error:
http://localhost:5000/.well-known/openid-configuration

![screenshot 2019-02-25 00 07 04](https://user-images.githubusercontent.com/10991334/53305378-fbf40f00-3891-11e9-8166-48ea5c5e5022.png)

Admin side is also not reachable:

![screenshot 2019-02-25 00 06 57](https://user-images.githubusercontent.com/10991334/53305367-d8c95f80-3891-11e9-9235-bdcebad60a12.png)

Where do you think I was wrong, guys?

Thanks

Not: I configured projects on postgre sql

**Comment by xmichaelx** [comment]
It probably means that you have connection string in wrong format or you haven't replaced UseSqlServer to matching PostgreSQL version everywhere. Please verify that and tell us if it solved the problem.

**Comment by gokayokutucu** [comment]
Before your remark, I have followed instruction which is under `EFMigration.md` file, it says:
```
Find RegisterDbContexts function in Helpers\StartupHelpers.cs

services.AddDbContext<AdminDbContext>(options => options.UseSqlServer(configuration.GetConnectionString(ConfigurationConsts.AdminConnectionStringKey), optionsSql => optionsSql.MigrationsAssembly(migrationsAssembly)));

**and change UseSqlServer to UseNpgsql.**
```

But when you emphasize,

> you haven't replaced UseSqlServer to matching PostgreSQL version everywhere

I found two more `UseSqlServer` method that waits for replacing with UseNpgsql.

After changes, it is running well.

Footnote: Under `Configure-Ubuntu-PostgreSQL-Tutorial.md` instructions have been noticed about `replace all occurences of UseSqlServer with UseNpgsql` but not in `EFMigration.md`.
