### ISSUE TITLE
Learn more in cookie consent does not activate the link

### ISSUE THREAD

**Issue by xmichaelx** [skoruba/IdentityServer4.Admin#200]
You have to click it with Ctrl pressed. Weird. Need to investigate.

**Comment by skoruba** [comment]
You can specify url like this:
```
window.cookieconsent.initialise({
		"content": {
			"href": "https://example.com/privacy",
		}
	});
```
Or do you mean some issue with the confirm button?

**Comment by xmichaelx** [comment]
![obraz](https://user-images.githubusercontent.com/1004852/53398250-72376500-39a9-11e9-9b8c-4bdf3d80d96c.png)

Clicking on `Learn more` does nothing until it's done with Ctrl pressed.

**Comment by skoruba** [comment]
Yes, you can add your own page with privacy information:
`"href": "https://example.com/privacy"`

**Comment by skoruba** [comment]
Fixed on `dev` branch.
Thanks.

**Comment by skoruba** [comment]
Done on `master`. Please check new release.
Thanks!
