### ISSUE TITLE
Error on Creates/Updates

### ISSUE THREAD

**Issue by john159753** [skoruba/IdentityServer4.Admin#206]
I am encountering an issue when trying to Create or Update nearly anything with the Admin UI. I enabled verbose logging and found this entry in the logs. Did my EF migration to the latest version break my database or is something going on with UI? I cant see why an UPDATE or INSERT would have a null ID.

2019-02-26 20:08:43.626 -06:00 [ERR] Exception at route /Configuration/IdentityResource/4
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Cannot insert the value NULL into column 'Id', table 'IdentityServer.dbo.IdentityClaims'; column does not allow nulls. UPDATE fails.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreResults(Boolean& moreResults)
   at System.Data.SqlClient.SqlDataReader.TryNextResult(Boolean& more)
   at System.Data.SqlClient.SqlDataReader.<>c__DisplayClass187_0.<NextResultAsync>b__1(Task t)
   at System.Data.SqlClient.SqlDataReader.InvokeRetryable[T](Func`2 moreFunc, TaskCompletionSource`1 source, IDisposable objectToDispose)

**Comment by skoruba** [comment]
@john159753 - Are you using IS4 Admin from template or fork version? It looks like that something went wrong with `IdentityClaims` - can you check that you have registered correctly - `_ViewImports.cshtml` - taghelpers - `@addTagHelper *, Skoruba.IdentityServer4.Admin` - according your namespace.
That is my first tip - take a look that Picker component correctly collect data for storing.
Thank you.

**Comment by john159753** [comment]
Sorry if none of this makes sense... Some of the ,NET Core concepts are still new to me.

I was stepping through the code and noticed that when `_identityResourceService.UpdateIdentityResourceAsync` is called, the IdentityResourceDto that is passed to it contains the Id property. Somewhere between this method being called and the record getting updated in the DB, my Id property is getting set to null. EF is still a very new concept to me, I looked through the IdentityResourceRepository and IdentityResourceService classes and saw nothing to note.

Any idea on how i can debug this further?

**Comment by skoruba** [comment]
Let me check it, I'll contact you.
Thanks.

**Comment by skoruba** [comment]
Please, send me screenshot of your form with identity resource. I'd like to check your Picker component.
Thanks.

**Comment by skoruba** [comment]
Any update for this? :)

**Comment by john159753** [comment]
Sorry about the Delay Jan, Here are a few screenshots. All the data looks to be there.
![image](https://user-images.githubusercontent.com/12056448/54089495-60ee4100-4337-11e9-97d4-9a86a54ce229.png)

![image](https://user-images.githubusercontent.com/12056448/54089500-6f3c5d00-4337-11e9-8e5a-b85358f94949.png)


Let me know if you have any suggestions on where to break the code and inspect any variables.

**Comment by john159753** [comment]
This is the farthest i've drilled down. I still see all the properties specified in the watch window, including ID. 
![image](https://user-images.githubusercontent.com/12056448/54089737-3487f400-433a-11e9-833c-f41b6b395b64.png)


Yet according to the logs on the server, it is trying to update on the DB without the ID field.
`Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Cannot insert the value NULL into column 'Id', table 'IdentityServer.dbo.IdentityClaims'; column does not allow nulls. UPDATE fails.`

Oddly, enough, this isn't just a problem with IdentityResources. I see the same for clients and apiresouirces (haven't tried others yet). I get the error for creates and updates, **I have not attempted to delete any entries yet.**

**Comment by skoruba** [comment]
Which database do you use? MS SQL Server?

**Comment by john159753** [comment]
Yes, MS SQL.

**Comment by skoruba** [comment]
OK, Let me check it. :)
Do you have full access to services and repositories? Or do you use project from template?
Thanks.

**Comment by john159753** [comment]
I built from the template. I'm not sure what you mean by full services and repositories, but I can definitely build from source if you would like and i have full access on it all.

**Comment by skoruba** [comment]
Did you try it same use case with full clone of this repository? Thank you.

**Comment by john159753** [comment]
I have not tried that, I will do a full clone (not from template) and report back.

Thank you!

**Comment by skoruba** [comment]
Any update? ;)
Please, try latest version from master branch.
Thanks!

**Comment by john159753** [comment]
Hey!
I just got to getting the latest version from the branch. Unfortunately the issue still persists. 

Since i have the source now, i am going to attempt to step through the code and try to pin point where its going wrong. I will comment my findings!

**Comment by john159753** [comment]
Okay, I think i know the issue.

My database does not have the identity flag set on any tables. Because of this, inserts do not work because there is no identity column defined.

I think what i need to do is recreate the tables with the Identity columns set.

I am closing this for now, i think this should take care of the issue.
Thanks for your help through this!

**Comment by skoruba** [comment]
Thank you for your feedback :-)
