### ISSUE TITLE
Guid Identifier

### ISSUE THREAD

**Issue by gokayokutucu** [skoruba/IdentityServer4.Admin#207]
Hi,
I actually wonder why don't you use primary and other identity fields as Guid as default?

**Comment by skoruba** [comment]
Hi @gokayokutucu - we have changed it back to Guid, currently available on dev branch.
Please take a look: [here](https://github.com/skoruba/IdentityServer4.Admin/tree/dev)

**Comment by gokayokutucu** [comment]
Thank @skoruba.
It looks great!

**Comment by skoruba** [comment]
Done on `master`. Please check new release.
Thanks!
