### ISSUE TITLE
建议从mvc改成前后端分离模式

### ISSUE THREAD

**Issue by DORAdreamless** [skoruba/IdentityServer4.Admin#220]
建议把admin改成前后端分离模式,后端identity server 部分逻辑不太清楚，愿意参与前端开发(VUE,Element UI)

**Comment by skoruba** [comment]
Hi, currently is available only mvc version of this admin. In the future we will add api for all actions and it will be possible to connect to SPA.
Thanks.

**Comment by gebiWangshushu** [comment]
虽然我英文也一般，但人家作者是用英文的,so:English only。

**Comment by Kurris** [comment]
我自己改成spa的实现了,有兴趣可以看看下面的链接
i made the spa implementation using vue and elementui  :)  
[see more ](https://github.com/Kurris/IdentityServer.STS.Admin)
