### ISSUE TITLE
Can't set new cliams on Identity Resources

### ISSUE THREAD

**Issue by kacey90** [skoruba/IdentityServer4.Admin#226]
I wish to know where/how the claims for an authenticated user is set. I noticed that there's no ProfileService implemented in the identity server project STS where in my experience I set my claims after successful authentication. 
I added a new claim `tenant_id` in the `custom.profile` scope created by default but don't know how to dynamically set it based on the authenticated user. Please what do I do about this?

**Comment by skoruba** [comment]
You can add your own implementation of ProfileService for IS4. 
Please, take a look at default ProfileService for `Asp.Net Core Identity`: https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/master/src/ProfileService.cs

It is possible to register your implementation via method `AddProfileService<>` in IS4 configuration.

In your ProfileService you can populate dynamically your `tenant_id` claim.

**Comment by kacey90** [comment]
Thanks. I already started the process. Your product is really cool by the way ;)

**Comment by skoruba** [comment]
Thank you maybe please take a look at dev branch, because - we added a lot of new features. :)
