### ISSUE TITLE
TagHelpers not loaded from assembly Skoruba.IdentityServer4.Admin

### ISSUE THREAD

**Issue by tornikebubuteishvili** [skoruba/IdentityServer4.Admin#230]
@addTagHelper doesn't add tags on starting project but when I change anything in view TagHelpers are added. 
![Before](https://user-images.githubusercontent.com/29339221/55075667-cd17b700-5050-11e9-8bdc-3af1432bed9f.png)

![after](https://user-images.githubusercontent.com/29339221/55075674-d2750180-5050-11e9-9aef-1403f1e563a8.png)

**Comment by SosoKapianidze** [comment]
Same issue here

**Comment by skoruba** [comment]
Are you using this solution via `dotnet template` or full clone?

**Comment by tornikebubuteishvili** [comment]
I'm using full clone

**Comment by SosoKapianidze** [comment]
Same issue here

**Comment by skoruba** [comment]
Thank you guys for feedback, let me check it.

**Comment by SosoKapianidze** [comment]
any updates?

**Comment by skoruba** [comment]
I can't figure out, where could be issue yet.

**Comment by SosoKapianidze** [comment]
I have hosted on azure also but same problem, which kind of additional information can I provide for you ?

**Comment by skoruba** [comment]
Are you using full clone of this repo or from dotnet new template? Sometimes is problem with name of assembly, if you are renamed your project name. 
Thanks.

**Comment by SosoKapianidze** [comment]
I'm also using full clone

**Comment by skoruba** [comment]
Please, take a look at: https://stackoverflow.com/a/31258916/943403
Can you check your folder name? I think that the name in import should be assembly name but according this answer we can try experiment with folder name as well.
Thanks!

**Comment by SosoKapianidze** [comment]
@skoruba  I see it's problem with VS2019, when I publish project with VS2017 it works but from VS2019 doesn't

**Comment by skoruba** [comment]
Thanks for feedback, now I am installing VS 2019, I will test it ;)

**Comment by skoruba** [comment]
It seems like everything work fine, feel free to reopen this issue.
Thanks
