### ISSUE TITLE
An unhandled exception occurred while processing the request.

### ISSUE THREAD

**Issue by luanSarmento** [skoruba/IdentityServer4.Admin#232]
Hi Guys, 

Im get error to access admin server at my address http://localhost:9000

Im change all ocurrences for Use PostgreSQL database, but i have this erros

______________________________________________________________
An unhandled exception occurred while processing the request.
SocketException: Connection refused
System.Net.Http.ConnectHelper.ConnectAsync(string host, int port, CancellationToken cancellationToken)

HttpRequestException: Connection refused
System.Net.Http.ConnectHelper.ConnectAsync(string host, int port, CancellationToken cancellationToken)

IOException: IDX20804: Unable to retrieve document from: '[PII is hidden]'.
Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(string address, CancellationToken cancel)

InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII is hidden]'.
Microsoft.IdentityModel.Protocols.ConfigurationManager<T>.GetConfigurationAsync(CancellationToken cancel)

______________________________________________________________________

My App STS its work!

I follow tutorial in github to configure my server, but i need help! :(

My infrastructure 

Ubuntu 18.10
AspNet core 2.2
Visual Studio Code
PostgreSQL

**Comment by skoruba** [comment]
Hi,
Please try to restart your STS, sometimes I get this message and after restarting it is working. 
Let me know.

**Comment by luanSarmento** [comment]
Nice Dude!

Im restart my STS, and start admin and STS side by side. It Works

**Comment by luanSarmento** [comment]
> Hi,
> Please try to restart your STS, sometimes I get this message and after restarting it is working.
> Let me know.
