### ISSUE TITLE
Support server to Springboot applications JAVA

### ISSUE THREAD

**Issue by luanSarmento** [skoruba/IdentityServer4.Admin#234]
Hi Guys,

One Question...
Skoruba Identity server have support for JAVA Springboot applications?

Exist some step-by-step to try this implementation?

**Comment by skoruba** [comment]
Hi,
what do you exactly mean with support java apps?
Thanks.

**Comment by luanSarmento** [comment]
I would like to know if I can implement a springboot Java client for example by pointing the authentication service to IdentityServer4

Thanks dude

**Comment by skoruba** [comment]
Yes, you can, I don’t use java but I believe that is possible to use some package which helps you with openidconnect auth. :)

**Comment by skoruba** [comment]
Take a look at:
https://jwt.io/
There is a list of libraries for JWT.
