### ISSUE TITLE
is anybody use in production environment?

### ISSUE THREAD

**Issue by gebiWangshushu** [skoruba/IdentityServer4.Admin#235]
we all knows , currently just a  **beta version**,but i still want to use in production environment。

is anybody tried? any surggerst?

thanks!

**Comment by skoruba** [comment]
I think the version which is on `dev` branch is pretty solid.

We are working on production release.

I want to publish next beta version next week, but this version will be almost RC, but I want to collect some feedback from users. 👍 

Thanks!

**Comment by gebiWangshushu** [comment]
good work！
thanks~

**Comment by StrongGesmbH** [comment]
We have been using the solution with extended user profiles and roles since february this year and it is rock solid.

**Comment by skoruba** [comment]
Thank you for your feedback - @StrongGesmbH

**Comment by gebiWangshushu** [comment]
@StrongGesmbH 👍🏼

**Comment by skoruba** [comment]
Currently it is possible to use in production. Thanks
