### ISSUE TITLE
oidc-client is not able to check session because 'X-Frame-Options' header is set to 'sameorigin'

### ISSUE THREAD

**Issue by kubakeil** [skoruba/IdentityServer4.Admin#237]
oidc-client in SPA application loaded from different host than STS.Identity server is not able to check session `http://localhost:5000/connect/checksession`.
The check is executed within IFrame and STS.Identity has currenly set Xfo to SameOrigin `app.UseXfo(options => options.SameOrigin());`

This also likely re-introduce some fixed IdentityServer issues e.g. [https://github.com/IdentityServer/IdentityServer4/issues/1224](https://github.com/IdentityServer/IdentityServer4/issues/1224)

**Comment by skoruba** [comment]
Thanks!

**Comment by skoruba** [comment]
Fixed on `dev`.

**Comment by skoruba** [comment]
Done on `master`. Please check new release.
Thanks!
