### ISSUE TITLE
Changing table names

### ISSUE THREAD

**Issue by SbGibson** [skoruba/IdentityServer4.Admin#242]
Hi, 
I've two questions on tables naming.
I created the base Core Identity tables with migrations and it created table with AspNet prefix while Skoruba search them without prefix. I had to change it on Skoruba.IdentityServer4.Admin.EntityFramework.Identity.Constants.TableConsts. Is it correct or I'm doing something wrong?
The second one, how I can change the names of admin tables (DeviceCodes, Log etc.)? 
Thanks in advance.

**Comment by skoruba** [comment]
Hi @SbGibson 

you can rename any table in `DbContext` - in method `OnModelCreating` for example like this:

```
builder.Entity<Entity>().ToTable("TableName");
```

https://github.com/skoruba/IdentityServer4.Admin/blob/master/src/Skoruba.IdentityServer4.Admin.EntityFramework.DbContexts/AdminIdentityDbContext.cs#L24

**Comment by wzoet** [comment]
Hi,

Thanks for this nice interface on administering IDSrv. You are doing a great job!

Just found this post while trying to add an issue for this.
Is it a possibility to add this as to the config? I would rather not change code for this as this would require maintaining a different version than yours. Adding it to the config makes for easy upgrading.

Thx!

**Comment by skoruba** [comment]
Sorry for delay, I forgot your question, I don’t want to add this in config, because I think a table name is pretty stable thing. :) feel free to add in your implementation.
Thank you.
