### ISSUE TITLE
2fa issue, when no return url i specified 

### ISSUE THREAD

**Issue by martea** [skoruba/IdentityServer4.Admin#248]
Issue with 2fa login, when no return url is specified.

suggested solution
`            if (result.Succeeded)
            {
	            if (model.ReturnUrl == null)
	            {
		            return LocalRedirect("/");
	            }
                return LocalRedirect(model.ReturnUrl);
            }`

**Comment by skoruba** [comment]
Thanks @martea 
I will check it, if you want - you can send a PR. 👍

**Comment by martea** [comment]
#249
