### ISSUE TITLE
Adding public origin to configuration of STS

### ISSUE THREAD

**Issue by xmichaelx** [skoruba/IdentityServer4.Admin#258]
In many cases STS is behind some proxy or load balancing so the default origin used in discovery document for prepending endpoints inferred from request may be a local one inferred from passed request.

[PublicOrigin](http://docs.identityserver.io/en/latest/reference/options.html) is an option that can be set to mitigate that, we should add it to the configuration of STS.

**Comment by aiscrim** [comment]
I am developing a PR to deal with this and other issues related to load balancing configurations. Stay tuned! :)

**Comment by skoruba** [comment]
Thanks @aiscrim

**Comment by skoruba** [comment]
Done in master. Thx
