### ISSUE TITLE
How to use  sendgrid

### ISSUE THREAD

**Issue by denisisack** [skoruba/IdentityServer4.Admin#259]
How to set up send grid settings ,I have tried to set up Api key in AppSettings.json but it does not respond as expected.

```json
"Sendgrid": {
    "apiKey": "##################"
  }
```

**Comment by skoruba** [comment]
@xmichaelx - can you please help with SendGrid settings? :)

**Comment by martea** [comment]
@denisisack
according to the code, you should add a connectionstring with "Sendgrid" as key
and the configuration sections should be like 
"SendgridConfiguration" :{
"SourceEmail": "",
"SourceName": "",
}

**Comment by skoruba** [comment]
@martea - Thanks - I wasn't sure about using of ApiKey ;)

**Comment by denisisack** [comment]
Thanks
