### ISSUE TITLE
Use my own login logic in implicit and hybrid Flow

### ISSUE THREAD

**Issue by gebiWangshushu** [skoruba/IdentityServer4.Admin#262]
hi~skoruba and anybody，a simple question.
We know，in `ResourceOwnerPassword`Flow,we can implement interface `IResourceOwnerPasswordValidator` for my own username and password validation。
but, in `implicit` and `hybrid` Flow ,`IResourceOwnerPasswordValidator` doesn't work.
so ,How can i validate username and password with my own logic in `implicit` and `hybrid` Flow  .

thans~and hope it not spend you too much times.

**Comment by skoruba** [comment]
Sorry for delay - I am not sure what do you want to achieve. You can check user’s credentials in AccountController.

**Comment by gebiWangshushu** [comment]
never mind.sorry for confused you.I will take more time in language;
ths~
