### ISSUE TITLE
ExternalLogin

### ISSUE THREAD

**Issue by gnsilence** [skoruba/IdentityServer4.Admin#264]
code :

public async Task<IActionResult> ExternalLoginCallback(string returnUrl = null, string remoteError = null)
        {
            if (remoteError != null)
            {
                ModelState.AddModelError(string.Empty, _localizer["ErrorExternalProvider", remoteError]);

                return View(nameof(Login));
            }

            var info = await _signInManager.GetExternalLoginInfoAsync();

I want to use GitHub as a third party login，but this info and  returnUrl  always null,  the github Authorization callback URL I set  "http://localhost:5000/account/ExternalLoginCallback"   if  is error 。
I Use a MVC client to login 。

**Comment by skoruba** [comment]
Try setup `Authorization callback URL` to `http://localhost:5000`.

**Comment by gnsilence** [comment]
> Try setup on Github - Authorization callback URL to http://localhost:5000.
This problem has been solved, but If I enter an existing username and mailbox ,then get an error, I'm not sure if it's a bug.  the new username have no problem .

the error is 

NullReferenceException: Object reference not set to an instance of an object.
AspNetCore.Views_Account_ExternalLoginConfirmation.ExecuteAsync() in ExternalLoginConfirmation.cshtml
+
<h4>@Localizer["SubTitle", ViewData["LoginProvider"].ToString()]</h4>

I think ,Here should be show the error like "User name Or MailBox  already exists"

**Comment by skoruba** [comment]
OK, let me check it. ;)

**Comment by skoruba** [comment]
This is a bug, I will fix it.
Thanks for reporting!

**Comment by skoruba** [comment]
Fixed on `dev` branch - can you test it please?
Thanks!

**Comment by gnsilence** [comment]
> 固定在`dev`树枝上 - 你能测试一下吗？
> 谢谢！

Okay, I'll test and reply to the results.

**Comment by gnsilence** [comment]
I have finished the test. This error has been resolved. The hint I got was that the mailbox or username had already been used. It's perfect.I will continue to use it. If there are other errors, I will give you feedback in time. I hope it will get better and better.

**Comment by skoruba** [comment]
Great, I will look forward to your feedback. 
Thanks.
