### ISSUE TITLE
Configurations 

### ISSUE THREAD

**Issue by tomadj** [skoruba/IdentityServer4.Admin#266]
Hi @skoruba ,

Is there any particular reason why some Configurations Implement an interface like : 

- AdminConfiguration --> IRegisterConfiguration 
- RegisterConfiguration -->  IRegisterConfiguration 
- (RootConfiguration --> IRootConfiguration )

and others not, like : 

- LoginConfiguration
- SendgridConfiguration
- CertificateConfiguration
- ... 

Thank's 

Thomas

**Comment by tomadj** [comment]
Because they are never injected

**Comment by skoruba** [comment]
Thanks for feedback, I will take a look at these configurations and create same identical approach. What do you suggest?
