### ISSUE TITLE
Sorry, there was an error : unauthorized_client

### ISSUE THREAD

**Issue by shepparddigital** [skoruba/IdentityServer4.Admin#270]
I've set up a new project using .Net Core 2.2 on a Mac. I created a database and added the connection string to both the Admin and STS.Identity projects. Following the instructions in the README I have added and ran migrations which have created empty database tables.

The problem I seem to be having is that there is no client setup in the database, so the client details specified in Admin/appsettings.json are invalid. When I run the solution and try accessing the admin interface on port 9000, I see 'Sorry, there was an error : unauthorized_client'

What is the best way to set up a default client?

**Comment by skoruba** [comment]
Take a look at Program.cs in Admin project, there is method for seeding first admin uder and client for adminui - https://github.com/skoruba/IdentityServer4.Admin/blob/master/README.md#we-suggest-to-use-seed-data

**Comment by shepparddigital** [comment]
Perfect, thank you
