### ISSUE TITLE
Exception: Certificate not found after upload to azure ..with StoreLocation.CurrentUser set

### ISSUE THREAD

**Issue by DjStitch** [skoruba/IdentityServer4.Admin#273]
Not sure why ...error after all step below.

- After uploading the my self sighed Private Certificate to azure
- setting UseSigningCertificateThumbprint to "true"
- setting the SigningCertificateThumbprint of zures thumbprint..
- even set ...WEBSITE_LOAD_CERTIFICATES

I got the error ....

I was forced to use a physical path to .pfx file setting UseSigningCertificatePfxFile to true and specifying the path ..it works.

Exception: Certificate not found
EasyCore.STS.Identity.Helpers.IdentityServerBuilderExtensions.AddCustomSigningCredential(IIdentityServerBuilder builder, IConfiguration configuration, ILogger logger) in IdentityServerBuilderExtensions.cs, line 45

Exception: Certificate not found
EasyCore.STS.Identity.Helpers.IdentityServerBuilderExtensions.AddCustomSigningCredential(IIdentityServerBuilder builder, IConfiguration configuration, ILogger logger) in IdentityServerBuilderExtensions.cs
EasyCore.STS.Identity.Helpers.StartupHelpers.AddIdentityServer<TConfigurationDbContext, TPersistedGrantDbContext, TUserIdentity>(IServiceCollection services, IConfiguration configuration, ILogger logger, IHostingEnvironment hostingEnvironment) in StartupHelpers.cs
EasyCore.STS.Identity.Helpers.StartupHelpers.AddAuthenticationServices<TConfigurationDbContext, TPersistedGrantDbContext, TIdentityDbContext, TUserIdentity, TUserIdentityRole>(IServiceCollection services, IHostingEnvironment hostingEnvironment, IConfiguration configuration, ILogger logger) in StartupHelpers.cs
EasyCore.STS.Identity.Startup.ConfigureServices(IServiceCollection services) in Startup.cs
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

**Comment by skoruba** [comment]
Please try change last parameter to false:
https://github.com/skoruba/IdentityServer4.Admin/blob/master/src/Skoruba.IdentityServer4.STS.Identity/Helpers/IdentityServerBuilderExtensions.cs#L42

**Comment by DjStitch** [comment]
A..ha ... that worked ..thanks
