### ISSUE TITLE
SSO In Different browsers 

### ISSUE THREAD

**Issue by gnsilence** [skoruba/IdentityServer4.Admin#275]
Hi, Have you tried it in different browsers.Multiple clients log in using different browsers 
and logout.
After testing, I found that unified login and login could not be achieved in different browsers. 
Do I need to set something up?

**Comment by skoruba** [comment]
Hi, every browser has own cookie which is used for SSO, you can’t share cookies across browsers.

**Comment by gnsilence** [comment]
> Hi, every browser has own cookie which is used for SSO, you can’t share cookies across browsers.

I also thought of that. I'm going to implement a unified logout first, which will use the back-end logout channel.

**Comment by gnsilence** [comment]
> Hi, every browser has own cookie which is used for SSO, you can’t share cookies across browsers.

I also thought of that. I'm going to implement a unified logout first, which will use the back-end logout channel.

**Comment by skoruba** [comment]
May I close this issue?
Thanks.

**Comment by gnsilence** [comment]
> May I close this issue?
> Thanks.

Yes,
