### ISSUE TITLE
I have one question regarding Login Ui

### ISSUE THREAD

**Issue by sudheeshv** [skoruba/IdentityServer4.Admin#277]
Why are we using mvc razor page for login ? why it's not separating like API and Angular or react UI ? Please help me to understand and what is the security breach ?

**Comment by skoruba** [comment]
If you want to use IdentityServer4 - you need use server-side login screen, because of cookies (for example for SSO) and everything stuff around that.

**Comment by sudheeshv** [comment]
> If you want to use IdentityServer4 - you need use server-side login screen, because of cookies (for example for SSO) and everything stuff around that.

Then how the same will work for Mobile Application ? If i want to use same SSO Login for Mobile application then how does it will work ? May be i am asking some wrong questions please help me to understand the scenario if i am wrong

**Comment by fudgeboy2000** [comment]
> > If you want to use IdentityServer4 - you need use server-side login screen, because of cookies (for example for SSO) and everything stuff around that.
> 
> Then how the same will work for Mobile Application ? If i want to use same SSO Login for Mobile application then how does it will work ? May be i am asking some wrong questions please help me to understand the scenario if i am wrong

Not sure if this is the most common way, but in our Xamarin app we use a webview control to visualise our IdentityServer login page to handle the auth flow/token exchange.

**Comment by skoruba** [comment]
Look at this sample:
https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/master/XamarinForms

**Comment by skoruba** [comment]
This video describes - how to use IS4 with native clients like mobile apps - including solving login screen etc. https://vimeo.com/205451987
Thanks

**Comment by Munde** [comment]
Also you may look at this sample.
https://sinclairinat0r.com/2018/12/09/secure-data-access-with-identityserver4-and-xamarin-forms

**Comment by sudheeshv** [comment]
Thank you @skoruba @Munde
