### ISSUE TITLE
How to connect angular application to skoruba identity server?

### ISSUE THREAD

**Issue by sudheeshv** [skoruba/IdentityServer4.Admin#278]
I have created one angular application and trying to register with soruba identity server using admin portal. I have registered client with client id and name redirect url etc. I have followed the same procedure which i used to follow with identity server. but it's not redirecting to login page and authentication not working. let me know if you have any document which i can follow for on boarding one application using admin ui ?

**Comment by sudheeshv** [comment]
I have created one angular application and trying to register with soruba idenetity server using admin protal. I have registered client with client id and name redirect url  etc. I have followed the same procedure which i used to follow with identity server. but it's not redirecting to login page and authendication not working. let me know if you have any document which i can follow for onboarding one application using admin ui ?

**Comment by skoruba** [comment]
You can create new client with template for SPA and then use client settings something like this:
https://github.com/IdentityServer/IdentityServer4/blob/master/samples/Quickstarts/6_JavaScriptClient/src/IdentityServer/Config.cs#L120-L137

**Comment by sudheeshv** [comment]
I did the same before and it is working fine. I have migrated to skoruba because admin ui and it is more user friendly. below screen also doing the same right ? 

![image](https://user-images.githubusercontent.com/2003489/57767375-dbf61e00-7711-11e9-8728-23ff3930fac9.png)


![image](https://user-images.githubusercontent.com/2003489/57767330-c1bc4000-7711-11e9-8761-8c57dbd1f50f.png)

**Comment by sudheeshv** [comment]
> You can create new client with template for SPA and then use client settings something like this:
> https://github.com/IdentityServer/IdentityServer4/blob/master/samples/Quickstarts/6_JavaScriptClient/src/IdentityServer/Config.cs#L120-L137

I did the same before it is working. But now i want to add client dynamically using skoruba ui which i mentioned in above comment.

**Comment by skoruba** [comment]
What do you mean - add new clients dynamically?

**Comment by sudheeshv** [comment]
> What do you mean - add new clients dynamically?

I will register new applications using admin portal.  I have followed the same in skoruba it is working. But I am getting CORS error now Access to XMLHttpRequest at 'https://localhost:5001/.well-known/openid-configuration' from origin 'https://localhost:44311' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by skoruba** [comment]
Did you configure this url (https://localhost:44311) into collection `AllowedCorsOrigins`?

**Comment by sudheeshv** [comment]
Yes it is working fine.

**Comment by Matthew-J-Spencer** [comment]
Sorry to necro. We're still experiencing a cors issue after 'dynamically' creating a client. We add the url in AllowedCorsOrigins and it actually performs the authentication, but is then rejected on the /connect/userinfo call after redirecting to the callback page.

I can get it working by manually setting cors like so:
`app.UseCors(o => o.AllowAnyHeader().AllowAnyMethod().WithOrigins("http://localhost:8080"));`

But I assume this should happen automagically via skoruba, right?

**Comment by j-tee** [comment]
> You can create new client with template for SPA and then use client settings something like this: https://github.com/IdentityServer/IdentityServer4/blob/master/samples/Quickstarts/6_JavaScriptClient/src/IdentityServer/Config.cs#L120-L137

This link is broken
