### ISSUE TITLE
enable profile service to return roles in access token

### ISSUE THREAD

**Issue by koo9** [skoruba/IdentityServer4.Admin#281]
does it support out of the box to return user roles already?

**Comment by skoruba** [comment]
You need associate role claim into some scope and this scope use for getting access token. You do not need modify Profile service.

**Comment by koo9** [comment]
@skoruba  is there any example somewhere? or steps in doing that in the admin UI?

**Comment by skoruba** [comment]
@koo9 - you can check dev branch and Api project, I use role claim for access to swagger ui.
https://github.com/skoruba/IdentityServer4.Admin/blob/dev/src/Skoruba.IdentityServer4.Admin/Configuration/IdentityServer/Resources.cs#L35
If you have any issue, let me know.
Thanks!

**Comment by xaviergxf** [comment]
Hi @skoruba , i'm trying to include roles into the access token but i can't. Can you provide an example?

Thanks

**Comment by hitcSimon** [comment]
How can I add it in your newest IdentityServer version? I can't reach the link above.
Thank's a lot.

**Comment by kunleshipo** [comment]
Hello, Please I am having same issue here, I have added the api scope but can't see role on the list of claims to add. Please help me.

**Comment by EngDuraid** [comment]
> @koo9 - you can check dev branch and Api project, I use role claim for access to swagger ui. https://github.com/skoruba/IdentityServer4.Admin/blob/dev/src/Skoruba.IdentityServer4.Admin/Configuration/IdentityServer/Resources.cs#L35 If you have any issue, let me know. Thanks!

Thank you but The link is not working  and I have the same problem

**Comment by EngDuraid** [comment]
> @koo9 - you can check dev branch and Api project, I use role claim for access to swagger ui. https://github.com/skoruba/IdentityServer4.Admin/blob/dev/src/Skoruba.IdentityServer4.Admin/Configuration/IdentityServer/Resources.cs#L35 If you have any issue, let me know. Thanks!

Thank you but The link is not working  and I have the same problem
