### ISSUE TITLE
Role and feature mapping how we can achieve dynamic authorization using Identity Server  ?

### ISSUE THREAD

**Issue by sudheeshv** [skoruba/IdentityServer4.Admin#282]

**Comment by sudheeshv** [comment]
Role and feature mapping how we can achieve dynamic authorization using Identity Server

**Comment by skoruba** [comment]
What do you mean with dynamic authorization? Please describe your scenario.

**Comment by sudheeshv** [comment]
> What do you mean with dynamic authorization? Please describe your scenario.

I have a requirement where common admin module. which will create users for multiple applications and the same module will allocate some features based on their roles. 

How we will achieve the same using Identity Server and .net core ? 

Dynamic means i will have a list of features. I will create roles and allocate few features and add user assign role to the user.

**Comment by sudheeshv** [comment]
I am developing a multi tenant application. I want to develop admin module using identity server. My requirement is this module i can create user roles applications and features. Features will assign to roles and role will apply to the users. How i will control the user accessing un authorized features using identity server.

**Comment by skoruba** [comment]
If I understand correctly, you probable want to create some custom policies for authorization like this:
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-2.2
Is it what you looking for?

**Comment by sudheeshv** [comment]
> If I understand correctly, you probable want to create some custom policies for authorization like this:
> https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-2.2
> Is it what you looking for?

No.... above mentioned reference explaining how we can enable authorization in .net core. What I am looking is a role weds feature mapping and authorization using .net core and identityserver4.

**Comment by skoruba** [comment]
Sorry for delay, have you find out the solution, yet? I have never implemented this feature before.

**Comment by sudheeshv** [comment]
> Sorry for delay, have you find out the solution, yet? I have never implemented this feature before.

I got few options and started implementing. Still i am searching better option for managing authorization dynamically.

**Comment by skoruba** [comment]
If you want, you can share it. 👍 
Thanks.

**Comment by sudheeshv** [comment]
> If you want, you can share it. 👍
> Thanks.
Yes I will do once I complete the implementation.
