### ISSUE TITLE
Skoruba.IdentityServer4.Admin.BusinessLogic.Mappers.ClientMappers exception when upgrading from automapper 8.0.0 to 8.1.0

### ISSUE THREAD

**Issue by baywet** [skoruba/IdentityServer4.Admin#283]
Hi,
my project was generated using beta5.
When upgrading from automapper 8.0.0 to 8.1.0, the Clients vieew (Configuration/Clients) stopped working with the following exception:
```
'Skoruba.IdentityServer4.Admin.BusinessLogic.Mappers.ClientMappers' threw an exception. <--- Exception has been thrown by the target of an invocation. <--- Method not found: 'AutoMapper.IMappingExpression`2<!0,!1> AutoMapper.IMappingExpression`2.ConstructUsing(System.Linq.Expressions.Expression`1<System.Func`2<!0,!1>>)'.
```

**Comment by skoruba** [comment]
Hi,
thanks, I will check it, can you suggest some fix for this?

**Comment by baywet** [comment]
I'd have to investigate further and I don't know very well the detailed way to work if this project.
I'll probably invest the time into upgrading to beta 6 first and then see if the problem is still here or not. So it might be a while before I can spend time on this.

**Comment by pbros** [comment]
I have the same error. I rolled back for now

**Comment by pbros** [comment]
Version 8.1.1 is out now. Did anybody check to see if the issue was fixed? If not, I'll try upgrading tomorrow.

**Comment by skoruba** [comment]
If you have any suggestion for this issue, please share it :)

**Comment by pigwing** [comment]
@skoruba it is idsvr4 problem,current idsvr4 version 2.5 solve this problem,can you upgrade the dll to idsvr 2.5 version?^_^

**Comment by curtisconner** [comment]
Upgraded to the idsvr 2.5 but still have the same issue.  
IdentityServer4 - v2.5.2
IdentityServer4.EntityFramework v2.5.2
Skoruba.IdentityServer4.Admin.BusinessLogic v1.0.0-beta7
Skoruba.IdentityServer4.Admin.BusinessLogic.Identity v1.0.0-beta7

checked to see every package is the newest but still get the error.

thanks. if I can send you more information just let me know. Also using EF and SQL Server

**Comment by skoruba** [comment]
Fixed and available in master
