### ISSUE TITLE
documentation upgrade path from beta5 to beta6

### ISSUE THREAD

**Issue by baywet** [skoruba/IdentityServer4.Admin#284]
Hi,
As beta6 as been released a month ago we're looking into upgrading our project generated with beta5 to beta6.
However I can't find any upgrade documentation, it'd be helpful to have such documentation, or even just a checklist, to make sure we don't forget anything.
Having this checklist as part of the release notes would probably the best way to find it.

**Comment by skoruba** [comment]
Hi,
this is great point, I will create some migration document for next releases, but beta6 has massive rewrite of identity model, that you should probable create new project from template and compare manually what it is changed.
Other releases should be more stable, without breaking changes - I hope. :)

**Comment by baywet** [comment]
Thanks! Yes creating a new project and comparing with current is a bit of a heavy upgrade path.
Also the beta 6 release is only showing 7 commits. Is it possible that either beta 5 or beta 6 is tied to the wrong commit? https://github.com/skoruba/IdentityServer4.Admin/releases/tag/1.0.0-beta6

**Comment by skoruba** [comment]
It should be connected with correct commit.

**Comment by baywet** [comment]
Hum, you're right, I was a bit confused by the UI, the diff link is https://github.com/skoruba/IdentityServer4.Admin/compare/1.0.0-beta5...1.0.0-beta6

**Comment by skoruba** [comment]
For sure, it looks correct. :)

**Comment by skoruba** [comment]
@baywet - I am currently closing this issue, because I will release new beta version and this will be outdated. :)
Thanks for this feedback, I will create some docs about breaking changes for new release.

**Comment by baywet** [comment]
So you will document how to go from beta 5 to 7 or only 6 to 7?

**Comment by skoruba** [comment]
Probable both versions. ;)
