### ISSUE TITLE
User Applications

### ISSUE THREAD

**Issue by EstebanMellado** [skoruba/IdentityServer4.Admin#295]
Hello!
How can i set up for add permissions to users to access specific applications?
For example:
User1 can access to app1
User2 can access to app2
etc.

Thanks

**Comment by skoruba** [comment]
Hi, in your application you can add some authorization checks - I mean check some user claims - for example - user1 must have the claim called role=user_app1.

**Comment by EstebanMellado** [comment]
Thanks! I'll try it
