### ISSUE TITLE
Admin  unauthorized_client after deploy to azure

### ISSUE THREAD

**Issue by JannyM85** [skoruba/IdentityServer4.Admin#297]
Hi, I publish both site to azure. I created database and run seed. I can login to sts, but when i try go to admin I get the error unauthorized_client. When i remove autorize atribute from HomeController  i see UI. I changed URL in applicationSettings. json, lanuchSettings.json, and in AdminConfiguration object but does not help me.

**Comment by skoruba** [comment]
Hi,
can you check logs, please? You can check log file or in DB.
Thanks.

**Comment by JannyM85** [comment]
[Logs.xlsx](https://github.com/skoruba/IdentityServer4.Admin/files/3294143/Logs.xlsx)

**Comment by JannyM85** [comment]
Hi, please do you have any idea? I try it on localhost and its work fine, but when is application in azure attribute Autorization does not work. When i remove Autorization atribute, admin works fine. Thanks.

**Comment by skoruba** [comment]
I can not find any issue in this log.
Please try check - if you have correctly set in admin ui client props:
RedirectUri
ClientSecret
- try more explore log, this must generates better error message.

**Comment by skoruba** [comment]
Any update on this issue? 
Thanks

**Comment by skoruba** [comment]
I am closing now, if you have any questions, please let me know.
Thanks.

**Comment by HashTagDotNet** [comment]
I too am getting this error and I don't see the Serilog Log table.

**Comment by dithamar** [comment]
I have the same error
