### ISSUE TITLE
Connecting sample IS to database managed by IdentityServer4.Admin

### ISSUE THREAD

**Issue by xmichaelx** [skoruba/IdentityServer4.Admin#30]
Hello,

First of all, big thanks for doing this. You saved me a tremendous amount of work.

Why haven't you connected IdentityServer4 to the database modified by Admin panel? I understand that you could've done for the sake of simplicity and that's why you've opted for in memory stores but I'm curious if there's any other reason.

 I'm working on having IS from `Skoruba.IdentityServer4` connected to database modified in `Skoruba.IdentityServer4.Admin`. If I connect them are you interested in a pull request?

**Comment by skoruba** [comment]
Hello @xmichaelx 

I really appreciate your feedback.

You are right, the in-memory users / clients in `Skoruba.IdentityServer4` are for simplicity.

I will be happy for any pull request from you. I will consider your idea.

It's possible to follow this sample for doing that - https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Quickstarts/Combined_AspNetIdentity_and_EntityFrameworkStorage

Btw: What do you think about issue #28 - creating the UI and services as nuget package?

**Comment by xmichaelx** [comment]
Certainly, it would be nice to have a nuget package. Add to that some ability for branding with additional powered by <here your credentials> and you have a very nice, generic solution.

**Comment by xmichaelx** [comment]
Right now I'm trying to reference `AdminDbContext `but for that I need to reference dll with Skoruba.IdentityServer4.Admin. Unfortunately this creates situation where I reference another MVC project and I fail because of:

`InvalidOperationException: The AuthorizationPolicy named: 'RequireAdministratorRole' was not found.`

As I understand this policy is present on controllers in the `Skoruba.IdentityServer4.Admin.Controllers` namespace. I need to find a way to only reference `AdminDbContext` without MVC picking up all MVC stuff from the other assembly :)

**Comment by skoruba** [comment]
It's interesting. I think it's time to split the project into two parts - UI and Services.

Thank you - I'll check it and create some fix for this use case. :)

**Comment by skoruba** [comment]
I see. :) I think, splitting of the solution will be better approach - but good quick workaround.

**Comment by xmichaelx** [comment]
I agree, splitting solution will be much better.

**Comment by skoruba** [comment]
#41 - splitting solution, next step will be switching the inmemory store to the database.

**Comment by skoruba** [comment]
DONE.
