### ISSUE TITLE
Acquire application token for Microsoft Graph API

### ISSUE THREAD

**Issue by Auroustech** [skoruba/IdentityServer4.Admin#302]
I have an application that needs to be able to call Microsoft Graph API without a user.  It would use the ClientId and ClientSecret.  Can this be set up to work through IdentityServer4 using your Admin?

**Comment by skoruba** [comment]
If you want to call Microsoft Graph API - you need retrieve an access token from their Identity Provider.
If you are looking for forwarding access token of external provider - take a look at these resources:
https://stackoverflow.com/a/45767061/943403
https://github.com/waqaskhan540/IdentityServerExternalAuth
http://docs.identityserver.io/en/latest/topics/extension_grants.html

**Comment by Auroustech** [comment]
Thank you.  I will have a look at that right away.

**Comment by skoruba** [comment]
May I close it? Do you have any issues?

**Comment by skoruba** [comment]
Feel free to reopen.
