### ISSUE TITLE
Why I am getting this error page? Grant types list cannot contain both implicit and hybrid

### ISSUE THREAD

**Issue by Danni-Ke** [skoruba/IdentityServer4.Admin#309]
![image](https://user-images.githubusercontent.com/46721114/60776525-8b260300-a15f-11e9-84bc-b5cc11baf96d.png)

**Comment by skoruba** [comment]
Where did you get this error? It looks like you selected implicit and hybrid flow for one client which is not possible?

**Comment by Danni-Ke** [comment]
@skoruba  Hi, I am new to the IdentityServer4, I got this since I add new grant type for  skoruba_identity_admin_api_swaggerui, which means I selected implicit and hybrid flow for one client at the same time. I am not quite sure what causes this.

**Comment by skoruba** [comment]
You need to choose implicit or hybrid flow for this client, not both. What do you want to achieve?

**Comment by Danni-Ke** [comment]
@skoruba actually I just mistakenly added both of the ways of authorization. Nevermind, : ). Again, thanks for replying, after I delete one of them, it works normally.
