### ISSUE TITLE
IdentityController.cs parameter TRoleDto cannot implicitly convert type...

### ISSUE THREAD

**Issue by cmiller0352** [skoruba/IdentityServer4.Admin#311]
IdentityController.cs
`[HttpGet]
        public async Task<IActionResult> UserRolesDelete(TUserDtoKey id, TRoleDtoKey roleId)
        {
            await _identityService.ExistsUserAsync(id.ToString());
            await _identityService.ExistsRoleAsync(roleId.ToString());

            var userDto = await _identityService.GetUserAsync(id.ToString());
            var roles = await _identityService.GetRolesAsync();

            var rolesDto = new UserRolesDto<TRoleDto, TUserDtoKey, TRoleDtoKey>
            {
                UserId = id,
                RolesList = roles.Select(x => new SelectItem(x.Id.ToString(), x.Name)).ToList(),
                RoleId = roleId,
                UserName = userDto.UserName
            };

            return View(rolesDto);
        }`
![image](https://user-images.githubusercontent.com/46453611/61087326-ede6fb00-a3fa-11e9-9b44-6bd412a3c879.png)

**Comment by cmiller0352** [comment]
I havent touched these files, just updated nuget packets to new versions and now get this error

**Comment by skoruba** [comment]
You need use correct namespace for object SelectItem probable, what I can see from error message. I move this object to another project.

**Comment by cmiller0352** [comment]
Thanks! Ill look for those changes.
