### ISSUE TITLE
Getting Invalid Column Name 'Created'

### ISSUE THREAD

**Issue by cmiller0352** [skoruba/IdentityServer4.Admin#312]
I have verified that the column exists and is set up in SSMS correctly. I have full functions of adminUI connected to an existing identity server, with this exception. I cannot edit or delete Clients from the adminUI without getting an error ==> Invalid Column Name 'Created'

**ConfigurationController.cs**
`        [HttpGet]
        [Route("[controller]/[action]")]
        [Route("[controller]/[action]/{id:int}")]
        public async Task<IActionResult> Client(int id)
        {
            if (id == 0)
            {
                var clientDto = _clientService.BuildClientViewModel();
                return View(clientDto);
            }

            var client = await _clientService.GetClientAsync(id);
            client = _clientService.BuildClientViewModel(client);

            return View(client);
        }
`

**Comment by skoruba** [comment]
Did you correctly apply new db changes via migrations?

**Comment by cmiller0352** [comment]
I did. I ran updates hoping this would correct the issue, and it did not. I have verified that I can create new records into the db, delete, update, etc.. just not for clients. 

I used the Debug>Windows>Exception Settings> Common Language Runtime Exceptions checked on and was getting breaks due to cannot find 'dbo.logs' which is where I am currently inspecting why this is. I used a different schema name => 'IdentityServer' so it should be looking for IdentityServer.Logs not 'dbo'. I applied the `builder.HasDefaultSchema("IdentityServer");` changes to my dbContext as well as the configuration/persisted grant db context files `storeOptions.DefaultSchema = "IdentityServer";`

Thanks btw for your fast response! This is awesome! I've learned a ton through trying to setup this adminUI!

**Comment by cmiller0352** [comment]
as soon as it hits the line 
`var client = await _clientService.GetClientAsync(id);
            client = _clientService.BuildClientViewModel(client);
            

            return View(client);`
it breaks. I have confirmed that it knows the id of the client.

**Comment by cmiller0352** [comment]
I tried adding a client to see if in the db, there was a record in the Created Column.
When I hit the Save button to create a new client, I get the invalid column name error,
however, when i look in the db, the client i tried to create is there, with a value in the Created column.
and when I run the adminUI again, the created client is there..

**Comment by cmiller0352** [comment]
Solved: I had an existing identity server, with custom schema, and not all the tables had the columns the adminUI was expecting. Needed to add a 'Created' column in ClientSecrets and ApiSecrets, but was able to get everything up and running.

Thanks for the help!

**Comment by skoruba** [comment]
Thanks for your feedback.
