### ISSUE TITLE
Persisted Grants - allow deleting individual grants

### ISSUE THREAD

**Issue by Peperud** [skoruba/IdentityServer4.Admin#313]
The GUI only allows to delete all grants. This is rather limiting IMO. It seems that more often than not, you'd want to delete a particular grant only, perhaps a set of grants, but not all of them.

**Comment by skoruba** [comment]
You can delete a specific one, check list of grants and in table is button for deleting only one specific row.

**Comment by Peperud** [comment]
My bad. The screen was apparently getting cut off and I didn't notice the scroll bar down there. I'm sorry.
On a different note - clicking on the details button on an _individual_ grant takes you to a screen where _all_ grants for that subject are listed. 
Seems a bit odd. Perhaps either take it to the individual grant details, or group the grants per subject on the previous screen.

**Comment by skoruba** [comment]
I am closing this issue. Thanks
