### ISSUE TITLE
upgrade to ids 2.5 version and automapper 8.1.1 crash

### ISSUE THREAD

**Issue by pigwing** [skoruba/IdentityServer4.Admin#314]
when i open the url http://localhost:9000/Configuration/Clients
and throw an unhandled exception
it is automapper 8.1.1 version problem

MissingMethodException: Method not found: 'AutoMapper.IMappingExpression`2<!0,!1> AutoMapper.IMappingExpression`2.ConstructUsing(System.Linq.Expressions.Expression`1<System.Func`2<!0,!1>>)'.
Skoruba.IdentityServer4.Admin.BusinessLogic.Mappers.ClientMapperProfile..ctor()

TargetInvocationException: Exception has been thrown by the target of an invocation.
System.RuntimeTypeHandle.CreateInstance(RuntimeType type, bool publicOnly, bool wrapExceptions, ref bool canBeCached, ref RuntimeMethodHandleInternal ctor)

TypeInitializationException: The type initializer for 'Skoruba.IdentityServer4.Admin.BusinessLogic.Mappers.ClientMappers' threw an exception.
Skoruba.IdentityServer4.Admin.BusinessLogic.Mappers.ClientMappers.ToModel(PagedList<Client> clients)

TargetInvocationException: Exception has been thrown by the target of an invocation.
System.RuntimeTypeHandle.CreateInstance(RuntimeType type, bool publicOnly, bool wrapExceptions, ref bool canBeCached, ref RuntimeMethodHandleInternal ctor)
System.RuntimeType.CreateInstanceSlow(bool publicOnly, bool wrapExceptions, bool skipCheckThis, bool fillCache)
System.Activator.CreateInstance<T>()
AutoMapper.Configuration.MapperConfigurationExpression.AddProfile<TProfile>() in MapperConfigurationExpression.cs
AutoMapper.MapperConfiguration.Build(Action<IMapperConfigurationExpression> configure) in MapperConfiguration.cs
AutoMapper.MapperConfiguration..ctor(Action<IMapperConfigurationExpression> configure) in MapperConfiguration.cs
Skoruba.IdentityServer4.Admin.BusinessLogic.Mappers.ClientMappers..cctor()

**Comment by skoruba** [comment]
How did you solve this issue?
Thanks.

**Comment by StasPerekrestov** [comment]
https://github.com/AutoMapper/AutoMapper/issues/3117

**Comment by skoruba** [comment]
Thanks 👍🏼

**Comment by StasPerekrestov** [comment]
I suppose if you upgrade ids to 2.5.0 and Automapper to 8.1.1 (this version is in the dependencies here https://www.nuget.org/packages/IdentityServer4.EntityFramework.Storage/), it should resolve the issue

**Comment by StasPerekrestov** [comment]
Even more, it's discussed here https://github.com/IdentityServer/IdentityServer4/issues/3227 and the issue is part of Release Notes https://github.com/IdentityServer/IdentityServer4/releases
