### ISSUE TITLE
How far you are from official 1.0.0 release ?

### ISSUE THREAD

**Issue by cszczotka** [skoruba/IdentityServer4.Admin#315]
Hi,
We are considering usage "Skoruba IdentityServer4" on production env. Currently only beta version is available. How far you are from official 1.0.0 release ? Do you recommend usage beta version on production ?
Thanks,
Czeslaw

**Comment by skoruba** [comment]
Hi, I think that AdminUI and STS are pretty solid, currently I am still collecting the feedback, if everything works fine. 👍🏼😊
Before 1.0.0 - I want to improve API - there are missing some validations (#304)
BTW: We are using latest beta version in production and looks good, but as I mentioned - feedback is still welcome.

**Comment by skoruba** [comment]
Today it was released 1.0.0-rc1. Please take a look at the latest changes.
