### ISSUE TITLE
swagger ui

### ISSUE THREAD

**Issue by devchild** [skoruba/IdentityServer4.Admin#320]
Hi I started a new project using following command:
`dotnet new skoruba.is4admin --name MyProject --title MyProject --adminrole MyRole --adminclientid MyClientId --adminclientsecret MyClientSecret`

The documentation seem to suggest that there should be a swagger ui somewhere.
But there's not reference to any swagger library.

Should I add this myself, or am I missing something

**Comment by devchild** [comment]
![image](https://user-images.githubusercontent.com/6022889/61460332-cc43c180-a96e-11e9-8bf9-4f8b68af3842.png)
Seems like the api isn't generated. Do I need to use another switch?

**Comment by devchild** [comment]
> ![image](https://user-images.githubusercontent.com/6022889/61460332-cc43c180-a96e-11e9-8bf9-4f8b68af3842.png)
> Seems like the api isn't generated. Do I need to use another switch?

Never mind, seems like I have an old template installed

**Comment by skoruba** [comment]
Yes, you have old template, please check the new one. I have added the API in latest beta version. 😊
Thanks!

**Comment by skoruba** [comment]
I am closing it, feel free reopen it.
Thanks
