### ISSUE TITLE
Add Spanish (es) Localization

### ISSUE THREAD

**Issue by carlosomarcp** [skoruba/IdentityServer4.Admin#329]
I'm willing to create the Spanish localization.
This would be my first contrib in github, so I want to confirm:

1. I fork the repository to my account.
2. then create a branch in my repository (in the forked one)
3. commit and push in my repo, 
4. then PR to your repo, 

Is that correct?

Edit:
what branch should I base my change? dev?

**Comment by skoruba** [comment]
Hello, 
yes, this is absolutely correct way. 👍🏼
Please, check out dev branch and from dev you can create a PR with your translations.

Thank you for your interest! 😊

**Comment by DrQwertySilence** [comment]
Are you still working on it?
I have one for prev-7 (missing some messages of the admin project) that I need to update now so I can make a pull request later (2 days max I think).

**Comment by carlosomarcp** [comment]
I've been working on this, but only have the Skoruba.IdentityServer4.STS.Identity project ready. I haven´t had free time =(
If you have a translation, just PR. I don't know when I could finish this.

**Comment by skoruba** [comment]
@DrQwertySilence - Great work, I merged it into dev. 👍 
Thanks!

**Comment by skoruba** [comment]
I am closing this issue, it was released in master branch. Thank you. 👍🏼
