### ISSUE TITLE
Planned support for OAuth Device Flow

### ISSUE THREAD

**Issue by xmichaelx** [skoruba/IdentityServer4.Admin#33]
Device flow will be added in next release of IdentityServer4 and is currently developed:
https://github.com/scottbrady91/IdentityServer4/tree/device-flow

Blog post describing the flow:
http://www.identityserver.com/articles/an-introduction-to-the-oauth-device-flow/

Would you consider adding this flow? I'm willing to help with that since I'll be using that flow a lot.

**Comment by skoruba** [comment]
Absolutely, device flow is on my radar as well. :)

I will be happy for your help with implementation of device flow.

**Comment by skoruba** [comment]
Currently, device flow is part of IS4 2.3 and available in this administration on branch: https://github.com/skoruba/IdentityServer4.Admin/tree/feature/upgrade-ids4-2-3 - I will merge it into master.

**Comment by eduardobarbiero** [comment]
@skoruba did you even merge?

**Comment by skoruba** [comment]
Sure, I will merge it this week. 
Thanks

**Comment by skoruba** [comment]
Done. :)
