### ISSUE TITLE
Add French (fr) localization

### ISSUE THREAD

**Issue by Aegide** [skoruba/IdentityServer4.Admin#330]
I'm willing to create the French localization.

Currently i'm working on setting up everything correctly before the PR.

**Comment by skoruba** [comment]
Perfect, thanks! 😊

**Comment by Aegide** [comment]
Thanks for the fast answer!

Do you think it would be pertinent to keep the english names for the OAuth concepts or use the  french microsoft translations ?

The devs arround me suggest that i keep english names.

Examples : 

**Api scope** => [**Étendue de l'Api**](https://docs.microsoft.com/fr-fr/azure/active-directory/develop/v2-permissions-and-consent)
**Client claim** => [**Revendication client**](https://docs.microsoft.com/fr-fr/dotnet/api/system.security.claims.claim?view=netframework-4.8)

**Comment by skoruba** [comment]
This is really good question. I've checked the our current translations and we are using this types of translation like you mentioned: **Api scope => Étendue de l'Api**. Maybe it would be great - create same style of translation. :)

Thanks!

**Comment by Aegide** [comment]
For most words i can find an equivalent but there are cases where i have absolutely no idea.
And if i translated them directly it would feel weird.

- Subject ID
- Persisted Grant
- Device Authorization Flow
- Client/User claim
- Identity resource

Thanks for the insight, i will see what i can adapt !

**Comment by skoruba** [comment]
For sure, if you don’t have an equivalent, please use english term, this is absolutely fine. 👍🏼 Thanks!

**Comment by Aegide** [comment]
Translation done (118 fr.resx files and 2 culture files).

I'll double check my work and test it before PR.

**Comment by nlz242** [comment]
Question: Did you encounter issues with ModelBinding using the Delete logs feature? 
On my side, it works if i set the UI to English, but it fails when i set it to French because MM/dd/yyyy is not a valid french date format. 
Seems like the DateTime Picker used in this page doesn't change locale to match selected language

**Comment by nlz242** [comment]
#343

**Comment by Aegide** [comment]
I didnt test the `Delete logs feature`.

Nice finding about the DatePicker !

**Comment by nlz242** [comment]
I fixed it in PR #344

**Comment by skoruba** [comment]
Done on dev branch. :)
Thanks for your work guys! 👍
I will merge it to master.

**Comment by skoruba** [comment]
I am closing this issue, it was released in master branch. Thank you 👍🏼
