### ISSUE TITLE
Broken link "ready to use samples" on the Welcome page ?

### ISSUE THREAD

**Issue by Aegide** [skoruba/IdentityServer4.Admin#337]
There are two links to GitHub on the **Welcome page**.
- [source code repository](https://github.com/identityserver/IdentityServer4)
- **[ready to use samples](https://github.com/identityserver/IdentityServer4.Samples)**

But the second link returns an error 404.
I initially thought i would be redirected to one of those three links :
- https://github.com/IdentityServer/IdentityServer4/tree/master/samples
- **https://github.com/IdentityServer/IdentityServer4/tree/master/samples/Quickstarts**
- https://github.com/IdentityServer/IdentityServer4/tree/master/samples/Clients

Also i feel like the structure of the sentence sounds odd.
`Here are links to the source code repository, ready to use samples.`

I was thinking about something like : 
`Here are links to the source code repository and ready to use samples.`
`Here is a link to the source code repository, with ready to use samples.`

Not an important issue, but i saw it mentioned nowhere.

**Comment by skoruba** [comment]
Good catch, can you please send a PR? 😊
Thanks!

**Comment by Aegide** [comment]
I'm struggling to create a new branch `dev/fix-link` in my fork with the current files from the official branch `dev`.
Currently my `dev` is filled with commits of another issue and i need to create a clean branch but i can't clone my own `dev in that state` xd .

**Comment by skoruba** [comment]
Thanks! 😊

**Comment by skoruba** [comment]
I am closing this issue, it was released in master branch.
