### ISSUE TITLE
Question: Restricting a Client to a User

### ISSUE THREAD

**Issue by justki03** [skoruba/IdentityServer4.Admin#338]
Hi,

Is it possible to restrict a Client to a User. 
I'm looking for a way to limit a User A to use only Client A. If User A tries to use Client B, I like to throw a unauthorized message.

**Comment by skoruba** [comment]
Hi,
What do you mean with use client B? Do you mean to access from Admin and change settings of this client? So adding of additional authorization stuff on Admin part?

Thanks.

**Comment by justki03** [comment]
Hi Skoruba,
On the admin page, I would like to restrict User A to only modify/access Client A's information and can not modify/access other Client. Is there a way to do that?

Thanks.

**Comment by skoruba** [comment]
For this use case you need implement some extra policy with your requirements - something like this:
https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-2.2

For example: You can bind the access for some specific client_id for maybe some role name or create your own logic. 😊

**Comment by skoruba** [comment]
I am closing it, feel free reopen. 
Thanks
