### ISSUE TITLE
Minor translation oddities

### ISSUE THREAD

**Issue by Aegide** [skoruba/IdentityServer4.Admin#341]
1°)
https://github.com/skoruba/IdentityServer4.Admin/tree/master/src/Skoruba.IdentityServer4.STS.Identity/Resources/Views/Account

- **RegisterFailure.resx** could be renamed **RegisterFailure.en.resx**
- **RegisterFailure.ru.resx** do no exist

2°)
https://github.com/skoruba/IdentityServer4.Admin/tree/dev/src/Skoruba.IdentityServer4.Admin/Resources/Views/Configuration/Client/Section
- The equivalent to **DeviceFlow.en.resx** is hidden
- **DeviceFlow.ru.resx** do no exist

3°)
https://github.com/skoruba/IdentityServer4.Admin/tree/dev/src/Skoruba.IdentityServer4.Admin/Resources/Views
- **ClientClone.en.resx** is only translated in Swedish

**Comment by skoruba** [comment]
I am closing this issue, it was released in master branch.
