### ISSUE TITLE
DatePicker's locale doesn't change when switching language

### ISSUE THREAD

**Issue by nlz242** [skoruba/IdentityServer4.Admin#343]
In the admin UI, in the logs page, the DatePicker's language is always english (ignores the selected language). 

For example, if i select Russian, the calendar still shows "August" and all the abreviated days in english: 

![image](https://user-images.githubusercontent.com/3332745/63026645-8ef12780-be79-11e9-98a6-c58c8ba8ad4b.png)

The calendar comes with Locales for most cultures and they can be found in Skoruba.IdentityServer4.Admin\node_modules\bootstrap-datepicker\dist\locales 
Probably just have to include them in the gulp script and set the language on the picker as per the documentation here:  https://bootstrap-datepicker.readthedocs.io/en/latest/i18n.html

**Comment by skoruba** [comment]
I am closing this issue, it was released in master branch.
