### ISSUE TITLE
How to use Admin Api

### ISSUE THREAD

**Issue by gzinger** [skoruba/IdentityServer4.Admin#347]
I am trying to call Admin API from another API, which is very common scenario. Usually, one uses Client-Credentials-flow in such chase. This is what I trying to do (for a week already) - I am calling token endpoint passing client_id and client secret and the scope of the adminapi. I got my access token and it validates correctly, but in the last step when I am actually calling the Admin API (to get all clients, for example) I get 403 with the message  in the event log: "IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler
AuthenticationScheme: Bearer was forbidden."

I am guessing this is because the access token doesn't have any roles listed, and the admin api controllers have this Authorization policy that requires administratition role.

So, I tried to add "roles" to the scopes I would like to get back. In this case I am getting an error in the first step - when trying to get a token:
"Client cannot request OpenID scopes in client credentials flow"

It kind of makes sense that we shouldn't get OpenID scopes (like roles in this example) in the workflow that has no end-user involved. It also make sense that you want to protect you admin API with some elevated-permission requirement. What is not clear at all, is to how to call this API? If there is some way to fix it that requires some work on the admin-API side - please describe what exactly should be done and I would be happy to create a PR for you. At this point I just don't see any good solution. Please advise.

**Comment by skoruba** [comment]
Please, try this scenario:
- Add client claim into your client - role and value which is requered in API
- Then you will receive the claim in your api called - “client_role” so you need extend the default authorization for additional check for client_role. Please check in Client object the collection claims and clientclaimsprefix. 
Give me pls info if it is good direction for your use case.
Thanks 😊

**Comment by gzinger** [comment]
Thank you Jan. I actually was able to get trough with the "Password" flow. I created and API user and pass that user's credentials in the PasswordTokenRequest. That works.

Now, I also created an additional admin API method to get user's role's claims. Would I be able to PR it into your main repo or you are not interested in this type of functionality?

**Comment by b0** [comment]
Hi @gzinger, @skoruba 

could you please elaborate your "Password" flow a bit more? 
I am also trying to call Admin.API let's say /api/ApiResources but I am unable to get token for my client. How could I set up my client to call that api? What did you do?

@skoruba 
Is there a sample "console app" for calling Admin.API ? Or some code with relevant configuration for it to work?

Thank you

**Comment by skoruba** [comment]
https://github.com/IdentityServer/IdentityServer4/blob/master/samples/Quickstarts/2_ResourceOwnerPasswords/src/IdentityServer/Config.cs#L71 - here is the configuration which you probable are looking for. You need register new client for your console app and use api name for property called - allowedscopes. Then in your console app you need call api like in this file: https://github.com/IdentityServer/IdentityServer4/blob/master/samples/Quickstarts/2_ResourceOwnerPasswords/src/ResourceOwnerClient/Program.cs#L29

But I recommend use client credential flow instead like I mentioned above.

Please don not forget that user must have a role for administration.

**Comment by b0** [comment]
Hi Jan,

is it possible to enable GitHub [Wiki ](https://help.github.com/en/articles/adding-or-editing-wiki-pages)on this repository? 
I would like to add some info about how to setup client and use it for others to see...

Thank you

**Comment by skoruba** [comment]
Please, you can add new markdown file into folder called docs. I will convert folder docs into readthedocs instead of wiki. :-)
Thank you.

**Comment by b0** [comment]
Sure.

My I suggest you open a gitter community like let's say https://gitter.im/dotnet/home so we talk a bit easier then here. I don't want to "pollute" issues to much ;)

**Comment by skoruba** [comment]
For sure, we already have it - https://gitter.im/skoruba/IdentityServer4.Admin?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by gzinger** [comment]
BTW, the way I was able to get around the issue to create both client and
user credentials and passing them both to create an access token.
Is that what you did or you found some more elegant approach?

**Comment by skoruba** [comment]
@gzinger - Yes, I implemented this with client credentials flow, please check dev branch and authorization stuff in API. You can use client credentials flow and `client_role` claim.

**Comment by skoruba** [comment]
I am closing this issue for now, feel free reopen. Thanks

**Comment by mothswiller** [comment]
I've tried everything above and I simply cannot access the Admin API from a console application. The above GitHub links do not work. Would really appreciate some help

**Comment by mothswiller** [comment]
Just updated to your new net5 version and now all my previously working Client Credential flows are giving an error "invalid scope". Did I miss something?

**Comment by matiasvallejosdev** [comment]
Thank you @skoruba , @gzinger , and @b0 for your helpful discussion and suggestions on this issue. The information provided here was invaluable in helping me understand and resolve my problem with connecting to the Admin API.

I was able to add the necessary client_role claim through the Skoruba UI as suggested. This, combined with the proper configuration of client credentials and scopes, allowed me to successfully authenticate and access the Admin API.

For anyone else facing similar issues, make sure to:
1. Use the Client Credentials flow
2. Add a client_role claim to your client
3. Ensure your scopes match those required by the Admin API
4. Update your API's authorization policies to check for the client_role claim

Thanks again for maintaining this project and providing such helpful support!
