### ISSUE TITLE
Using SQLite as default database engine

### ISSUE THREAD

**Issue by xmichaelx** [skoruba/IdentityServer4.Admin#35]
A modest suggestion. By default Admin uses SqlServer which has to be separately installed for anyone who doesn't use Visual Studio daily.

Required changes would be pretty small:

`UseSqlServer` -> `UseSqlite` in StartupHelpers.cs and adding SQLite provider package for EntityFramework.Core.

I myself use PostgreSQL (works great), but for demonstration purposes I think SQLite would the best choice. This would also make checking out the Admin so much easier for Linux/MacOS folks.

**Comment by xmichaelx** [comment]
No, I'm using VS. But I've used VS Code for other .net core projects before and I could test if that works.

**Comment by skoruba** [comment]
I'll check the possibilities how to combine more configuration of different databases like PostgreSQL, MySQL, SQLite etc.

**Comment by xmichaelx** [comment]
I think that you could have it added to your migration documentation (where to change provider and what packages to add). Info on how you can use different providers (sqlserver, postgresql, sqlite) with default sqlite provider.

**Comment by xmichaelx** [comment]
GH-37
