### ISSUE TITLE
IOS Issues

### ISSUE THREAD

**Issue by cculver** [skoruba/IdentityServer4.Admin#353]
I've got a public deployment using Beta 7 set up and everything's working great on windows. I went to show functionality to a colleague while using my ios 12 iphone and it seems that the redirect from /connect/authorize is not happening. It seems like all required elements have been provided and logs indicate that each time I reload, a token is issued. It's just not redirecting. I am using SameSiteMode.None per the MS advisory. What could I be doing wrong?

**Comment by skoruba** [comment]
I will try it. Do you have any additional logs? 
Thanks.

**Comment by skoruba** [comment]
Feel free reopen
