### ISSUE TITLE
Why do we store Admin ClientID and ClientSecret in AuthenticationConsts ?

### ISSUE THREAD

**Issue by omikolaj** [skoruba/IdentityServer4.Admin#356]
This is a question at this point more so than an issue. I was wondering what was the reason for storing ClientID and ClientSecret in AuthenticationConsts? I see that it is used as default when no ClientID or Client Secret have been set in appsettings.json file, but it exposes the risk of it being 'accidentally' checked into source control. 

Also, is it safe to store ClientID and ClientSecret in the appsettings.json file anyway? Shouldn't this be retrieved from (for local dev) Secret Manager `Configuration["KeyValue"]`... and for production from some other secure key-value pair vault?

**Comment by skoruba** [comment]
You can for sure change this settings for your secure vault for production. What implementation do you suggest for production environment? I think it is specific according to deployment environment, like azure key vault etc.
Thanks.

**Comment by omikolaj** [comment]
I agree with you that this setting is specific to production deployment strategy. My only suggestion would be to not hard coding the `--adminclientsecret` value in `AuthenticationConsts`. I understand this serves the purpose of a fall back mechanism in case the `appsettings.json` file does not have `ClientSecret` value specified. I believe the use of Secret Manager should be encouraged instead. Perhaps having a key in the `appsettings.json` file akin to `ClientSecretVaultKey` which would be used to retrieve the value from Secret Manager for local development (key value pair would need to be set by the developer prior to using it). This set up would also go hand in hand if the application were deployed to Azure, using Azure Key Vault, as `Configuration["Key"]` code, would not have to change when retrieving the secret. Given the key name was configured the same in Azure Key Vault. 

If someone plans on generating a high entropy client secret and using it for both local development and production, hard-coding it when using the `skoruba.is4admin` template, adds additional steps that require you to go in and manually remove it from `AuthenticationConsts`, and from `appsettings.json` file and configure the code to retrieve it from Secret Manager.

**Comment by skoruba** [comment]
On dev branch - I removed default secret from AuthenticationConsts.cs and kept it available only in appsettings.json, there is possible to change it or for production scenario use another safer storage. 
Thanks for your ideas. 👍🏼
