### ISSUE TITLE
Generated resource file names are too long during build

### ISSUE THREAD

**Issue by BalintBanyasz** [skoruba/IdentityServer4.Admin#358]
Building project `Skoruba.IdentityServer4.STS.Identity` fails  with error code `AL1065`: 

> File name 'obj\Debug\netcoreapp2.2\Skoruba.IdentityServer4.STS.Identity.Resources.Views.Shared.Components.IdentityServerAdminLink.Default.en.resources' is too long or invalid

Windows 10 - Visual Studio Community 2019 v16.2.5

The resource file names generated during build are way too long (the path in the build error is 139 characters) and the 260 character limitation is easily exceeded in common scenarios (e.g. in this case the project resides under the default project location `C:\Users\[User Name]\Documents\Visual Studio 2019\Projects\IdentityServer4.Admin`).

Please consider removing the Skoruba.IdentityServer prefix from the project and folder names to fix this issue.  It could also improve legibility.

**Comment by skoruba** [comment]
Please, consider move project into C:\ and some shorter folder name :) I know that the path is long but the prefix for project it is necessary.

**Comment by BalintBanyasz** [comment]
@skoruba Yes, that works of course :) I just wanted to highlight that building the solutions would fail  if someone used the default VS projects location. I'm actually surprised to be the first to run into this issue.

Thank you by the way for this awesome project!

**Comment by skoruba** [comment]
For sure, I faced this issue, but you know I need add this prefix because it is requirement from IS4 - if you want to write some libraries regarding to IS4, it is necessary to use own prefix, which totally makes sense - it is not official IS4 library but contribution only. :)
