### ISSUE TITLE
Connect with Xamarin.Forms application

### ISSUE THREAD

**Issue by messaddek** [skoruba/IdentityServer4.Admin#359]
Hello,

I've implemented the skoruba solution on my application. I need to connect both Angular SPA APP, Xamarin and API with the IdentityServer authentication SSO.
Both (admin and sts) are deployed on azure.
When i tried to achieve connection, i've created xamarin client, the login page is shown, but there is error redirection with remote authentication exception (obtained from log section in the admin app).
How to resolve this error? I've performed several searches in google, but no one gives the right solution.

Thanks,

Regards.
Mohammed

**Comment by skoruba** [comment]
Can you please share error message? Thanks

**Comment by messaddek** [comment]
Hello, i've resolved the problem, the problem was with endpoint urls.

All is working correctly right now
