### ISSUE TITLE
Update to .NET Core 3.0

### ISSUE THREAD

**Issue by skoruba** [skoruba/IdentityServer4.Admin#360]

**Comment by pbros** [comment]
Is beta7 the last version that will run on .NET Core 2.x? Any chance the beta8 or first release will still be compatible with .NET Core 2.x?

**Comment by skoruba** [comment]
Is not possible to update to .Net Core 3.0 for your scenario?

**Comment by pbros** [comment]
Unfortunately not. I have some hard dependencies on a NuGet package that won't be upgraded to .NET Core 3 for a few months.

Do you expect to have to do many changes to move to .NET Core 3.0?

**Comment by skoruba** [comment]
I will explore .NET Core 3.0 next week, so I send some details. But thanks for feedback, I will consider how to manage this update.

**Comment by imranahmedkhan** [comment]
Any update on when you'd upgrade to .NET Core 3.0 ?

**Comment by skoruba** [comment]
I am working on it, but I have another PRs which are necessary to review and merge - after that I will upgrade to .Net Core 3.0 😊👍🏼 Thanks

**Comment by pbros** [comment]
> Unfortunately not. I have some hard dependencies on a NuGet package that won't be upgraded to .NET Core 3 for a few months.
> 
> Do you expect to have to do many changes to move to .NET Core 3.0?

Looks like the packages I need will be upgraded to .NET Core soon, so it should not be blocking after all.

**Comment by imranahmedkhan** [comment]
Hey @skoruba , any update on this ?

**Comment by skoruba** [comment]
Not yet. :) Did you try update this solution?

**Comment by maldworth** [comment]
Just like to add that we'd also like a -beta8 package which targets the last IdentityServer4 -> 2.5.3, before upgrading to core 3.0.

Our ability to upgrade to core 3.0 is still a few months out.

**Comment by skoruba** [comment]
Here is updated version to .NET Core 3.0 - #390 
Please, you can try it.
Thanks.

**Comment by maldworth** [comment]
at this point, it might just make sense to skip 3.0 and go to 3.1 (which is LTS).  You'd just need to wait for Ids4 to release their preview branch: https://www.nuget.org/packages/IdentityServer4/3.1.0-preview.1.4

**Comment by skoruba** [comment]
@maldworth - thanks 👍

**Comment by skoruba** [comment]
https://www.nuget.org/packages/IdentityServer4/ - new release of IS4 is available, I will update to .Net Core 3.1 👍🏼😊

**Comment by MaxThom** [comment]
Hi,
thank you for your great AdminUI. We were wondering if you will provide a guide to upgrade AdminUI from core 2.2 to 3.1 ?

**Comment by skoruba** [comment]
Hey, for sure - check dev branch. The final version is almost prepared. I am polishing docker support. 👍🏼

**Comment by skoruba** [comment]
I am closing this issue, it was released in master branch.
