### ISSUE TITLE
How to login in AdminUI

### ISSUE THREAD

**Issue by cehui0303** [skoruba/IdentityServer4.Admin#366]
I Have Seed the data by your readme, is there no user account? I Register an account , but when i open the admin website,it show that 'http://localhost:9000/Account/AccessDenied?ReturnUrl=%2F'  Access Denied!
    I Can't login in the admin ,so i can't set anything.

**Comment by skoruba** [comment]
Here is default admin user account:
https://github.com/skoruba/IdentityServer4.Admin/blob/master/src/Skoruba.IdentityServer4.Admin/Configuration/Identity/Users.cs
Thanks

**Comment by cehui0303** [comment]
thanks

**Comment by skoruba** [comment]
May I close it? Thx

**Comment by cehui0303** [comment]
OK &nbsp;close it



发自我的iPhone


------------------ Original ------------------
