### ISSUE TITLE
Add tenant manangement Or Other Management in API

### ISSUE THREAD

**Issue by mayankgaur** [skoruba/IdentityServer4.Admin#369]
I want to Add Some more APIs to Admin Panel, API can I add that.
For Example I have Application Management and Tenant management in API and those are having different db Context can I do that?

**Comment by mayankgaur** [comment]
Hi I want to know one more thing that why you have added AddIdentity in AdminAPI
![image](https://user-images.githubusercontent.com/5146368/66255403-b5a84c00-e7a0-11e9-93db-d922ad0f56da.png)

**Comment by skoruba** [comment]
You can absolutely extend the API endpoints. I’ve added Identity middleware because it is necessary to have available all of dependencies for Identity.

**Comment by mayankgaur** [comment]
@skoruba I have inhereted MyDBContext(Having my POCO Classes) in IAdminConfiguration like below. 
![image](https://user-images.githubusercontent.com/5146368/67358192-3d51d100-f57d-11e9-86f6-5c2565948a05.png)

And then implemented IdentityServerConfigurationDbContext like below
![image](https://user-images.githubusercontent.com/5146368/67358345-c10bbd80-f57d-11e9-8635-75b825e4aa4f.png)

I have different API Class library in their Startup.cs class I have Resolves services like below
![image](https://user-images.githubusercontent.com/5146368/67358418-eac4e480-f57d-11e9-97e2-71ca428bb509.png)
![image](https://user-images.githubusercontent.com/5146368/67358426-f4e6e300-f57d-11e9-9a5e-bd647b071659.png)

But whenever I am calling my API it gives below error 

![image](https://user-images.githubusercontent.com/5146368/67358451-0f20c100-f57e-11e9-8b3b-500cf772e38c.png)

Do I need to use services.AddIdentity() in each API Project?
