### ISSUE TITLE
isAuthenticated = false all the time

### ISSUE THREAD

**Issue by ganmuru** [skoruba/IdentityServer4.Admin#373]
Hi,

I setup the repo and it is working fine. I added a new client and trying to authenticate the client. The login works fine but after login the AuthenticationType is always NULL and isAuthenticated = false.

What am I missing?

My new client configuration in Startup.cs 

services.AddAuthentication(options =>
			{
				options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
				options.DefaultChallengeScheme = AuthenticationConsts.OidcAuthenticationScheme;
				options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
				options.DefaultForbidScheme = CookieAuthenticationDefaults.AuthenticationScheme;
				options.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
				options.DefaultSignOutScheme = CookieAuthenticationDefaults.AuthenticationScheme;
			})
			.AddCookie(CookieAuthenticationDefaults.AuthenticationScheme,
					options =>
					{
						options.Cookie.Name = AuthenticationConsts.IdentityAdminCookieName;

						options.Cookie.SameSite = SameSiteMode.None;
					})
			.AddOpenIdConnect(AuthenticationConsts.OidcAuthenticationScheme, options =>
			{
				options.Authority = EvolutionConfiguration.IdentityServerBaseUrl;

				options.RequireHttpsMetadata = false;

				options.ClientId = EvolutionConfiguration.ClientId;
				options.ClientSecret = EvolutionConfiguration.ClientSecret;
				options.ResponseType = EvolutionConfiguration.OidcResponseType;

				options.Scope.Clear();
				foreach (var scope in AuthenticationConsts.Scopes)
				{
					options.Scope.Add(scope);
				}

				options.ClaimActions.MapJsonKey(AuthenticationConsts.RoleClaim, AuthenticationConsts.RoleClaim, AuthenticationConsts.RoleClaim);
				
				options.SaveTokens = true;

				options.GetClaimsFromUserInfoEndpoint = true;

				options.TokenValidationParameters = new TokenValidationParameters
				{
					NameClaimType = "name",
					RoleClaimType = "role",
				};
			});`

**Comment by skoruba** [comment]
Please check list of samples of clients here:
https://github.com/IdentityServer/IdentityServer4/tree/master/samples/Clients

Please check log for more details about this issue. 🙂

**Comment by skoruba** [comment]
I am closing, feel free reopen
