### ISSUE TITLE
Example client

### ISSUE THREAD

**Issue by IwanSumpena** [skoruba/IdentityServer4.Admin#375]
how to make an example of a client that can be connected

**Comment by skoruba** [comment]
Please check these samples of clients:
https://github.com/IdentityServer/IdentityServer4/tree/master/samples/Clients

In admin UI you can in clients section - add new clients. You can use template for client according to application type (spa, mobile etc.) 🙂

**Comment by IwanSumpena** [comment]
okay thanks for the response

My newbee I tried to make a client console with a configuration like this but i get response invalid scope .is there anything lacking in the configuration
![clientConsole](https://user-images.githubusercontent.com/29264028/66728478-73050480-ee6f-11e9-8825-21ca83a170ae.PNG)

![name](https://user-images.githubusercontent.com/29264028/66728493-81ebb700-ee6f-11e9-968a-e0d20c6fd3ce.PNG)

[basic.pdf](https://github.com/skoruba/IdentityServer4.Admin/files/3722836/basic.pdf)

**Comment by yildirims** [comment]
Hi @IwanSumpena ,
Have you ever tried to add "api1" to AllowedScoped section in exampleClient configuration.


![api1](https://user-images.githubusercontent.com/42366798/66833202-0ddf0b00-ef64-11e9-893c-7585f8e26360.png)

**Comment by IwanSumpena** [comment]
@yildirims  yes I have added "api1" to the scope
and i modified clientID and secret
i get log error 

![image](https://user-images.githubusercontent.com/29264028/67177397-8debf180-f3f8-11e9-8a24-c6cfb4c1a4c7.png)
