### ISSUE TITLE
LoginConfiguration.ResolutionPolicy and Register new user flow

### ISSUE THREAD

**Issue by b0** [skoruba/IdentityServer4.Admin#377]
Hi @skoruba and @xmichaelx

When setting ResolutionPolicy to "Email" _Login view_ is changed to ask for _Email_ instead of Username and that is all great and expected. 
I was reviewing https://github.com/skoruba/IdentityServer4.Admin/pull/152 which introduced relevant configuration feature and changed how _Login view_ is shown. 

I am interested in _Register view_ and is it expected to still have _Username field_ on that view even ResolutionPolicy is set on "Email"?  
It seams to me that **Username field should be hidden**  (like on _Login view_) and instead only Email should be visible on _Register view_ when ResolutionPolicy is set to "Email". Of course, Username should be populated with Email on the backend side...  

Does this have sense for you or there are some other requirements for this current kind of behavior?

Thank you

**Comment by skoruba** [comment]
Hi @b0 - you are right, in registration form - this is missing, we need add this logic here as well. Thanks for your point.
Are you interested in sending PR for this issue? 😊

**Comment by b0** [comment]
Sure, what kind of solution would you have in mind?

Currently, because of [Required] attribute on UserName property on RegisterViewModel.cs which can't be set dynamically I would propose adding one more view RegisterWithoutUsername.html, and ViewModel RegisterWithoutUserNameViewModel.cs and returning specific one from AccountController regarding of ResolutionPolicy  value.

Do you have some other solution in mind or do you find this approach ok?
