### ISSUE TITLE
API methods for creating entities doesn't return Id of newly created entity

### ISSUE THREAD

**Issue by b0** [skoruba/IdentityServer4.Admin#382]
When calling API for adding Users/Roles, controller returns 200(ok) without any data, but should return 201(created) with at least Id of new entity.

I have created PR that resolves these issue. #381

**Comment by skoruba** [comment]
Thanks @b0 for your great work on this issue.

**Comment by b0** [comment]
Thank you. I hope to contribute more... 
BR
