### ISSUE TITLE
How to configure deploy to IIS local pc

### ISSUE THREAD

**Issue by IwanSumpena** [skoruba/IdentityServer4.Admin#385]
![image](https://user-images.githubusercontent.com/29264028/67838168-4580b200-fb23-11e9-932c-47d40be5f6f5.png)

I don't know what configuration is lacking.

**Comment by skoruba** [comment]
I can see that you have only one site with port 5008, did you change ports and another configuration? By default it is port 5000 for STS.
Thanks!

**Comment by IwanSumpena** [comment]
sorry I forgot to change the permissions in the application pool. Issue solved
