### ISSUE TITLE
how to change to MySql database

### ISSUE THREAD

**Issue by SinoMiles** [skoruba/IdentityServer4.Admin#387]
how to change to MySql database

**Comment by skoruba** [comment]
Please, check this guide: https://github.com/skoruba/IdentityServer4.Admin/blob/master/docs/EFMigration.md#mysql-and-mariadb

**Comment by skoruba** [comment]
Does it work for you?

**Comment by SinoMiles** [comment]
@skoruba Thanks.

**Comment by daconglee** [comment]
https://github.com/skoruba/IdentityServer4.Admin/blob/master/docs/EFMigration.md#mysql-and-mariadb
404
