### ISSUE TITLE
IdentityServer.LdapExtension

### ISSUE THREAD

**Issue by murattdogan** [skoruba/IdentityServer4.Admin#388]
ldap authentication  IdentityServer.LdapExtension

**Comment by murattdogan** [comment]
https://github.com/Nordes/IdentityServer4.LdapExtension 
If we integrate this project in Github to your project, auth is provided with Ldap or Open Ldap. And how do I add it to your project?
Where should I add the following codes in your project.
// ... Code ...
services.addıdentityserv is ()
     .adddevelopersigningcredential ()
     //. Addsigningcredential (...)
     .addınmemoryıdentityresources (config.getıdentityresources ())
     .addınmemoryapiresources (config.getapiresources ())
     .addınmemoryclients (config.getclients ())
     .AddLdapUsers <OpenLdapAppUser> (Configuration.GetSection ("MyConfigurationSection"), UserStore.InMemory);
// ... Code ...

**Comment by mandrepont** [comment]
I am confused as to what you are asking, this project is heavily coupled with ASP.NET Core Identity so sadly it is not so easy to just drop another user store in as some of the pages might be broken. (Ex: Users and Roles)

However, to answer your question, it seems you would want to put that code in the STS project in Startup.cs.

**Comment by skoruba** [comment]
I agree with @mandrepont

**Comment by skoruba** [comment]
I do not plan to implement this library for now. Thanks for tip.
