### ISSUE TITLE
UI design

### ISSUE THREAD

**Issue by erossini** [skoruba/IdentityServer4.Admin#393]
I should change the design of the UI to align it to other applications. What is the best practice for that?

**Comment by skoruba** [comment]
This project uses bootstrap4, so you can use styles from there and rewrite original classes with your custom implementation. :-) There are some gulp commands which helps you with compiling sass files to the css files. Please check folder Styles and everything else is bootstrap4. Give me please some feedback. Thanks

**Comment by skoruba** [comment]
I am closing this issue, feel free reopen.
