### ISSUE TITLE
Build  Error : MSB3086	

### ISSUE THREAD

**Issue by zengxinle** [skoruba/IdentityServer4.Admin#396]
错误	MSB3086	任务未能使用 SdkToolsPath“”或注册表项“HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.7.2\WinSDK-NetFx40Tools-x86”找到“al.exe”。请确保已设置 SdkToolsPath，在 SdkToolsPath 之下的相应处理器特定位置存在该工具，并且已安装 Microsoft Windows SDK	Skoruba.IdentityServer4.Admin	C:\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	3639

**Comment by skoruba** [comment]
Check this please: https://stackoverflow.com/questions/32602414/error-could-not-find-al-exe-using-sdktoolspath

**Comment by zengxinle** [comment]
After  I  install .net 4.7.2,   so  it's OK.
