### ISSUE TITLE
AuditLog not recorded in case of role added to user

### ISSUE THREAD

**Issue by aiscrim** [skoruba/IdentityServer4.Admin#397]
First of all thanks a lot for adding the audit logs, that's a great new feature!

I just noticed this small problem: when I add a role to a user, it does not get recorded in the Audit Log. That's because the LogEventAsync is called after the method CreateUserRoleAsync exits in case of success in this line:

https://github.com/skoruba/IdentityServer4.Admin/blob/e02dcaa31d41ab2829821b3cd665762f653df9f3/src/Skoruba.IdentityServer4.Admin.BusinessLogic.Identity/Services/IdentityService.cs#L239

**Comment by skoruba** [comment]
Thanks @aiscrim - great catch, I will fix it. 👍
