### ISSUE TITLE
Compiler Warning CS0618 usage of IStringLocalizer.WithCulture

### ISSUE THREAD

**Issue by bravecobra** [skoruba/IdentityServer4.Admin#398]
The current dev branch outputs warning regarding the deprecated usage of WithCulture as documented here: <https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.localization.istringlocalizer.withculture?view=dotnet-plat-ext-3.0>

This warning popped up due to the upgrade to .NET Core 3.0.

In [this StackOverflow article](https://stackoverflow.com/questions/58316533/net-core-3-istringlocalizer-withculturecultureinfo-is-obsolete) is a possible implementation on remedying the issue.

Personally I feel code is to be at least compiler warning free.

**Comment by skoruba** [comment]
Thanks, I will fix it. 👍🏼

**Comment by skoruba** [comment]
I am closing this issue, it was released in master branch.
