### ISSUE TITLE
ProfileService

### ISSUE THREAD

**Issue by ekjuanrejon** [skoruba/IdentityServer4.Admin#404]
How to add a custom ProfileService to STS?

**Comment by skoruba** [comment]
Here: https://github.com/skoruba/IdentityServer4.Admin/blob/master/src/Skoruba.IdentityServer4.STS.Identity/Helpers/StartupHelpers.cs#L243
You can add extension method .AddProfileService<>()

**Comment by ekjuanrejon** [comment]
How to do that if using the nupkgs?
