### ISSUE TITLE
Template generation needs updating for AdminAuditLogDbContext 

### ISSUE THREAD

**Issue by bravecobra** [skoruba/IdentityServer4.Admin#407]
During the template generation we're missing the generation of the `AdminAuditLogDbContext` at  https://github.com/skoruba/IdentityServer4.Admin/blob/dev/templates/1-template-prepare-content.ps1#L50

**Comment by skoruba** [comment]
Thanks @bravecobra I will upgrade these scripts. 👍🏼

**Comment by skoruba** [comment]
I am closing this issue, it was released in master branch.
