### ISSUE TITLE
Adding support for multiple DbProviders

### ISSUE THREAD

**Issue by bravecobra** [skoruba/IdentityServer4.Admin#408]
I noticed lots of issues being reports regarded missing database migrations. 

In EF Core it is possible add migrations for multiple DbProviders: <https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers?tabs=dotnet-core-cli>

So instead/on top of having the end-user having to generate the migrations for him/herself, we can provide those migrations already and allow for choosing the correct DbProvider through configuration. This would also allow for upgrading existing docker containers. 
We should also allow the end-user to provide his/her own set of migrations, should they choose to do so. There might a couple of rogue migrations in existence with custom changes. All that through configuration of course.

**Comment by skoruba** [comment]
I am glad that you suggest this idea, because I am working on this locally currently. I will add the ef migrations into source control for multiple db providers, because it will help for a lot of use cases.
It will be possible to switch among db providers from appsettings.json.

**Comment by maxrev17** [comment]
As a newbie to this repo I've been working through getting this to run in docker and have stumbled with the migrations as my machine is bare and I'm relying on docker for .net etc. This would be an awesome change to speed up getting it up and running out of the box :).

**Comment by skoruba** [comment]
I am closing this issue, it was released in master branch.
