### ISSUE TITLE
Add Shared project among Admin UI, Api and STS

### ISSUE THREAD

**Issue by skoruba** [skoruba/IdentityServer4.Admin#413]

**Comment by jwilliamsnephos** [comment]
Do you have a branch you have started on this, or have figured out the namespace and references?

The particular "shared part" I'm the most interested in right now is e-mail capabilities from the Admin (currently exists in STS).  Which currently has two dependencies...  Sendgrid, and Identity.UI for IEmailSender interface.

How did you want to handle the Identity.UI.. I was assuming it wouldn't be "desired" to make that a dependency in the admin based on how I was seeing the way you structured the STS vs Admin project.

**Comment by skoruba** [comment]
Done in master.
