### ISSUE TITLE
How to solve logging for multiple db providers

### ISSUE THREAD

**Issue by skoruba** [skoruba/IdentityServer4.Admin#417]
I have to figure out how to use logging into database via multiple db providers.
Currently it is used Serilog - MsSql Sink, but I cannot found any official version of db Sinks for MySql and PostgreSql.

Any idea? 😊

**Comment by fatalistt** [comment]
Hi!
What do you mean "official version"? From Serilog or from Microsoft/PostgreSQL/Oracle?
PostgreSQL - [Serilog.Sinks.PostgreSQL](https://github.com/b00ted/serilog-sinks-postgresql) (from [Serilog Wiki](https://github.com/serilog/serilog/wiki/Provided-Sinks))
Unfortunately, they're not mentioning MySql in their wiki, but there is package [Serilog.Sinks.MySql](https://www.nuget.org/packages/Serilog.Sinks.MySQL).

**Comment by skoruba** [comment]
I meant that mssql sink is provided from official Serilog repository, but these sinks for mysql and postgresql unfortunately not. I will test these package as well. 🙂Thanks
@TomasHubelbauer - what do you think?

**Comment by bravecobra** [comment]
I might have mentioned this before but I don't believe in putting logs in a database in the first place.

**Comment by skoruba** [comment]
Agree, I am closing this. Thx
