### ISSUE TITLE
suggest Guid instead of String

### ISSUE THREAD

**Issue by Varorbc** [skoruba/IdentityServer4.Admin#428]
https://github.com/skoruba/IdentityServer4.Admin/blob/2ab6bc0cf6f9346c997900e3761b96a4f7ceaf86/src/Skoruba.IdentityServer4.Admin.EntityFramework.Shared/DbContexts/AdminIdentityDbContext.cs#L8

**Comment by skoruba** [comment]
Why do you suggest guid? In database is guid generated with string as well.

**Comment by Varorbc** [comment]
Because the guid type supports self growth

**Comment by skoruba** [comment]
I prefer the default value, which is string, you can switch to guid in your fork. 🙂👍🏼

**Comment by Varorbc** [comment]
In addition, guid supports orderly numbering, which string cannot do

**Comment by skoruba** [comment]
Thanks for tip, currently is not my top priority, which you understand for sure 🙂 I had int like a primary key, but community asked for default string which is current state. 👍🏼

**Comment by Varorbc** [comment]
If you agree with my plan, I will open pr

**Comment by skoruba** [comment]
Maybe in next release, because I need finalize this release where I want to keep string for now. Thanks @Varorbc

**Comment by Varorbc** [comment]
When will this version be released

**Comment by skoruba** [comment]
I’d like release new version this month.

**Comment by skoruba** [comment]
I am closing this issue. I want to keep string as primary key for now. Thanks
