### ISSUE TITLE
¿When you release version 1.0.0-beta8?

### ISSUE THREAD

**Issue by willisga** [skoruba/IdentityServer4.Admin#431]
Hello @skoruba 

¿When you release version 1.0.0-beta8?

I'm sorry for my English, it's not very good.

They added very interesting features that I plan to use in a business project.

Thank you for this project, it is very complete and stable for productive environments.

Note: https://github.com/skoruba/IdentityServer4.Admin/issues/125

**Comment by skoruba** [comment]
Hello, I hope this month, according to my free time. 😊

**Comment by willisga** [comment]
Thanks you
