### ISSUE TITLE
Add the option to log to the console

### ISSUE THREAD

**Issue by bravecobra** [skoruba/IdentityServer4.Admin#435]
Add the sink to let Serilog log to the console: `Serilog.Sinks.Console`. This is especially useful in environments like Kubernetes where you want to do logshipping/distributed logging. It can be off by default, although that would not be my preference. 

The recently added logging to the DB is definitely not my preferred way to keep logs. You lose the option to do structured logging as well. I would vote to make this optional as well. I want to be able to do log-shipping to off-site services like Seq/Cloudwatch/Datadog. Currently there is no way to scrape those logs, except from file, but that requires write access to the file-system which in a Docker environment isn't desirable either.
We also need to revisit the current way of logging to enable structured logging so that services like seq and cloudwatch can do structured queries on certain properties. Adding distributed tracing with OpenTracing/Jaeger is certainly another thing we need to take a look at.

**Comment by skoruba** [comment]
For sure, we can add logging into console as well. Which other logging packages do you suggest by default? It is necessary to add specific packages into solution.  
Thanks

**Comment by bravecobra** [comment]
I wouldn't want to add dependencies that are opinionated and stick to the basics ones. We don't want to impose any preference but leave open the option to add more by just referencing the sink required and changing the configuration. Actually, I'd leave the console to be the only one enabled. Any other option as logging is a very opinionated topic. As mentioned before even file logging might not be desirable (especially in docker env's ).
Looking at the [Provided-Sinks](https://github.com/serilog/serilog/wiki/Provided-Sinks]) of Serilog, I'd go with just

- [Serilog.Sinks.Console](https://github.com/serilog/serilog-sinks-console) (enabled and configured by default)
- [Serilog.Sinks.Debug](https://github.com/serilog/serilog-sinks-debug) (enabled in Development env only for VS debug reasons, in `appsettings.Development.json`)
- [Serilog.Sinks.Async](https://github.com/serilog/serilog-sinks-async) (disabled, but referenced)
- [Serilog.Sinks.File](https://github.com/serilog/serilog-sinks-file) (disabled, but referenced and sample configuration)
- [Serilog.Sinks.MSSqlServer](https://github.com/serilog/serilog-sinks-mssqlserver) (disabled, but referenced and sample configuration) as we now have a way of logging to the database for those who want it. There are far more powerful tools available to parse and search logs than the one we have in this code. Take a look at loggly, seq, cloudwatch, datadog, etc

People can then choose/configure their own by adding the reference and updating their `appsettings.json`.

We should choose the do logging earlier as well as specified in Serilog's example to catch EF migration errors, which are not logged to sql at the moment (as it crashes beforehand): https://github.com/serilog/serilog-docker/blob/master/web-sample/src/Program.cs, which should be a straight forward change.

**Comment by bravecobra** [comment]
We should make distributed tracing like OpenTracing/Jaeger a separate issue. Same goes for structured logging, as that would involve changing the log statements everywhere where applicable.

**Comment by skoruba** [comment]
I definitely agree with you, I will do it according to your suggestion. 👍🏼

**Comment by skoruba** [comment]
According to @bravecobra PR added into dev.
