### ISSUE TITLE
How can I login?

### ISSUE THREAD

**Issue by edmundhuang** [skoruba/IdentityServer4.Admin#44]
It seems there is no default admin/admin user or something else like for login page.
Follow the step,
1. add-migrations
2. datebase update
3. uncomment seeddata

Then I start IDS4 at localhost:5000, and IDS4 admin at localhost:9000.
Where I open http://localhost:9000, the website redirect me to localhost:5000 login page.
But I don't have a username and password for login.
User table is empty when I check it in SQL Server Management Studio.
Is it something I have done wrong?

**Comment by skoruba** [comment]
Good point. 👍 

I will add some default admin user into IDS4 with Asp.Net Identity.

Now you can run project `Skoruba.IdentityServer4` - that contains inmemory admin user - bob/password - then you can create some new users/roles and switch back to `Skoruba.IdentityServer4.AspNetIdentity`.

**Comment by edmundhuang** [comment]
The key problem is: there is no default user interface for create new users/roles in IDS4.

**Comment by skoruba** [comment]
I've added to the `dev` branch updated seed data.
Please, take a look - [here](https://github.com/skoruba/IdentityServer4.Admin/blob/dev/src/Skoruba.IdentityServer4.Admin/Helpers/DbMigrationHelpers.cs#L32-L76).

**Comment by skoruba** [comment]
#45

**Comment by MaryadaPurshottam** [comment]
When i login using the existing username and password stored wtihin Identity.Users.cs, it keep redirecting me back to the login page. I download it and ran the migrations as well as the seeddata.  this is the returnurl

"/connect/authorize/callback?client_id=skoruba_identity_admin&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fsignin-oidc&response_type=id_token&scope=openid%20profile%20email%20roles&response_mode=form_post&nonce=636862813423997478.NDA0MmRkYzQtODdiMC00NWYzLTk0MGUtZTI5NDkzNjMyOTcyZjVhNWI2OWEtYjc5OC00OGJhLTk0OWYtMzY4MzE3MmE1Mjg2&state=CfDJ8DaiEcgA_YNIijFvat1kQrzHyDUpK0JXm-wTSG4MyrmgBP_rqyL6UpKmJ_vnu0boipJgILPRnS6hMaCWxnc9DR2EPtcJLgdNPNdgyWQRwXDS6CgCiMGJmJb74wC2-rKLzf-ny7_IwXdl-FTccTqkNQLpj--6G8NPAXO8UOYLbflkJrkNkH0Du4dDwKHZJmIPzjWa402F1ecyszJ1T4MqFyKhP0ZtWeSwlo6pG03IjVFWBOzp4JDaXKl7ieuMllZQtn56I4iPgnLhxviE6JiJ2Mk8vqVYQAbWZfB5qE82LWCWi8Bde3P8WonMcQ-2w2315g&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=5.3.0.0"
