### ISSUE TITLE
Unable to configure IdentityServer without modifying private methods 

### ISSUE THREAD

**Issue by b0** [skoruba/IdentityServer4.Admin#445]
Hi @skoruba ,

currently it's not possible to configure `IdentityServer` from STS project without going into `StartupHelpers` and modifying private methods. 

I have made PR that fixes that issue by exposing `IIdentityServerBuilder` back to `ConfigureServices`
PR #444 

Thank you

**Comment by skoruba** [comment]
Hi @b0 
thanks, it is merged. 👍

**Comment by b0** [comment]
Thank you @skoruba
