### ISSUE TITLE
Which token would I use ?

### ISSUE THREAD

**Issue by alvarovalle** [skoruba/IdentityServer4.Admin#449]
Hi

I am experiencing micro-service scenario, and I would like to know what is the propper use of Jwt token when diving in to cross micro-service communication. like the picture below

![image](https://user-images.githubusercontent.com/5870264/71643992-ef092e80-2c9f-11ea-8c59-2ebb2369d995.png)

My user got a token, but he only can talk to microservice A.
In the other hand, microservice A are allowed to talk to microservice B and microservice B allowed to talk to microservice C.

My doubt:

What is the JWT that I have to use to access B and C in that situation? the same the user got to access A? 

or my user only need to access the microservice A, and from that point every body who access microservice A are automaticaly allowed to access B and hence C?

regards

**Comment by skoruba** [comment]
Please, look at this docs: http://docs.identityserver.io/en/latest/topics/extension_grants.html
I think this is exactly what you want 🙂

**Comment by alvarovalle** [comment]
Thank you very much

**Comment by skoruba** [comment]
I am closing this issue, feel free reopen.
