### ISSUE TITLE
dev:  Authorize problem in Api

### ISSUE THREAD

**Issue by saeedrahimi** [skoruba/IdentityServer4.Admin#455]
Hi, Thank you for this great project.
I've just faced a problem with Api authorization in `dev` branch.

Steps to reproduce:
1. clone `dev` branch of repository.
2. run Admin, Api, Sts
3. navigate to swagger in > `http://localhost:5001/swagger/index.html`
4. authenticate with swagger ui successfully (token is available).
5. execute an api.
6. return 302 with `http://localhost:5001/Account/Login?redirect_url....`

**Comment by skoruba** [comment]
Hi @saeedrahimi 
thanks for reporting this, after your PR, this still doesn't work for me.
I need to figure out, where it is issue.
Thanks!

**Comment by skoruba** [comment]
@saeedrahimi - Please, check latest dev branch, it should work. 👍 Thanks for reporting this, I didn't notice this issue.

**Comment by saeedrahimi** [comment]
Works like a charm 👍
