### ISSUE TITLE
admin API 404 not found

### ISSUE THREAD

**Issue by gnsilence** [skoruba/IdentityServer4.Admin#464]
I created the project with the template 1.0rc1.
I have changed the DefaultAuthenticateScheme and DefaultChallengeScheme.

 services.AddAuthentication(options =>
                {
                    options.DefaultAuthenticateScheme = IdentityServerAuthenticationDefaults.AuthenticationScheme;
                    options.DefaultChallengeScheme = IdentityServerAuthenticationDefaults.AuthenticationScheme;
                })

But all the API interfaces are still 404.

just like:
Request URL: http://localhost:5001/api/Roles?page=1&pageSize=10
Request Method: GET
Status Code: 302 Found
Remote Address: [::1]:5001
Referrer Policy: no-referrer-when-downgrade

Is there anything else I need to change?

**Comment by gnsilence** [comment]
I have solved the problem , because EntityFrameworkStores were added last.

**Comment by skoruba** [comment]
Please use rc1-update1 - we fixed it. 🙂 thanks

**Comment by skoruba** [comment]
Thanks for reporting this
