### ISSUE TITLE
The docker-compose file not meet the network topology.

### ISSUE THREAD

**Issue by danielmeza** [skoruba/IdentityServer4.Admin#474]
The docker compose define port 5000 for the Admin Api but the admin api is configure to use 5001 port, and also put the 80 port to the STS site, it should use 5001 for Api and 5000 for STS

**Comment by skoruba** [comment]
I have checked the docker-compose and everything looks good. What do you think with network topology? Thanks.

**Comment by danielmeza** [comment]
When we run the solution with iis express the site has the following addresses:

- localhost:5000 for STS
- localhost:9000 for admin
- localhost:5001 for admin api

But in docker has:

- localhost:5000 for admin api
- localhost:80 for STS
- localhost:9000 for admin 

It should keep the same address to simplify configuration and maintenance?

**Comment by skoruba** [comment]
This was rewritten - please check master branch. Thank you.
