### ISSUE TITLE
API error - /api/Users/{id}/RoleClaims

### ISSUE THREAD

**Issue by anthonynewlineinfo** [skoruba/IdentityServer4.Admin#488]
Hi,

![image](https://user-images.githubusercontent.com/28350118/73909870-bcbca380-48d3-11ea-8d04-c6dfd522bb10.png)

Requested to fetch Role claims using user Id, it showing mapper error
![image](https://user-images.githubusercontent.com/28350118/73909980-02796c00-48d4-11ea-8b77-742df10311ef.png)

**Comment by skoruba** [comment]
Hi,
Thanks for reporting this issue, I will check it.

**Comment by skoruba** [comment]
Do you use the latest version of Admin UI?

**Comment by anthonynewlineinfo** [comment]
I'm using - New release 1.0.0-rc1

**Comment by skoruba** [comment]
Thanks, let me check it

**Comment by CoreDX9** [comment]
@skoruba @anthonynewlineinfo If you use AutoMapper with DI like ```services.AddAutoMapper()```, mapper error will heppen. I have encountered this error and use custom servive code solved this problem.
[sample code](https://github.com/CoreDX9/IdentityServerDemo)

**Comment by ToanHT** [comment]
Hi @anthonynewlineinfo,
You can fix it temporarily by adding code below in IdentityMapperProfile.cs
  CreateMap<TRoleClaimsDto, RoleClaimsApiDto<TRoleDtoKey>>(MemberList.Source);
  CreateMap<TRoleClaimDto, RoleClaimApiDto<TRoleDtoKey>>(MemberList.Destination);
  CreateMap<TRoleClaimsDto, RoleClaimApiDto<TRoleDtoKey>>(MemberList.Destination);
 Thanks!

**Comment by skoruba** [comment]
Thanks for reminder for this, I will add it into next release.
