### ISSUE TITLE
Client admin error, "RedirectUris" will be lost on save client.

### ISSUE THREAD

**Issue by CoreDX9** [skoruba/IdentityServer4.Admin#490]
on get client data

![01](https://user-images.githubusercontent.com/26616055/74102366-e698f300-4b7d-11ea-8a08-6fad50b301d8.png)

web page show nothing

![02](https://user-images.githubusercontent.com/26616055/74102383-03352b00-4b7e-11ea-8d0f-5ea8950c4f14.png)

DevTools Sources
![03](https://user-images.githubusercontent.com/26616055/74102425-5f984a80-4b7e-11ea-8875-6d4311f1862e.png)

on save client
![04](https://user-images.githubusercontent.com/26616055/74102444-72ab1a80-4b7e-11ea-9036-ec80c9e72dc3.png)

and don't have form key "RedirectUris" in FormData.

This may happened on other properties like "RedirectUris" with collection type.

branch : dev
solution: [IdentityServerDemo](https://github.com/CoreDX9/IdentityServerDemo)

**Comment by skoruba** [comment]
Sorry for late response, did you figure out where the issue was? I notices similar issue i  the that taghelpers were not loaded correctly. Any js errrors in console?

**Comment by CoreDX9** [comment]
Sorry. This error occurred because I forgot to include the tag helper in the code. After your reminder, I have fixed the error. thank you for your reply.
