### ISSUE TITLE
String length on password field's is not the same as on Password.RequiredLength

### ISSUE THREAD

**Issue by b0** [skoruba/IdentityServer4.Admin#494]
Hi,

when adding AspNet Identity default password policy is applied that
[reads](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration?view=aspnetcore-3.1):
> By default, Identity requires that passwords contain an uppercase character, lowercase character, a digit, and a non-alphanumeric character. Passwords must be at least six characters long. 

All forms(ViewModels) that contains password filed have this
`        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
`  
As you can see MinimumLength is hardcoded so if you change Identity's default password length to 8 you have to change this line on 5 places, and you need to **know** to change it...

Anyway, I propose we remove this line on this 5 ViewModels completely as we already have server side validation for all other cases(upper char, lower char and so on) and validation errors are returned from sever side.

@skoruba would this PR be fine with you?

Thank you

**Comment by skoruba** [comment]
Hi @b0 - thanks!
