### ISSUE TITLE
How to forward claims from Azure AD through IS4

### ISSUE THREAD

**Issue by brattpurrie** [skoruba/IdentityServer4.Admin#496]
When using IS4 combined with AzureAD, I would like that when a user logs in from a SPA client, he receives the AzureAD email address. Currently, there is an in-between screen that requires the user to insert an email address again. is there a way to map claims from azureAD to IS4?

requested scope: openid profile email

IS4 asking to fill in the email address:
![image](https://user-images.githubusercontent.com/36637783/74444597-64f2df00-4e75-11ea-9705-7829d79a3ae5.png)

IS4 configuration
```
if (externalProviderConfiguration.UseAzureAdProvider)
            {
                authenticationBuilder.AddOpenIdConnect("aad", "Login with Azure AD", options =>
                {
                    options.Authority = externalProviderConfiguration.AzureADAuthority;
                    options.ClientId = externalProviderConfiguration.AzureADClientId;
                    options.CallbackPath = "/signin-oidc";
                });
            }

```

**Comment by tomadj** [comment]
Hello, 

I do like this : 

    
```
var email = info.Principal.FindFirstValue(ClaimTypes.Email) ??
                        info.Principal.FindFirstValue(ClaimTypes.Name);

return View("ExternalLoginConfirmation", new ExternalLoginConfirmationViewModel { Email = 
        email });
```

**Comment by skoruba** [comment]
Thanks @tomadj 👍
