### ISSUE TITLE
Migrations failing

### ISSUE THREAD

**Issue by EricHerlitz** [skoruba/IdentityServer4.Admin#504]
I'm trying to run some migrations but it all fails, my current versions are
MigrationId: 20181023124204_DbInit
ProductVersion: 2.1.4-rtm-31024

```
Updating donet ef tools
Tool 'dotnet-ef' was reinstalled with the latest stable version (version '3.1.0').
Start migrate projects
Generate migration for db provider: SqlServer , for project path -  ...
Migrating context  AdminLogDbContext
Build started...
Build failed.
Migrating context  AdminIdentityDbContext
Build started...
Build failed.
Migrating context  IdentityServerPersistedGrantDbContext
Build started...
Build failed.
Migrating context  IdentityServerConfigurationDbContext
Build started...
Build failed.
Migrating context  AdminAuditLogDbContext
Build started...
Build failed.
```

x

**Comment by skoruba** [comment]
Hi @EricHerlitz 
thanks for reporting this - which version of admin ui do you use?
Did you get some error message?

**Comment by aiscrim** [comment]
Here it's the build that is failing, not the migrations themselves. Can you successfully build and run the project from Visual Studio?

**Comment by EricHerlitz** [comment]
> Hi @EricHerlitz
> thanks for reporting this - which version of admin ui do you use?
> Did you get some detailed error message?

The error was resolved by upgrading SQL Server
