### ISSUE TITLE
change default language problem

### ISSUE THREAD

**Issue by rezafx** [skoruba/IdentityServer4.Admin#512]
i've changed default culture to 'fa' and it didn't work.
how can i change default culture???

**Comment by skoruba** [comment]
I will check it, thanks.

Did you try to setup this via appsettings.json, right?

**Comment by rezafx** [comment]
No,I dont know how it is ? can you give me any example please

**Comment by rezafx** [comment]
I changed :

var options = app.ApplicationServices.GetService<IOptions<RequestLocalizationOptions>>();
app.UseRequestLocalization(options.Value);

to this  :

 var options = app.ApplicationServices.GetService<IOptions<RequestLocalizationOptions>>();
            var cookieProvider = options.Value.RequestCultureProviders.OfType<CookieRequestCultureProvider>().First();

            var urlProvider = options.Value.RequestCultureProviders.OfType<QueryStringRequestCultureProvider>().First();

            cookieProvider.Options.DefaultRequestCulture = new RequestCulture("fa");
            urlProvider.Options.DefaultRequestCulture = new RequestCulture("fa");

            cookieProvider.CookieName = CookieRequestCultureProvider.DefaultCookieName;

            options.Value.RequestCultureProviders.Clear();
            options.Value.RequestCultureProviders.Add(cookieProvider);
            options.Value.RequestCultureProviders.Add(urlProvider);
            app.UseRequestLocalization(options.Value);

in StartupHelper.cs and it worked !

**Comment by skoruba** [comment]
In appsettings.json you can add default language here:
```
"CultureConfiguration": {
    "DefaultCulture": "fa"
  }
```
If you will have any question, let me know.
Thanks
