### ISSUE TITLE
Deploying behind a reverse proxy 

### ISSUE THREAD

**Issue by sheng-jie** [skoruba/IdentityServer4.Admin#513]
I got an issue when I tried to deploy STS.Identity to Nginx. After research I got the same issue  [Deploying behind a reverse proxy](https://github.com/IdentityServer/IdentityServer4/issues/324#issuecomment-392129635).

So it's better to add `IdentityServerBaseUrl` options for STS.Identity project so that developer can specified it when deploying the project under reverse proxy such as Nginx. 

If  agree with that, I can make a PR.

**Comment by skoruba** [comment]
Please, check this PR from @aiscrim  - #510 - Is this PR cover your issue?
Thanks.

**Comment by sheng-jie** [comment]
yes, it is.
