### ISSUE TITLE
PostgreSQL health check failure

### ISSUE THREAD

**Issue by inbarbarkai** [skoruba/IdentityServer4.Admin#514]
Hi,
I've initialized the docker-compose environment with PostgreSQL.
Checking the admin health endpoint, I've seen failure `42P01: relation \"apiresources\" does not exist` on all tables.

This is because PostgreSQL is case sensitive and the table that is created is: `ApiResources`.
Maybe the migration should create the table in lower case?
Maybe the health check is missing `"` around the table name?

**Comment by skoruba** [comment]
Hi @aiscrim - can you help with this please? 😊 thanks

**Comment by inbarbarkai** [comment]
Create PR #515

**Comment by aiscrim** [comment]
It seems that @inbarbarkai solved it faster than me. :)

**Comment by skoruba** [comment]
Thanks guys! 👍

**Comment by inbarbarkai** [comment]
I aim to please 😄.
