### ISSUE TITLE
API and Swagger return 404

### ISSUE THREAD

**Issue by raukomor** [skoruba/IdentityServer4.Admin#519]
I'm trying to access Swagger or access any API endpoint, but the API 404 response for both. I am using the default configuration of the API and other solutions. To acess Swagger i'm trying to use: 

`http://localhost:5001/swagger/` 

but not working. Do I need to do any other configuration to access the API?

This is my appsettings.json of Admin.Api
`{
    "ConnectionStrings": {
        "ConfigurationDbConnection": "Server=localhost; User Id=admin; Database=IdentityServer4Admin; Port=5432; Password=123456; SSL Mode=Prefer; Trust Server Certificate=true",
        "PersistedGrantDbConnection": "Server=localhost; User Id=admin; Database=IdentityServer4Admin; Port=5432; Password=123456; SSL Mode=Prefer; Trust Server Certificate=true",
        "IdentityDbConnection": "Server=localhost; User Id=admin; Database=IdentityServer4Admin; Port=5432; Password=123456; SSL Mode=Prefer; Trust Server Certificate=true",
        "AdminLogDbConnection": "Server=localhost; User Id=admin; Database=IdentityServer4Admin; Port=5432; Password=123456; SSL Mode=Prefer; Trust Server Certificate=true",
        "AdminAuditLogDbConnection": "Server=localhost; User Id=admin; Database=IdentityServer4Admin; Port=5432; Password=123456; SSL Mode=Prefer; Trust Server Certificate=true"
    },
    "AdminApiConfiguration": {
        "ApiName": "Identity Api",
        "ApiVersion": "v1",
        "ApiBaseUrl": "http://localhost:5001",
        "IdentityServerBaseUrl": "http://localhost:5000",
        "OidcSwaggerUIClientId": "AdministratorClientId_api_swaggerui",
        "OidcApiName": "AdministratorClientId_api",
        "AdministrationRole": "Administrator",
        "RequireHttpsMetadata": false,
        "CorsAllowAnyOrigin": true,
        "CorsAllowOrigins": []
    },
    "DatabaseProviderConfiguration": {
        "ProviderType": "PostgreSQL"
    },
    "AuditLoggingConfiguration": {
        "Source": "IdentityServer.Admin.Api",
        "SubjectIdentifierClaim": "sub",
        "SubjectNameClaim": "name",
        "ClientIdClaim": "client_id"
    }
}`

**Comment by daconglee** [comment]
https://localhost:5001/  or http://localhost:5001/

**Comment by raukomor** [comment]
@daconglee http://localhost:5001/, sorry.

**Comment by raukomor** [comment]
I think i'm found the Issue. On appsettings.json the AdminApiConfiguration.ApiBaseUrl by default is "http:localhost:5001", but api use the port 5002. I change the port to 5002 and works. I dont know if this is the right way, but works...

**Comment by skoruba** [comment]
Thanks for reporting back your solution.
