### ISSUE TITLE
Error 404 when launching server

### ISSUE THREAD

**Issue by feanor91** [skoruba/IdentityServer4.Admin#522]
Hello,

Whatever I tried, I face this error message when launching IdentityServer4.admin : 
IOException: IDX20807: Unable to retrieve document from: 'http://localhost:5005/.well-known/openid-configuration'. HttpResponseMessage: 'StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content

server is running on http://localhost:5005/

Could you help?

**Comment by skoruba** [comment]
Did you change the default ports? I think default port for sts is 5000.
Thanks

**Comment by feanor91** [comment]
I try to change it, but it changes nothing so I go back to default port, I think it is a kind of SSL problem, but I'm not able to find it

**Comment by skoruba** [comment]
I am closing this for now, feel free reopen. Thank you.
