### ISSUE TITLE
external login with google and twitter

### ISSUE THREAD

**Issue by jack1232** [skoruba/IdentityServer4.Admin#527]
How to use Google and Twitter to log in?

In the original IdentityServer4, we can easily add the following code to do it:

services.AddAuthentication()
    .AddGoogle(googleOptions => { ... })
    .AddTwitter(twitterOptions => { ... });

Thanks

Jack

**Comment by skoruba** [comment]
Hi @jack1232 
you can add another external providers here:
https://github.com/skoruba/IdentityServer4.Admin/blob/master/src/Skoruba.IdentityServer4.STS.Identity/Helpers/StartupHelpers.cs#L307

Thank you

**Comment by skoruba** [comment]
I am closing this, feel free reopen. Thank you.
