### ISSUE TITLE
Can't send email from Admin and Admin.Api projects

### ISSUE THREAD

**Issue by b0** [skoruba/IdentityServer4.Admin#529]
Hi @skoruba,

as you know, current implementation of mail sending and mail sending configuration is in STS so it's not reusable.

Where would you put configuration and three interface implementations so all is reusable? 
I am not really sure new project just for this is needed, can it be moved to some of already existing ones?

What do you think?

Thank you

**Comment by b0** [comment]
Just to say if not clear, I am willing to implement it. Looking for your input, how and where...

Thank you

**Comment by skoruba** [comment]
Hi @b0 - thanks for opening this issue.
I think it is connected to issue: #413.

My idea:
I would create new project called:
Skoruba.IdentityServer4.Shared

And this project will be for shared things like email service, maybe some shared configuration?

Please, tell me what do you think about it?
Or even we can create new project for email service, but I think one Shared project should be enough. 

Thanks.

**Comment by b0** [comment]
Yup. Definitely connected to #413.  

I agree, new Skoruba.IdentityServer4.Shared project is fine.  
I will create it, move mail sending and configuration there, make appropriate refactoring to STS and make a PR.

Thank you

**Comment by skoruba** [comment]
Thank you, it would be great. 👍🏼

**Comment by skoruba** [comment]
BTW: @b0 - can you send me your contact to my email - I'd like to discuss some details with you, if you agree. :) Thank you.

**Comment by ekjuanrejon** [comment]
Hello, I have been looking that when a user register via the MVC an email get sends but when using the API no email get sends....

**Comment by b0** [comment]
@ekjuanrejon You are correct, that functionality is not implemented in API project. Currently, mail is sent only when user register via MVC application(STS, GUI) .

Best regards

**Comment by b0** [comment]
As of #671, mail sending is possible from Admin and API projects so I am closing this issue.

Thanks to everyone involved. 

Best regards
