### ISSUE TITLE
SameSite Cookie Changes Issue

### ISSUE THREAD

**Issue by bsheriff** [skoruba/IdentityServer4.Admin#532]
I have a Single page web application with consists of the following

 1. Angular 8 Front End
 2. .Net Core Web Api Back End
 3. .Net Core Identity Server Authentication Server (Skoruba Admin .NET Core 2.2)

I recently started to see a few warnings in my console which reads - "A cookie associated with a cross-site resource at "" was set without the 'SameSite' attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with 'SameSite=None' and 'Secure'.

So based upon this a did a little bit of research and landed on the following article, which happens to explain everything that is going on in detail.
[Explanation of Cookie Issue][1]

I read the article over several times and think I have a grasp of it, but still I am struggling on one simple aspect of it. There is a few areas where they ask you to add some code to your "Project".  My question is (being still somewhat of a newbie with Identity Server and its inner workings), is what is the "Project" they are referring to. I am not exactly sure where to put the code they provide in order to fix the issue.

 

 1. For me its not so obvious on where exactly to put the provided code.  I have 2 Visual Studio solutions - one representing my authentication server (Identity Server Skoruba) and one for my Web Api.  Which of these solutions' Startup.cs files do I add the code solution?

 2. I am assuming that I have to add the following code somewhere in my STS project
```
services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
            .AddCookie("Cookies", options =>
            {
                options.Cookie.SameSite = SameSiteMode.None;
            });
```
I am just not exactly sure where to add that.  I read a few articles which said that Identity Server, by default, creates a cookie for you automatically after successfully logging in and that I don't need to add anything custom.  What I am thinking is that I may have to update that default cookie to be SameSite=None, just not exactly sure how to go about doing that.  I am afraid that the above code will override any authentication I have.  The only line related to adding authentication in the STS project I see is located in the "ConfigureServices" method:
`services.AddAuthenticationServices<AdminIdentityDbContext, UserIdentity, UserIdentityRole>(HostingEnvironment, rootConfiguration.AdminConfiguration);`

 3. One more thing I did notice is that once the cookies are set they are not being deleted when a logout is performed.

Keep in mind that these issues are only occuring on a MacOS running Google Chrome. If I run my application on a Windows PC, I still see the warnings, but I am able to log out and clear all existing cookies

  [1]: https://www.thinktecture.com/en/identity/samesite/prepare-your-identityserver/

**Comment by TomasHubelbauer** [comment]
I came across the same issue using Puppeteer (Chromium based) on Windows today, so I think it is only a matter of time before this new restriction is rolled out for Windows as well. It was in an unrelated project though, so I can't comment on what it means for this project.

**Comment by skoruba** [comment]
Hi @bsheriff 
Thanks for reporting this, I will check it.

**Comment by bsheriff** [comment]
Hi, thank you for the swift response.  @skoruba any timetable on a fix to this (we are currently using this in a production environment and we have a few users mention this issue).  The fix you will make will go against the current .NET Core 3 codebase?

Thanks again

**Comment by bsheriff** [comment]
Also, I have tried to use the newer version of your software (.NET Core 3) and am having the same issue.  I am unable to login to the Admin Site and am receiving the following error when attempting to login.

<img width="1023" alt="Screen Shot 2020-03-12 at 9 48 52 PM" src="https://user-images.githubusercontent.com/20213332/76582045-94642e00-64ab-11ea-8c22-056a8443b98f.png">

This is a consequence of the issue I mentioned in my original question with Chrome version 80.

**Comment by skoruba** [comment]
@bsheriff - I will check it probable at the weekend and send fix.
Thanks.

**Comment by skoruba** [comment]
I added the fix into dev branch - can you please verify this fix? 
Thanks.

**Comment by bsheriff** [comment]
Excellent,

Thank you so much for your assistance.  I will test over the weekend and let you know.

**Comment by jberg2016** [comment]
@skoruba  I happen to be experiencing the same issues as @bsheriff,

I tried applying your fix to my local branch, however, it did not seem to fix my issue. I am still trying to get a grasp on this issue as well.

It is my understanding that this new update to chrome requires the cookies (at least for chrome browser) to be set to "SameSite=None" and "Secure" in order for it to be read by another domain.

After applying your update I did not see the cookie being set to "secure."

One thing to note, I am running this locally in a non https (non secure) development environment. Assuming the cookies now need to be set to secure does this mean the local environment would have to be run in a secure environment?

Additional help would greatly be appreciated.

**Comment by skoruba** [comment]
Can you please send me some steps, how do you test it this use case?

**Comment by jberg2016** [comment]
OS : Windows Parallels
Browser : Chrome Version 80.0.3987.132 with Chrome feature flag SameSite set as "default"

I am running your latest release and applied your fixes.

Steps:

1. I start up Visual Studio Debug IISExpress running both the Admin and STS Identity projects on their respective ports http://localhost:5000 and http://localhost:9000

2. The Admin application then correctly redirects to the login of the STS Identity app for authentication

3. I enter the correct admin credentials and then I am instantly redirected back to the login page instead of the Admin application.

4. Now if I change the chrome feature flag SameSite setting to "disabled", after relaunching and logging in again as the Admin, I correctly redirected back to the Admin application and I am logged in.

5. I was then able to view the state of the cookies from the dev tools. I am also seeing the same warning messages as @bryan in my console.

Is this information helpful? If there is anything other information you would like, let me know.

Thanks again

**Comment by skoruba** [comment]
Thanks, let me check it.

**Comment by bsheriff** [comment]
@skoruba I am working on a windows machine and am able to login successfully to the Admin application and to my custom SPA application using your STS Server.  The only thing that worries me a bit is that I still notice that I am still receiving the following warning:

![image](https://user-images.githubusercontent.com/20213332/76693621-b641ea00-663e-11ea-8193-665359239c69.png)

I was under the assumption that with your changes, this warning would be gone.

I also took a look at the cookies:

![image](https://user-images.githubusercontent.com/20213332/76693642-05881a80-663f-11ea-8cc5-a744ffe73d6e.png)

I also noticed here that the "idserv.session" cookie is not set to "Secure".

Also, I did not see you include in your changes anywhere where it sets the Cookie to be Secure.

**Comment by skoruba** [comment]
This is because we do not have https on dev environment - if you configure https - you will see that cookie is set to "Secure".

**Comment by bsheriff** [comment]
Ok I will give that a try, thank you.  I guess the only issue is with users using a Mac.  I happen to also own a Mac and I am indeed seeing the same issues that @jberg2016 is running into. Windows machines are good.  So there still exists some strange issues with Mac either using parallels or MacOS.  Were you able to reproduce that issue @skoruba?

**Comment by skoruba** [comment]
Can you please clone latest dev branch, verify solution on macOS? I do not have macOS unfortunately.

**Comment by skoruba** [comment]
I updated dev branch with `CookieSecurePolicy to SameAsRequest` - can you please verify this change on your enviornment? thank you.

**Comment by mitirazvan** [comment]
Hi, I had an issue with the "Correlation failed" and all the hints suggested that it was a problem with the cookies. The fix for me was to add in the DisallowsSameSiteNone method a check for "Chrome/8" userAgent. After this, everything worked. 
Thank you for your help!

**Comment by bsheriff** [comment]
Hi @skoruba everything seems to be working just fine, I am able to log into the Admin Site and I am also able to login/logout of my SPA application using your STS Identity Project.  However, I am still seeing the warning on my developer console which reads "A cookie associated with a cross-site resource at <url of sts server> was set without the 'SameSite' attribute.  It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with 'SameSite=None'.

When I go look at the cookies from the STS Server there are 2 that are not set to both 'SameSite=None' and Secure

1.  The .AspNetCore.Antiforgery cookie is set to 'SameSite=Strict' and Secure
2.  The ARRAAffinity cookie does not have a value for 'SameSite' and is not Secure

Is this normal behavior for these 2 cookies? Could this be causing this problem.

On a side note the "idsrv.session" cookie is set to 'SameSite=None' and Secure which is a good thing.

I am just trying to get rid of that warning and I am not sure what is causing that and I have a feeling that it may cause issues for my users.

Please advise
Thank You

**Comment by bsheriff** [comment]
Hi, @skoruba, my SPA client application has a silent-renew.html file which sends over requests in an iframe behind the scenes to the STS Identity Server.  With these new changes implemented I am receiving this error in the console:

"Refused to display 'https://<url of sts server>/home/error?errorId=etc....' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'"

So I was experimenting and added the following code to the Configure method of the Startup.cs file of the STS project:

```
app.UseCsp(opts => opts
              .BlockAllMixedContent()
              .FrameAncestors(s => s.Self())
              .FrameAncestors(s => s.CustomSources(
                  "https://<url of my spa application sending the silent-renew", "http://localhost:4200")
               )
```

And after adding this, I do not see the error in the console anymore.  I just want to make sure that this is the correct solution for this problem and that I am not adding code incorrectly.

Thank You

**Comment by gzinger** [comment]
Hi @skoruba , I understand that this issue is only happening on non-secure (http vs https) setups. Unfortunately, all our Dev and Qa environments are not secure. And now, with this policy change from Chrome, nobody can login to the STS. Setting the SameSite to None is actually creates the problem (not solves it). So, when you say that you fixed it on Dev branch, what exactly did you change to fix it? Can we actually use Strict instead of None? Do we use cookies across sites?

**Comment by skoruba** [comment]
Hi @gzinger - I will switch dev environment to https, because this is probable only valid solution for this issue. Cookie which is marked like `SameSite=None` needs to be `Secure` (in the latest version of Chrome), therefore switching to https will be necesarry - #550

**Comment by skoruba** [comment]
Fixed in master branch.

**Comment by wggley** [comment]
https://github.com/IdentityModel/oidc-client-js/issues/729

"Keep in mind that some browsers started to reject insecure SameSite=None cookies, i.e Chrome version 85"
