### ISSUE TITLE
Add Custom Field in Role

### ISSUE THREAD

**Issue by elavanya** [skoruba/IdentityServer4.Admin#534]
I have added customer field in role 
       `public class UserIdentityRole : IdentityRole
	{
		public bool isPredefined { get; set; }
	}`
        
in GetRoleAsync() Function I did not get isPredefined column and value
How to get the isPredefined column in GetRoleAsync() Function

**Comment by skoruba** [comment]
Hi @elavanya 
Did you create the db migration? 
Do you want to use this new field in form as well - or is it something internal flag?
Thanks

**Comment by elavanya** [comment]
yes i done migration, want to get column name in GetRoleAsync()

**Comment by skoruba** [comment]
Do you use project installed from template or full fork?

**Comment by elavanya** [comment]
full

**Comment by elavanya** [comment]
i have admin. adminApi, adminEntitiyFrameworkShared, STSIdentity

**Comment by skoruba** [comment]
OK, if you have full clone of this project, you can easily add this column into:
`UserIdentityRole` and `RoleDto`.
Then you can add this new field into form - `Role.cshtml`.
You need update method `UpdateRoleAsync` in IdentityRepository - because there is manual mapping of properties. This is by the way place where I need add automatical mapping via Automapper, but for your use case is fine.

**Comment by skoruba** [comment]
Please, check this commit - https://github.com/skoruba/IdentityServer4.Admin/commit/e8185817a4a4a1c05cb7e2280841ff1807063745 - I added automatical mapping via automapper.
In this place is currently manual mapping like this:
https://github.com/skoruba/IdentityServer4.Admin/blob/master/src/Skoruba.IdentityServer4.Admin.EntityFramework.Identity/Repositories/IdentityRepository.cs#L151

**Comment by elavanya** [comment]
Sorry I installed from template
I cant edit UserIdentityRole and RoleDto

**Comment by skoruba** [comment]
OK, for template I have to write some guide and merge issue mapping above. :)

**Comment by elavanya** [comment]
ok

**Comment by skoruba** [comment]
Fixed in master, thanks

**Comment by avitryhard** [comment]
I'm using 1.0.0beta7 template version and I'm having the same problem.
I want create a new table that have foreign key to Roles.
And how can I display this field in Role.cshtml. I mean how to custom RoleDto.
