### ISSUE TITLE
it has some issues by update clients Redirect Uris

### ISSUE THREAD

**Issue by pigwing** [skoruba/IdentityServer4.Admin#54]
dtos have not values

**Comment by pigwing** [comment]
oh i see must selected

**Comment by skoruba** [comment]
@pigwing does it work for you?

**Comment by TomasHubelbauer** [comment]
Can you add screenshot or code snippet? From your description I don't understand where the issue is @pigwing.

**Comment by pigwing** [comment]
yes it work,add completed and must click it ,it will be selected status

**Comment by skoruba** [comment]
@pigwing I know, what you mean. I've recieved same type of the issue. I will consider creating maybe better UI design of the picker. I'll discuss it with @TomasHubelbauer.

Thanks for your report.

**Comment by pigwing** [comment]
@skoruba THX

**Comment by mjisaak** [comment]
Any updates on this issue? If I seed the test data I won't see any redirect URIs for the skoruba_identity_admin client in the UI (but they are present in the database). If I try to add a redirect URI and save that, all redirect URIs for that client gets deleted in the db and I won't be able to use the admin UI anymore (invalid redirect uri).

**Comment by skoruba** [comment]
@mjisaak - if you are trying to add new redirect uri - do you click on the uri in the search result? That was an issue, which @pigwing mentioned.

BTW: Any javascript error in console?

Thanks!

**Comment by skoruba** [comment]
It seems that works correctly - if you have any issue about it - please feel free to reopen.
