### ISSUE TITLE
Localization verbiage issue with RegisterWithoutUsername View

### ISSUE THREAD

**Issue by jberg2016** [skoruba/IdentityServer4.Admin#541]
I noticed when displaying the "return View("RegisterWithoutUsername")" view, localization was not being applied correctly.

I believe this is due to the "RegisterWithoutUsername.en" file missing?

When I added that to the project it fixed the language translation issue on that page.

Just wanted to add this incase anyone else experience similar issues.

Thanks

**Comment by skoruba** [comment]
Great catch! 👍🏼
You can copy all resx files called Register.cshtml and rename then to RegisterWithoutUsername.

Can you send a PR for this?

Thanks

**Comment by skoruba** [comment]
Fixed in master. Thanks👍🏼
