### ISSUE TITLE
Update User Claim

### ISSUE THREAD

**Issue by jack1232** [skoruba/IdentityServer4.Admin#544]
How to update the user claims from Admin API? 

I see that there are the UpdateUserAsync and UpdateRoleAsync interface methods in the Skoruba.IdentityServer4.Admin.BusinessLogic.Identity.Dtos.Identity assembly, but there is no UpdateClaimAsync method. Sometimes, user just want to update a specified claim value rather than to create a new claim. It will be useful to add the UpdateClaimAsync method to Admin API.

Thanks
Jack

**Comment by skoruba** [comment]
Good idea, can you add it this method and send a PR?
Thanks

**Comment by jack1232** [comment]
In my project, I installed the IdentityServer4.Admin following your instruction given in the READ.me file.  Thus, implementing the UpdateClaimAsync method will involve changes in the binary assemblies. Here I simply use a temporary solution by first calling DELETE /api/Users/{id}/Claims to remove old claims and then calling POST /api/Users/Claims to add new claims to database.

**Comment by skoruba** [comment]
Merged in master, thanks 👍🏼
