### ISSUE TITLE
Docker STS port

### ISSUE THREAD

**Issue by jomendoza84** [skoruba/IdentityServer4.Admin#546]
Hi there!

I tried to use a custom port for sts:

> skoruba.identityserver4.sts.identity:
>     image: ${DOCKER_REGISTRY-}skoruba-identityserver4-sts-identity
>     ports:
>       - 9002:80

This url works fine on the browser:

http://127.0.0.1.xip.io:9002/.well-known/openid-configuration

But when the admin tries to do the same request throws this exc:

> IOException: IDX20804: Unable to retrieve document from: 'http://127.0.0.1.xip.io:9002/.well-known/openid-configuration'.

More details:

> System.Net.Http.HttpRequestException: Connection refused
>  ---> System.Net.Sockets.SocketException (111): Connection refused
>    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
>    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)

Maybe this happens because inside a container you can only call the port 80 of the other containers.

Just to confirm I opened a bash console on the admin's container and I did a ping to http://127.0.0.1.xip.io. It worked fine but with this curl I get the same error as the application:

> ```
> curl http://127.0.0.1.xip.io:9002/.well-known/openid-configuration
> curl: (7) Failed to connect to 127.0.0.1.xip.io port 9002: Connection refused
> ```

If I use the container name it works fine because the docker internal dns:

> curl http://skoruba.identityserver4.sts.identity/.well-known/openid-configuration
> {"issuer":"http://skoruba.identityserver4.sts.identity",

But I can't change the setting to "AdminConfiguration__IdentityServerBaseUrl=http://skoruba.identityserver4.sts.identity" because it breaks the urls that are intended for the browser (e.g. /connect/authorize)

Maybe isn't the best solution but having separate settings for internal requests should do the trick.

**Comment by SamLangTen** [comment]
Same problem when I use NGINX to proxy pass admin ui and sts. I set a domain in local hosts file, which means that programs in container can't access this domain.

**Comment by skoruba** [comment]
Hi guys, I will test it this docker stuff later. @bravecobra - any suggestion on this issue?
Thx.

**Comment by bravecobra** [comment]
Seems like the same network topology issue in #402 
For this to work you'll need the internal addresses to be fqdn as well. That's where most configs fail.

**Comment by ahmedrz** [comment]
the problem is that there are two ways to contact the STS project ,
the internal way which the admin and admin api projects use internally to conatct the sts which is the discovery endpoint for example and there is the public one which the urls sent to the browser for redirection 
so to solve this there is two options :
one is to use the host ip address for these endpoints where the container is not contacted directly 
but this is not a good option as the host ip address is dynamic and changing all the time (docker windows )
second is to somehow differentiate between internal and external connection addresses which i think have to be done in the identityserver4 project itself 
i don't know if there is any other way because im having this issue myself and now im handling it by using the host ip address but it is not a good solution

**Comment by zwq000** [comment]
docker 服务提供了内部 DNS 寻址, 支持基于 DNS SSR 的负载均衡, 区分内部 RPC 和 浏览器重定向是一个很好的思路,
现在的问题是需要区分 哪些是 内部 RPC 那些访问需要通过浏览器重定向.

> 问题是，有两种联系STS项目
> 的方法，一种是admin和admin api项目在内部使用的内部方式来连接sts（例如发现端点），还有一种是将URL发送到浏览器的公共途径。重定向，
> 因此有两种解决方案：
> 一种是将这些主机IP地址用于未直接联系容器的这些端点，
> 但这不是一个好选择，因为主机IP地址是动态的并且一直在变化（docker Windows）
> 其次是以某种方式区分内部连接地址和外部连接地址，我认为必须在identityserver4项目本身中完成
> 我不知道是否还有其他方法，因为我自己有这个问题，现在我通过使用主机IP地址来处理它，但这不是一个好的解决方案

The docker service provides internal DNS addressing and supports load balancing based on DNS SSR. It is a good idea to distinguish between internal RPC and browser redirection,
The problem now is to distinguish between internal RPC and browser redirection

**Comment by zwq000** [comment]
https://github.com/skoruba/IdentityServer4.Admin/issues/546#issuecomment-605130181

The docker service provides internal DNS addressing and supports load balancing based on DNS SSR. It is a good idea to distinguish between internal RPC and browser redirection,
The problem now is to distinguish between internal RPC and browser redirection

**Comment by skoruba** [comment]
Please check new docker compose in master. Thanks
