### ISSUE TITLE
Custom styling

### ISSUE THREAD

**Issue by nobba75** [skoruba/IdentityServer4.Admin#547]
Hi,

what would be the easiest way to customize the Admin site according to my preferred coloring scheme etc?

**Comment by ViRuSTriNiTy** [comment]
Hi there,

imho you have two options right now:

a) use custom CSS rules in your own `css` file to override the styles applied by `bundle.css` and `web.css`

or

b) modify the existing `scss` files

To easily customize colors the projects would need to use [Bootstrap Sass Theming](https://getbootstrap.com/docs/4.4/getting-started/theming) which should be easy to integrate as there is already a gulp pipeline established that is required for this job. I've done that already in my own projects but i'm not sure whether this applies that easily here.

So lonG

**Comment by skoruba** [comment]
@ViRuSTriNiTy described details about styles really good. 👍🏼
A PR for improvements around styles is welcome, especially find some way how to easily create new theme - but I used bootstrap, so modification should be easy I hope. :)

**Comment by nobba75** [comment]
Thank you for your answers!
