### ISSUE TITLE
Serilog setup does not include environment specific configuration files

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [skoruba/IdentityServer4.Admin#549]
Hi there,

i would like to add environment specific configuration files like `serilog.Development.json` or `serilog.Staging.json`. Currently only `serilog.json` is added hence environment specific configuration files cannot be used.

I can provide a PR. What do you say? 

So lonG
Daniel

**Comment by skoruba** [comment]
Hi, please check dev branch, I added this.
Thanks

**Comment by ViRuSTriNiTy** [comment]
Hi @skoruba, thx for the fast reply. I cannot find the code that adds this functionality. Would you please provide a link to relevant commit? So lonG

**Comment by skoruba** [comment]
Sorry, I added support for loading configuration from secrets. I am wondering about this one, I tought that this is build in default configuration, did you test it?
Thanks!

**Comment by skoruba** [comment]
I added this: https://github.com/skoruba/IdentityServer4.Admin/commit/76a0181702bafedc03f6004ccb8ad6f5dbae2e45

**Comment by b0** [comment]
Hi @skoruba,

I was thinking the same way as you. Since AddJsonFile magicaly loads appstettings.{environment}.json I was thinking that is true for all files - but it is not.  [configuration](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#default-configuration)

`
            .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
            .AddJsonFile("serilog.json", optional: true, reloadOnChange: true)

            .AddJsonFile($"serilog.{environment}.json", optional: true, reloadOnChange: true)`

Sorry for bad formating. I was have hard time with it 😠

**Comment by ViRuSTriNiTy** [comment]
@b0, @skoruba 

AddJsonFile() does **not** load appstettings.{environment}.json magically. This is a implementation detail in the DefaultBuilder, see https://github.com/dotnet/aspnetcore/blob/master/src/DefaultBuilder/src/WebHost.cs#L170

My PR would add some lines according to the WebHost implementation like

    configApp.AddJsonFile("serilog.json", optional: true, reloadOnChange: true);

    // https://github.com/skoruba/IdentityServer4.Admin/issues/549
    //
    // add configuration files based on hosting environment,
    // adopted from https://github.com/dotnet/aspnetcore/blob/master/src/DefaultBuilder/src/WebHost.cs#L170
    var env = hostContext.HostingEnvironment;

    configApp.AddJsonFile($"serilog.{env.EnvironmentName}.json", optional: true, reloadOnChange: true);

    if (env.IsDevelopment())
    {
        ...

Btw this approach also should be adopted to ´identitydata.json` and `identityserverdata.json`.

I can still provide a PR for this.

**Comment by skoruba** [comment]
For sure, please send a PR. :)
Thanks

**Comment by ViRuSTriNiTy** [comment]
@skoruba Which branch is the default target for a PR in your repo?

**Comment by skoruba** [comment]
dev

**Comment by ViRuSTriNiTy** [comment]
@skoruba PR is ready, please review it. I'm sorry for the additional clean-up commits. My VS converts the files automatically to Windows line endings and without UTF-8 BOM on save.

**Comment by ViRuSTriNiTy** [comment]
PR merged, issue closed
