### ISSUE TITLE
Switch to HTTPS for dev environment 

### ISSUE THREAD

**Issue by skoruba** [skoruba/IdentityServer4.Admin#550]
It is necesarry to switch dev environment to https: [some tips here](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio).

I will need test it on windows, linux and macOS and also configure for the docker as well.

These changes will require reconfigure the urls for IS4.

Help with this issue is really welcome. 👍

**Comment by inbarbarkai** [comment]
I understand the need but I really wish it would be possible to still run it without HTTPS.

**Comment by ViRuSTriNiTy** [comment]
@inbarbarkai But isn't this just a matter of the URL configuration and perhaps making some flags like `RequireHttpsMetadata` configurable? At least these were the parameters i changes when switching to HTTPS ...

**Comment by inbarbarkai** [comment]
When I wanted to switch to HTTPS, my first attempt (which was successful) was a pure configuration one.
In .NET Core 2.2 it was possible to define HTTPS via appsettings.json. Maybe it is still possible.
Today I'm just running it behind NGINX like recommended by [Microsoft](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-3.1).
It's simpler configuration and can be done in one place to all hosted services.

**Comment by inbarbarkai** [comment]
It is still possible:
```cs
{
  "Kestrel": {
    "Endpoints": {
      "Http": {
        "Url": "http://localhost:5000"
      },
      "HttpsInlineCertFile": {
        "Url": "https://localhost:5001",
        "Certificate": {
          "Path": "<path to .pfx file>",
          "Password": "<certificate password>"
        }
      },
      "HttpsInlineCertStore": {
        "Url": "https://localhost:5002",
        "Certificate": {
          "Subject": "<subject; required>",
          "Store": "<certificate store; required>",
          "Location": "<location; defaults to CurrentUser>",
          "AllowInvalid": "<true or false; defaults to false>"
        }
      },
      "HttpsDefaultCert": {
        "Url": "https://localhost:5003"
      },
      "Https": {
        "Url": "https://*:5004",
        "Certificate": {
          "Path": "<path to .pfx file>",
          "Password": "<certificate password>"
        }
      }
    },
    "Certificates": {
      "Default": {
        "Path": "<path to .pfx file>",
        "Password": "<certificate password>"
      }
    }
  }
}
```

**Comment by bravecobra** [comment]
Have a look at https://github.com/FiloSottile/mkcert for creating local certificates.

**Comment by skoruba** [comment]
Fixed in master, thanks.
