### ISSUE TITLE
IdentityServer4.Admin uses skoruba-ico.png although all other views use favicon.ico

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [skoruba/IdentityServer4.Admin#552]
Hi there,

i was reworking the fav icons and stumpeled upon `skoruba-ico.png` which is still used in `IdentityServer4.Admin.AccountController.AccessDenied`. All other views already use favicon.ico which is configurable via the `appsettings.json`.

I think we can safely replace / remove `skoruba-ico.png`.

I can provide a PR. What do you say?

So lonG
Daniel

**Comment by skoruba** [comment]
Hi, this favicon should be defined in appsettings.json, for sure you can send PR. Thanks 👍🏼

**Comment by ViRuSTriNiTy** [comment]
Sadly i had to move away from IdentityServer, perhaps another user can adopt this task, closing this for now.
