### ISSUE TITLE
_Layout applies right margin instead of left margin for right aligned menu items

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [skoruba/IdentityServer4.Admin#553]
Hi there,

i want to extend the menu items by adding a menu item that is always visible. Menu items are right aligned hence a margin on the left side makes more sense. With a left margin approach you can simply add items and the visible ones would right align to the upper right corner correctly.

I can provide a simple PR. What do you say?

So lonG
Daniel

**Comment by skoruba** [comment]
Hi @ViRuSTriNiTy - can you please provide some screen - what do you exactly mean?
Thx.

**Comment by ViRuSTriNiTy** [comment]
@skoruba Here is a screenshot showing a left margin instead of a right margin to ensure items added to the menu bar have a margin to its sibling on the right side.

![image](https://user-images.githubusercontent.com/12170676/77998917-208ea600-7332-11ea-9b1a-ff83fa28951f.png)

**Comment by ViRuSTriNiTy** [comment]
@skoruba Bump, please have a look at my last post. Thanks.

**Comment by ViRuSTriNiTy** [comment]
Sadly i had to move away from IdentityServer, perhaps another user can adopt this task, closing this for now.

**Comment by skoruba** [comment]
Thank you 👍🏼
