### ISSUE TITLE
Azure app : STS : 500 internal server error while redirect back to connect/authorize/callback

### ISSUE THREAD

**Issue by berajkumar12** [skoruba/IdentityServer4.Admin#557]
I followed steps mentioned [https://github.com/skoruba/IdentityServer4.Admin/blob/master/docs/Configure-Azure-Deploy.md](azure deploy) but instead of certificate thumbprint(uploading pfx file in azure app service) i tried to load pfx file directly.

I published my cert file to 'wwwroot' and it is available.

I did configuration changes as below,
`"CertificateConfiguration": {

        "UseTemporarySigningKeyForDevelopment": false,

        "CertificateStoreLocation": "LocalMachine",
        "CertificateValidOnly": true,

        "UseSigningCertificateThumbprint": false,
        "SigningCertificateThumbprint": "",

        "UseSigningCertificatePfxFile": true,
        "SigningCertificatePfxFilePath": "mycert.pfx",
        "SigningCertificatePfxFilePassword": "Password12",

        "UseValidationCertificatePfxFile": true,
        "ValidationCertificatePfxFilePath": "mycert.pfx",
        "ValidationCertificatePfxFilePassword": "Password12",

        "UseValidationCertificateThumbprint": false,
        "ValidationCertificateThumbprint": ""
    }`

In my local machine, if i run sts and admin apps, it works perfectly fine, but where as it is not working on azure app service of STS.

I am able to login successfully directly on sts site, but if i try to login from admin application, authentication is successful but (in STS app) callback throwing internal server error.

Below is the chrome developer network call details of callback,
`Request URL: https://autosecauthsts.azurewebsites.net/connect/authorize/callback?client_id=LocalAdministratorClientId&redirect_uri=https%3A%2F%2Flocalhost%3A44374%2Fsignin-oidc&response_type=code%20id_token&scope=openid%20profile%20email%20roles&response_mode=form_post&nonce=637211534404523194.NGM2YmZmYjktZjE0Yy00YmUzLTgyZjItNWNiYjRmMmJlMGM1MTA3ODEyNDktNTE0My00YzdlLTkxMzItNGFmYTQyYjUxNmRk&state=CfDJ8LFOOiLglqhBk5ZF0Otbct3NWi9LA0b2aMl_sssCdO1pqej7s7S5dvbQ1gNzHOPQvUQcxnMUru3BhXMS8H_wTMh8ZNN6eELC0WHVqK7pb-7VOQ9h19UK_e4RELZeylqYYSPjiVk1Xq-Gspp1HgdtA9RV54pfSTeB3P6ilaf8ZtTKs7yLPBFySkEIITmsjGIjgeA1heYFP57uDOk0r_hQwYfoFfR5zmUmzoNIPUsysH4xaNXVjMcFCEOOq2Q_h4Y1xADA2t54mlcUMQSdqmRCRzCk81LHuzyQK1cDT-U73SxF&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=5.5.0.0
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: 52.230.1.186:443
Referrer Policy: no-referrer
Content-Length: 0
Date: Mon, 30 Mar 2020 08:24:42 GMT
Server: Microsoft-IIS/10.0
X-Powered-By: ASP.NET
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,ta;q=0.8,en-IN;q=0.7
Cache-Control: max-age=0
Connection: keep-alive
Cookie: ARRAffinity=1d7666dade4c05b5f92ca4792a07bd8ee7539f02b0ea1e7860745cfdb14dec46; cookieconsent_status=dismiss; .AspNetCore.Antiforgery.w5W7x28NAIs=CfDJ8DXNwOhTE8NKjLuJwoIs_I0L3-RsTM5iT6Yx7oHIBBW1gmOBxvgxHv-_W50ZxlsHDOnUca8QrKGgZXASiCep4hI6w3w3HGZ-sHM7Dh6tKmdlsAgW5PK_D4N2aw2E9HD9-HPcyGZlS9KSROw9aY0qh9Q; idsrv.session=gniQOBjJ1k9cYxW-rV5TlQ; .AspNetCore.Identity.Application=CfDJ8DXNwOhTE8NKjLuJwoIs_I1816ZSHlGVupLFoOQPfkVimM_U-XTw_LK5oetI2Yx1rTtArEWiJBdAADQ68jmdz2xzXT00BRQSAKSNIUqpkMD9bV0SmBSZjAqlDc0yS_NTy-Mha9DLsZMZ7AA2cZbtX8_MEYCcozx9ZKPhGWqGmbkGTB3eI5CcD6zQlhsFif1RJ1BdA8j7Vy1UH-1ewyVjHxfzyswnsH56Gxqj-7Eddwnk6wGTCfiv4CAwivC99t388Zo489QmJLlH7q4ImjExtP3x5drRa2WrvZF1I91c7oehT9MZHwMgpnWposWHHm-UwNu3yFJzH6Cff9Wy36uINEwjwZyORZRRgjpoK3Em2WzbpVVajomEGtmuJ5d6ZN1ll7JX1ecOzWp0IT8C2YGSySLImm2-3vWZwKA_OjfAZRXeKh0eupsjo7SQ8yKkMITntPf2d4LshV0ZLIc0fTSAKPsRDdWsOvax_vdd83pn_Kvon3EowOXHd13T33jCjmHMOb6fvN7dv_09vytQdJ4z-LbtdpMIYv2eGUyCSmRsz3uEETVdNd-i3yn4mOydTNRW7fxI74hdkroQ37h4pN-t8Efpdrq9lOVF99EfumWzwsNOJTCTWn4sHexC1nc-7GZJsj_xp-FcPRy3qMJxyjFpV2foPSkO3wMAdECCgOMmKLkF014nJy-c01Dvf8HRyySBUT8-m3q0NuO5LpgHAja6wmh44UKFVMGbYZl7MJCrtqZBQwieeH2FW2aZMeCMNbQqd7ICNXbgage8TSp1dKreSNQ-QY4B0-idIff3uALr30xRLY6Iaf5FqIMeQYyXHTJgv75ykokYG8JwlfufvK24im1hGtUc3IJUIBTKRPAxjd5T0l6jKLDB2CDLOvHJhZLplc4JVRh3pNoOwHxqFErqYqY
Host: autosecauthsts.azurewebsites.net
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
client_id: LocalAdministratorClientId
redirect_uri: https://localhost:44374/signin-oidc
response_type: code id_token
scope: openid profile email roles
response_mode: form_post
nonce: 637211534404523194.NGM2YmZmYjktZjE0Yy00YmUzLTgyZjItNWNiYjRmMmJlMGM1MTA3ODEyNDktNTE0My00YzdlLTkxMzItNGFmYTQyYjUxNmRk
state: CfDJ8LFOOiLglqhBk5ZF0Otbct3NWi9LA0b2aMl_sssCdO1pqej7s7S5dvbQ1gNzHOPQvUQcxnMUru3BhXMS8H_wTMh8ZNN6eELC0WHVqK7pb-7VOQ9h19UK_e4RELZeylqYYSPjiVk1Xq-Gspp1HgdtA9RV54pfSTeB3P6ilaf8ZtTKs7yLPBFySkEIITmsjGIjgeA1heYFP57uDOk0r_hQwYfoFfR5zmUmzoNIPUsysH4xaNXVjMcFCEOOq2Q_h4Y1xADA2t54mlcUMQSdqmRCRzCk81LHuzyQK1cDT-U73SxF
x-client-SKU: ID_NETSTANDARD2_0
x-client-ver: 5.5.0.0`

**Comment by berajkumar12** [comment]
Also i tried  to check log file in log\skoruba_admin.txt in azure app service. I am seeing file is empty. I dont know why log is not happnening. 

My serilog config,
`{
                "Name": "Console"
            },
            {
                "Name": "File",
                "Args": {
                    "path": "Log\\skoruba_admin.txt",
                    "rollingInterval": "Day"
                }
            },
            {
                "Name": "MSSqlServer",
                "Args": {
                    "connectionString": "Server=abcd.postgres.database.azure.com;Database=abcd;Port=5432;User Id=postgres@abcd;Password=Dasdasd1;Ssl Mode=Require;",
                    "tableName": "Log",
                    "columnOptionsSection": {
                        "addStandardColumns": [ "LogEvent" ],
                        "removeStandardColumns": [ "Properties" ]
                    }
                }
            }`

**Comment by HashTagDotNet** [comment]
My log\skoruba_admin text is also empty

**Comment by skoruba** [comment]
Hi, sorry for delay answer. 
Can you please check also errors in STS?
Thanks

**Comment by skoruba** [comment]
I am closing this. Feel free reopen. Thank yoh
