### ISSUE TITLE
Consider moving Asp.Net Identity into the separate projects

### ISSUE THREAD

**Issue by skoruba** [skoruba/IdentityServer4.Admin#56]
I'd like to create the project template via `dotnet new` that doesn't include the part with AspNet Identity therefore I'd like to move Asp.Net Identity into the separate projects. 

**BusinessLogic:**
- Skoruba.IdentityServer4.Admin.BusinessLogic
- Skoruba.IdentityServer4.Admin.BusinessLogic.AspNetIdentity

**EntityFramework:**
- Skoruba.IdentityServer4.Admin.EntityFramework
- Skoruba.IdentityServer4.Admin.EntityFramework.AspNetIdentity

**Comment by cerginio** [comment]
There is need to separate AdminDbContext to AspnetIdentityDb, ConfigurationDb, OperationalStorageDb.
In our solution we aim to keep them separately in different databases to backup only configuration db. When using AdminUI component AdminDbContext is forces to use single Db for all 3 contexts.

**Comment by skoruba** [comment]
Done on master - #99
