### ISSUE TITLE
Problem with HomePageLogoUri when deploying STS project as Virtual Application on IIS

### ISSUE THREAD

**Issue by tancevsasa** [skoruba/IdentityServer4.Admin#560]
When I tried to publish **STS.Identity** project as Virtual Application as ***/auth** subdomain of existing website  **/images/skoruba-icon.png** image defined under **HomePageLogoUri** parameter in appsettings.json is not shown properly in **Home/Index.cshtml** page.

Note: I deployed STS project under **\auth** virtual appliciation 

After reviewing rendered HTML `h1` element is rendered as:
`<img class="icon" alt="Logo" src="/images/skoruba-icon.png"`

but should be rendered as 
`<img class="icon" alt="Logo" src="/auth/images/skoruba-icon.png"`

There is solution that will work in any cases 
- when STS project is deployed as normally 
- when it's deployed as subdomain or virtual application  

Solution is:
1. To use **@inject IUrlHelper UrlHelper** that could be added 
   - into **Index.cshtml** page directly or 
   - into **_ViewImports.cshtml**

2. and to change h1 element from 
`<h1 class="display-4"><img class="icon" alt="Logo" src="RootConfiguration.AdminConfiguration.HomePageLogoUri"><br />@RootConfiguration.AdminConfiguration.PageTitle</h1>`
to
`<h1 class="display-4"><img class="icon" alt="Logo" src="@UrlHelper.Content(RootConfiguration.AdminConfiguration.HomePageLogoUri)"><br />@RootConfiguration.AdminConfiguration.PageTitle</h1>`

     Difference is in 
     src="**@UrlHelper.Content**(RootConfiguration.AdminConfiguration.HomePageLogoUri)"

3. appsettings.json entry 
"HomePageLogoUri": "/images/skoruba-icon.png",
sholud be 
"HomePageLogoUri": "**~**/images/skoruba-icon.png",
 
Screenshot 01 - defined IIS virtual applications under parent website 
![image](https://user-images.githubusercontent.com/4563019/77947735-aaa02580-72c4-11ea-8226-324ef60d38d3.png)

Screenshot 02  - current STS implementation 
![image](https://user-images.githubusercontent.com/4563019/77947941-f18e1b00-72c4-11ea-8737-71c9a6b7c17e.png)

Screenshot 03  - layout after provided solution has been implemented 
![image](https://user-images.githubusercontent.com/4563019/77948079-20a48c80-72c5-11ea-9453-2f356491c9b3.png)

Thanks,
Sasa Tancev

**Comment by skoruba** [comment]
Hi, can you please send PR for this? :-)

Thanks

**Comment by skoruba** [comment]
Fixed in master, thanks 👍🏼
