### ISSUE TITLE
How do I implement m2m client credentials flow in api?

### ISSUE THREAD

**Issue by cculver** [skoruba/IdentityServer4.Admin#568]
I'd like to code against the api from another web service (e.g. to create a user programmatically and assign it roles) and I'm just trying to understand how to get this going. I'm pretty certain by this point that I need to do the client credentials flow, but the admin api seems to require the Administration Role on the client (StartupHelpers.cs:243). Since there's no user, I'm not sure how to get that role in there. This is probably simple, but I haven't spent much time in this space. I have read a few similar questions but they appear to be a bit older and I'm not sure if the solution lies only in the dev branch or if that's been merged into master by now. Thanks for your help!

**Comment by skoruba** [comment]
Hey,
Did you figure out how to achieve this?
Thanks

**Comment by cculver** [comment]
I finally found the client claims and added the right value to it. I haven't gotten around to querying /token for the token and submitting it to the api server yet. Is there a dedicated client available that wraps the calls to the api server?

**Comment by skoruba** [comment]
What do you mean with dedicated client? By default this type of client is not created during the initial seed. :-)

**Comment by cculver** [comment]
Yes, probably bad wording given the nomenclature surrounding identity. What I mean to ask is this: is there a project/dll/nuget package that wraps the calls to the admin api such that we can use that instead of writing raw calls with HttpClient. If I have the wrong idea about the admin api, tell me, but it seems that there is a better way to do this than to manually go out and hit /token, get and store the token, and add that token to the actual call, then deserialize the returned content. I write these things a lot, and if anyone is in a similar circumstance to me where I need to automate the creation of accounts, assigning of roles, etc, then a client like this might be helpful. Is that the intended use of the admin api?

**Comment by bmurali31** [comment]
Hello,
I am stuck at making admin api calls using client_credentials token. My api client has claim called "role" and its value is set to Admin role. Still when I hit the endpoint e.g http://localhost:5001/api/Users with Bearer token I get empty response.
Any help in this would be greatly appreciated.  
Thanks

**Comment by bmurali31** [comment]
> I finally found the client claims and added the right value to it. I haven't gotten around to querying /token for the token and submitting it to the api server yet. Is there a dedicated client available that wraps the calls to the api server?

Hello @cculver,
What are the client claims you added for your m2m client to get it working?

**Comment by bmurali31** [comment]
Never mind. I was able to hit the api with just role client claim as Admin.

**Comment by skoruba** [comment]
Hi @bmurali31 
1.) you can create new client and use `client_credential` flow
2.) go to `client claims` and setup claim called - `role` = `Admin role` (value is according to your configuration). And in API is authorization check like this:
https://github.com/skoruba/IdentityServer4.Admin/blob/master/src/Skoruba.IdentityServer4.Admin.Api/Helpers/StartupHelpers.cs#L242-L244

NOTE: If client has claim called: `client_role` = `AdminRole` - everything should work correctly.
By default client claims has prefix `client_` so you should only add client claim called `role`.
