### ISSUE TITLE
How to map user phone number to claim?

### ISSUE THREAD

**Issue by spaasis** [skoruba/IdentityServer4.Admin#570]
Hi,

In the user profile page there is a field for a phone number, but it seems that by default this is not mapped to any claim. How could this mapping be done so that I won't have to manually add this claim to every user?

**Comment by pavel-usachev** [comment]
Try adding `phone_number` claim to some identity resource, for example `profile`.

![image](https://user-images.githubusercontent.com/540241/88213993-22260600-cc62-11ea-94a7-74075d7ab918.png)

Then ask for this scope and as identity resource you should be able to find it in `id_token` .

![image](https://user-images.githubusercontent.com/540241/88213876-fdca2980-cc61-11ea-8efd-a1f41f6e3a32.png)

**Comment by spaasis** [comment]
@pavel-usachev  Thanks, this works! Sorry for the long wait. For some reason phone_number is not instantly mapped in my client application Claims but I see it at the /connect/userinfo endpoint, so I'll close this and try to figure out why every other property (given_name, preferred_username etc.) works out of the box

**Comment by spaasis** [comment]
Followup: Had to add this to the my ASP app to get the mapping to work:
```
services.AddAuthentication(..)
.AddOpenIdConnect(opt=>...
    opt.ClaimActions.MapJsonKey(JwtClaimTypes.PhoneNumber, JwtClaimTypes.PhoneNumber, JwtClaimTypes.PhoneNumber);
```
