### ISSUE TITLE
PersistedGrantsController has errors with Automapper

### ISSUE THREAD

**Issue by flyznex** [skoruba/IdentityServer4.Admin#580]
When request action in PersistedGrantsController. Automapper will throw exception with mapping profile. I don't change anything presistedgrant model.
```
An unhandled exception has occurred while executing the request.
AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.

Mapping types:
PersistedGrantsDto -> PersistedGrantSubjectsApiDto
```

**Comment by flyznex** [comment]
I added `CreateMap<PersistedGrantsDto, PersistedGrantSubjectsApiDto>(MemberList.Destination);` to PersistedGrantApiMapperProfile.cs but it still not working.

**Comment by skoruba** [comment]
Thanks, let me check it. 🙂
