### ISSUE TITLE
[question] Should the Admin client use Code w/PKCE instead of Hybrid Flow?

### ISSUE THREAD

**Issue by selangley-wa** [skoruba/IdentityServer4.Admin#581]
I've read lately that the Authorization Code flow with PKCE is now recommended for most application types.

[IdentityServer4 Docs](http://docs.identityserver.io/en/latest/topics/grant_types.html#interactive-clients)
[Philippe De Ryck on OAuth 2.0 best practices](https://pragmaticwebsecurity.com/files/cheatsheets/oauth2securityfordevelopers.pdf)

Is there a reason why the Admin client uses the hybrid flow?  Perhaps the hybrid flow is good enough?

I see that I can change the configuration for the Admin client to use Code w/PKCE and it works (dev branch).

Thanks.

**Comment by skoruba** [comment]
Yes, I will update it to Authorization Code flow with PKCE - and client templates as well. 
Thanks

**Comment by pavel-usachev** [comment]
By the way, isn't it strange that code flow can work with PKCE, but when it comes to hybrid flow, `response_type=code (+ smth)`, it turns off PKCE?

This line puzzles me https://github.com/dotnet/aspnetcore/blob/16e25867248cb446bf1bba3f975c6e676b52ba6e/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L369.

**Comment by skoruba** [comment]
Fixed in master. 👍🏼 Thanks
