### ISSUE TITLE
Registration issue without UserName

### ISSUE THREAD

**Issue by jack1232** [skoruba/IdentityServer4.Admin#583]
In the STS.Identity project, I set:

 "LoginConfiguration": { 
    "ResolutionPolicy": "Email"
  }

This allows user to register or login without UserName. However, when trying to register a new user without UserName, i get the following error:

An unhandled exception occurred while processing the request.
InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'Gincker.STS.Identity.ViewModels.Account.RegisterViewModel', but this ViewDataDictionary instance requires a model item of type 'Gincker.STS.Identity.ViewModels.Account.RegisterWithoutUsernameViewModel'.

 How to make it working without the UserName?

Thanks

**Comment by skoruba** [comment]
I will check it, thanks for reporting this.

**Comment by jack1232** [comment]
This only happens if a user was already registered. If you try to add the same user again, you will get the above error.

This error can be eliminated by adding an IF statement to the end of the  Register POST method in the AccountControllor class:

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterViewModel model, string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");
          ......

            // If we got this far, something failed, redisplay form

          // add this code to avoid error:
           if(_loginConfiguration.ResolutionPolicy == LoginResolutionPolicy.Email)
            {
                return View(new RegisterWithoutUsernameViewModel());
            }           

            return View(model);
        }

**Comment by opena854** [comment]
Actually this happend because model returned by Register method is RegisterViewModel but the Email policy expects a RegisterWithoutUsernameViewModel model. 

You can easy fix this by making RegisterViewModel extends RegisterWithoutUsernameViewModel and removing the duplicated properties, like this:
```
namespace gp_admin.STS.Identity.ViewModels.Account
{
    public class RegisterViewModel : RegisterWithoutUsernameViewModel
    {
        [Required]
        public string UserName { get; set; }

    }
}
```

**Comment by skoruba** [comment]
This is solved in master branch. Thank you 😉👍
