### ISSUE TITLE
Duplicate health checks when use MySQL as database provider

### ISSUE THREAD

**Issue by O-R** [skoruba/IdentityServer4.Admin#584]
The following exception in Project Skoruba.IdentityServer4.Admin.Api was thrown when host run：

> Duplicate health checks were registered with the name(s): PersistentGrantsDb, IdentityDb (Parameter 'registrations')

something wrong found in [IdentityServer4.Admin/src/Skoruba.IdentityServer4.Admin.Api/Helpers/StartupHelpers.cs#L312-L318](https://github.com/skoruba/IdentityServer4.Admin/blob/master/src/Skoruba.IdentityServer4.Admin.Api/Helpers/StartupHelpers.cs#L312-L318)
```
                    case DatabaseProviderType.MySql:
                        healthChecksBuilder
                            .AddMySql(configurationDbConnectionString, name: "ConfigurationDb")
                            .AddMySql(persistedGrantsDbConnectionString, name: "PersistentGrantsDb")
                            .AddMySql(identityDbConnectionString, name: "IdentityDb")
                            .AddMySql(logDbConnectionString, name: "PersistentGrantsDb")
                            .AddMySql(auditLogDbConnectionString, name: "IdentityDb");
                        break; 
```
fix as #585

**Comment by skoruba** [comment]
I think we fixed this in dev branch. Can you please check the latest dev branch?
Thanks.
