### ISSUE TITLE
Migration on sql server fails when applying ChangeAuditLogToLong

### ISSUE THREAD

**Issue by bravecobra** [skoruba/IdentityServer4.Admin#586]
When trying to apply the migrations on SQL Server, they fail with the following error:
`The object 'PK_AuditLog' is dependent on column 'Id'.ALTER TABLE ALTER COLUMN Id failed because one or more objects access this column.` at the migration `20200419130339_ChangeAuditLogToLong`.

I know it's hard to change the types of primary keys, but just using an alter statement is not an option.
I started from a fresh database.

**Comment by skoruba** [comment]
Thanks @bravecobra for reporting, I fixed this issue in #587

**Comment by skoruba** [comment]
Fixed in master, thanks.
