### ISSUE TITLE
Unauthorized_Client in Admin UI (Azure hosted)

### ISSUE THREAD

**Issue by jhone18** [skoruba/IdentityServer4.Admin#588]
Did everything in the instructions in deploying the projects in Azure App Services. However I encounter an error when running the admin ui. It says unauthorized_client,  could you help me on this? No issues on my local solution.

Error
Sorry, there was an error : unauthorized_client
Request Id: 800000bd-0000-eb00-b63f-84710c7967bb

It runs perfectly on sts in azure but only the admin keeps on failing.

**Comment by jhone18** [comment]
here is the URL for reference.

https://idsrv4-sts.azurewebsites.net
https://idsrv4-admin.azurewebsites.net

error:
https://idsrv4-sts.azurewebsites.net/connect/authorize?client_id=AdminClientId&redirect_uri=https%3A%2F%2FIdSrv4-admin.azurewebsites.net%2Fsignin-oidc&response_type=code%20id_token&scope=openid%20profile%20email%20roles&response_mode=form_post&nonce=637234844438856476.MDQ5MjY4NTktYzEwOC00MWQxLTgxNzItZTQ1ODJkMmIyMDY0NWU3OGE5OTUtM2U3ZS00MmNhLTk2ZjYtODg3MTEwMmY1NDMw&state=CfDJ8FjyfAOASgxFuBuYmZaoV1UyX9I2gA4b7MoQo1NDK0CjPYGx99Uj-mdW9chf5m19XR69F5DkPIZ3uN_7R-iabbApsnhPBHWhVQwBGW4xgR4VIlD28bvJO65AtQH3psV1ScyJajRLvDpSGoJaa_pGsnbgAg1WD0OVafwYFXW2bb6xii0F82rg32ZKlTF-KzQbsu6RO7w5Papy-QWDqcUnh1n1quUftiMKIc1HfCMVCns_lGYiho1srAx7LdBbOxRGVfewDLNkj15ye-dzCqoJTI7mRnDxa-2Q1a6Sd_EnwxtjYoAKx7Lf4hCRIduIu1Tgbg&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=5.5.0.0

**Comment by ViRuSTriNiTy** [comment]
This is most likely caused by a wrong client id (querystring parameter client_id) or a mismatch of the redirect uri (query string parameter redirect_uri).

**Comment by jhone18** [comment]
Thanks. yeah. but I didn't do any changes after publishing to azure.

> 
> 
> This is most likely caused by a wrong client id (querystring parameter client_id) or a mismatch of the redirect uri (query string parameter redirect_uri).

**Comment by jhone18** [comment]
> 
> 
> Thanks. yeah. but I didn't do any changes after publishing to azure.
> 
> > This is most likely caused by a wrong client id (querystring parameter client_id) or a mismatch of the redirect uri (query string parameter redirect_uri).

**Comment by jhone18** [comment]
> 
> 
> This is most likely caused by a wrong client id (querystring parameter client_id) or a mismatch of the redirect uri (query string parameter redirect_uri).

Thanks.
yeah, but I didn't do any changes on the client id or anything in the querystring. It works when I used the localhost but not hosted in Azure. Is there anything that I could change when publishing to Azure or configurations?

**Comment by skoruba** [comment]
Can you please check log? I think there are more details. Can you share your identityserver configuration file? Thanks

**Comment by ViRuSTriNiTy** [comment]
> > This is most likely caused by a wrong client id (querystring parameter client_id) or a mismatch of the redirect uri (query string parameter redirect_uri).
> 
> Thanks.
> yeah, but I didn't do any changes on the client id or anything in the querystring. It works when I used the localhost but not hosted in Azure. Is there anything that I could change when publishing to Azure or configurations?

When you say you use localhost then you most likely have a redirect uri like https://localhost configured which obviously doesn't match the azure environment right?

**Comment by Spookenator** [comment]
I am having the same issue on my side. 
What is weird is that the AdminClient is not updating the Log database entry.

**Comment by Spookenator** [comment]
I just redeployed everything from a new template and it seems to be working. 
I think the problem was that when I was seeding the database that i did not update the defaults for identitydata.json and identityserverdata.json. 
Everything seems to be working fine now.
