### ISSUE TITLE
Referencing incorrect Cert Config value

### ISSUE THREAD

**Issue by kamrowskik** [skoruba/IdentityServer4.Admin#589]
https://github.com/skoruba/IdentityServer4.Admin/blob/be6fc55a61d890378dd21f9110c2850e963a487f/src/Skoruba.IdentityServer4.STS.Identity/Helpers/IdentityServerBuilderExtensions.cs#L158

Correct me if I'm wrong, but did you mean to use "certificateConfiguration.ValidationCertificatePfxFilePath" vs "certificateConfiguration.SigningCertificatePfxFilePath"?

**Comment by skoruba** [comment]
Hi @kamrowskik - thanks for this catch, I will fix it. Sorry for delayed answer. ;)

**Comment by kamrowskik** [comment]
No worries. Great work on this project by the way. Thanks for everything!
