### ISSUE TITLE
Introduce AppSettings based on IOptions aspnetcore feature

### ISSUE THREAD

**Issue by cerginio** [skoruba/IdentityServer4.Admin#60]
Actually AdminUI IdSrv4 intergation and authorization params  configured in  AuthorizationConsts: 

```
        public const string AdministrationPolicy = "RequireAdministratorRole";
        public const string AdministrationRole = "PlutoRootAdministrator";
        public const string IdentityAdminCookieName = "IdentityServerAdmin";        
        public const string IdentityAdminRedirectUri = "http://localhost:9000/signin-oidc";
        public const string IdentityServerBaseUrl = "https://localhost:44301/idsrv";
        public const string IdentityAdminBaseUrl = "http://localhost:9000";
```

I would suggest  to use AppSettings class for that, which mapped to appsettings section in appsettings.JSON and IAppSettings rigistered as dependency in DI container.

Detailed about `IOptions<TSettings>` aspnetcore feature here:
https://joonasw.net/view/asp-net-core-1-configuration-deep-dive
```
services.AddOptions();
services.Configure<MySettings>(Configuration.GetSection("MySettings"));
```

**Comment by skoruba** [comment]
@cerginio Please, can you specify what you specifically suggest? I'll be happy for some detail.

**Comment by skoruba** [comment]
Hi @cerginio,

I'll be happy for your help and pull requests! :)
If you have any ideas, please share them with us.

Thank you.

**Comment by skoruba** [comment]
Done on master - #99
