### ISSUE TITLE
"Unknown client or not enabled" error for skoruba_identity_admin when i disable Consent

### ISSUE THREAD

**Issue by shanojscp** [skoruba/IdentityServer4.Admin#601]
Great respect for the work so far!

"Unknown client or not enabled" error for skoruba_identity_admin when i disable Consent

Message":"Unknown client or not enabled: \"skoruba_identity_admin\"

Thanks

**Comment by shanojscp** [comment]
This is fixed. Mistake from my side.

**Comment by antonyarulraj** [comment]
I'm also getting the same error. what is the issue @shanojscp ?

**Comment by skoruba** [comment]
@antonyarulraj - check error log from identity server.
