### ISSUE TITLE
Not Logging In

### ISSUE THREAD

**Issue by imabdul-dev** [skoruba/IdentityServer4.Admin#608]
### Question
I have cloned the repo or even tried with CLI commands which are mentioned in readme.md.
I am using SQL server. I was trying to log in with the default username and password event which in identity data.json. The line for seed is also uncommented. But still, I can not log into the admin portal. Even I created a new account then tried to log in but still not work. Whenever I tried to log in application return to the login page again.
Is there anything missing?

**Comment by b0** [comment]
Probably related to #582

**Comment by skoruba** [comment]
Hi @imabdul-dev - do you have more details about this issue? Some log information?
Thanks

**Comment by imabdul-dev** [comment]
I this this was due to one of the chrome's extension most probably ad-block. Now it is working fine thanks by  the way.

**Comment by felipebossolani** [comment]
Same here, opened in a anonymous tab and work like a charm.
