### ISSUE TITLE
Add audit tables to track IdSrv configuration data changes

### ISSUE THREAD

**Issue by cerginio** [skoruba/IdentityServer4.Admin#61]
During administration clients, scopes, users, roles may be important to have control on it's history.

One of the cheap way to get changes history could be SQL server Track Data Changes feature.
1. Add feature for SQL server
https://docs.microsoft.com/en-us/sql/relational-databases/track-changes/enable-and-disable-change-data-capture-sql-server?view=sql-server-2017
2. Add views to read tracking changes tables and build around them AuditDbContext.

Second options is to realize it on application level by using EF handlers and changetracker.
https://blog.tonysneed.com/2017/10/01/trackable-entities-for-ef-core/

**Comment by ruant** [comment]
I would like to see it not bound to MSSQL, that way people can choose what SQL technology they want to run themselves.

**Comment by skoruba** [comment]
I agree with @cerginio - audit log is very important. I'll check some details about the implementation that mentioned @ruant - it will be nice to use the implementation independent of the database engine.

**Comment by skoruba** [comment]
@cerginio - Any suggestions about that?

**Comment by cerginio** [comment]
I would chose application level logging based on EF handlers. Defenetely we must store in each row for each history table username from bearer token. I would use change tracker state and save row before change into history table. That tables should be defined in separate audit db context.
But how to achieve that with clean code is a big question, taking into account that we reuse ids4 entity model and do not have control on it.

**Comment by cerginio** [comment]
I would chose application level logging based on EF handlers. Defenetely we must store in each row for each history table username from bearer token. I would use change tracker state and save row before change into history table. That tables should be defined in separate audit db context.
But how to achieve that with clean code is a big question, taking into account that we reuse ids4 entity model and do not have control on it.

**Comment by Robban1980** [comment]
I think an important part here is not also not bind this functionality to a specific storage type, like EventStore. 
Raise an audit event and if subscribed to, the implementer can decide what they want to do with it. Be it  storing it in MSSQL, PostgreSQL, EventStore etc.

**Comment by skoruba** [comment]
Currently I am working on this stuff here:
https://github.com/skoruba/IdentityServer4.Admin/tree/feature/audit-logging

**Comment by pbros** [comment]
Will this audit logging extend to logging user logins?

 It would be useful to have an audit log of successful (and failed) login history for each user. If presented to the user, he could notice suspicious activity

**Comment by cerginio** [comment]
I played a bit with simple audit implementation in db agnostic way:
https://dejanstojanovic.net/aspnet/2018/november/tracking-data-changes-with-entity-framework-core/
https://www.meziantou.net/2017/08/14/entity-framework-core-history-audit-table

And it descover overhead in DAL implementation.
RemoveClientRelationsAsync(Client client) in 
https://github.com/skoruba/IdentityServer4.Admin/blob/8ea5449965c8254d28c36c82ab45a6a77eafa663/src/Skoruba.IdentityServer4.Admin.BusinessLogic/Repositories/ClientRepository.cs

If you update single propery in Client - let's say Description from "A" to "B",
in audit logs you will see like all 9 navigation properties was removed and inserted!
and all client properties was modified. I tried to manually calculate diff and separate from the noise, but it killing my brain. it not worth of it.

@skoruba please consider how to implement an update in a more smart and lean way.
Above audit obfuscation such approach to update the whole client tree for single change kills performance.

I will try to suggest PR with audit this week.

**Comment by cerginio** [comment]
#298 
PR suggested

1. Please take changes
2. add migration for Audits table
3. update db
4. play with UI
- choose random client
- update description from "A" to "B"
5. SELECT *   FROM [dbo].[ClientConfigAudit]

ER: 13 changes in audit log
1 modify
6 delete
6 inserts

![audit-1](https://user-images.githubusercontent.com/2261603/59702778-2e3ec900-9201-11e9-8aeb-9717c187e5fd.PNG)

**Comment by cerginio** [comment]
expected:
1 modify

![audit-2](https://user-images.githubusercontent.com/2261603/59703041-c2109500-9201-11e9-84de-2a38bbe8573d.PNG)

**Comment by skoruba** [comment]
Done in #391

**Comment by skoruba** [comment]
I am closing this issue, it was released in master branch.
