### ISSUE TITLE
Identity server heathy check name conflict for mysql

### ISSUE THREAD

**Issue by BinGuoGuo** [skoruba/IdentityServer4.Admin#617]
at src\Skoruba.IdentityServer4.Admin.Api\Helpers\StartupHelpers.cs line 317-318

Please change this fragment from
```
.AddMySql(logDbConnectionString, name: "PersistentGrantsDb")
.AddMySql(auditLogDbConnectionString, name: "IdentityDb");
```
to
```
.AddMySql(logDbConnectionString, name: "LogDb")
.AddMySql(auditLogDbConnectionString, name: "AuditLogDb");
```

**Comment by skoruba** [comment]
Hi @BinGuoGuo - thanks for reporting this issue - please check dev branch, there is already fixed. I will release this bug this month.

Thanks.

**Comment by skoruba** [comment]
Fixed in master, thanks. 😊
