### ISSUE TITLE
Cannot update extended RoleDto properties from the UI

### ISSUE THREAD

**Issue by NiraniK** [skoruba/IdentityServer4.Admin#618]
We have extended UserDto, RoleDto , UserIdentity and UserIdentityRole to have additional properties.

```
 public class ExtendedUserDto<TKey> : UserDto<TKey>, IExtendedUserDto
    {
        public string FirstName { get; set; }

        public string LastName { get; set; }
    }

public class ExtendedRoleDto<TKey> : RoleDto<TKey>, IExtendedRoleDto
    {
        public string Description { get; set; }
    }

```
We are trying to update the UI to include those so that we can update their values from the UI. We have successfully updated the UI for extended UserDto properties. But for RoleDto it is not working as expected. 

When we create a new Role, it saves the data for additional properties. But when we update an existing Role, it doesn't update values for additional properties. After further investigating, we found that updating roles (UpdateRoleAsync method) doesn't use Mapper as it is used when updating users (UpdateUserAsync method) in Skoruba.IdentityServer4.Admin.EntityFramework.Identity.Repositories .

```
public virtual async Task<(IdentityResult identityResult, TKey roleId)> UpdateRoleAsync(TRole role)
 {
            var thisRole = await RoleManager.FindByIdAsync(role.Id.ToString());
            thisRole.Name = role.Name;

            var identityResult = await RoleManager.UpdateAsync(thisRole);
            return (identityResult, role.Id);
        }

public virtual async Task<(IdentityResult identityResult, TKey userId)> UpdateUserAsync(TUser user)
        {
            var userIdentity = await UserManager.FindByIdAsync(user.Id.ToString());            
            Mapper.Map(user, userIdentity);
            var identityResult = await UserManager.UpdateAsync(userIdentity);

            return (identityResult, user.Id);
        }
```

Can UpdateRoleAsync method be updated to use Mapper similar to UpdateUserAsync method?

**Comment by skoruba** [comment]
Hi @NiraniK - thanks for reporting this bug - it is already fixed in dev branch, I will release this in this month. Thanks!

**Comment by skoruba** [comment]
Fixed in master, thanks.
