### ISSUE TITLE
Serilog integration

### ISSUE THREAD

**Issue by cerginio** [skoruba/IdentityServer4.Admin#62]
IdentityServer4 authors "kind of recommend" to use Serilog  http://docs.identityserver.io/en/release/topics/logging.html
https://github.com/serilog

Serilog has basic sinks for 
File (https://github.com/serilog/serilog-sinks-file)
Database (https://github.com/serilog/serilog-sinks-mssqlserver)
and enterprise level sinks for Splunk, Azure AppInsights, ElasticSearch etc.

Also Enrichers concept allows to customize on DI container level tracking properties.

I would use Serilog to log into existing Log table in Admin context,
and add Logging configuration section to appsettings.json with sinks configurations.

**Comment by skoruba** [comment]
Done
