### ISSUE TITLE
RegisterWithoutUsername issue

### ISSUE THREAD

**Issue by johndcollins** [skoruba/IdentityServer4.Admin#622]
### Describe the bug
If I use the RegisterWithoutUsername functionality there is a problem in the code if there is an error during the registration process. Since RegisterWithoutUsername calls the regular Register process with a new model, if the error returns the model in Register I get an error that the ViewModel should be RegisterWithoutUsernameViewModel not RegisterViewModel.

### To Reproduce
Just produce and error during Register with the RegisterWithoutUsername functionality like a duplicate email address

### Relevant parts of the log file

```
<log goes here>
```

**Comment by skoruba** [comment]
Hi, please, can you send a PR which fixed this use case? Thanks

**Comment by johndcollins** [comment]
I just duplicated the code from Register instead of calling Register with a new ViewModel from RegisterWithoutUsername.

**Comment by skoruba** [comment]
Ok, I will test. Thanks for reporting @johndcollins 👍

**Comment by skoruba** [comment]
Solved in master branch. 😉👍
