### ISSUE TITLE
Recommendation how to send validate email from Admin API

### ISSUE THREAD

**Issue by we4sz** [skoruba/IdentityServer4.Admin#623]
### Question
First of all, thank you for this project, it have saved me countless of hours in multiple projects!

But I have a question that I never seem to solve in a good way.
How would you recommend me to implement verify email from the Admin API when I create a user.
I can't seem to get the logic for UserManages GenerateEmailConfirmationTokenAsync to work in the API.  

The same with the forgot password functionallity.

**Comment by b0** [comment]
Code that makes `GenerateEmailConfirmationTokenAsync` work called even from API is on a dev branch. It's DataProtection. Added [here](https://github.com/skoruba/IdentityServer4.Admin/blob/bfcdfa28c993933e244d3d55bb33ca78e3592f53/src/Skoruba.IdentityServer4.Admin.Api/Startup.cs#L47).

So, I would suggest that you try with latest code available.

**Comment by we4sz** [comment]
@b0 Perfect! Got this working! Yay!
