### ISSUE TITLE
Api endpoint do not return created item

### ISSUE THREAD

**Issue by thomas-illiet** [skoruba/IdentityServer4.Admin#635]
Hello guy’s

 I use actively your api to insert or update a lot of claims ( 2000000 claims / 300000 users ) and I have two issues for this usage.

- Unable to update claim entity
- Claim identifier is not returned at creation ( global issues on this api )

Kind regards 
Thomas

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by skoruba** [comment]
Hi,
Can you please send a sample of your Api call?

Thanks

**Comment by thomas-illiet** [comment]
Yop,

You can find in attachment a screenshot of my request ( sorry for that i can't use github on my work computer .... )

![api](https://user-images.githubusercontent.com/2133666/85234224-3204bd00-b40c-11ea-81f6-ab550fda8bb7.jpg)

Kind regards
Thomas
