### ISSUE TITLE
ef 怎么迁移到远程数据库，命令怎么写？以下命令执行会Build failed.

### ISSUE THREAD

**Issue by LiWenZi** [skoruba/IdentityServer4.Admin#636]
update-database DbInit -Context AdminIdentityDbContext -Project Skoruba.IdentityServer4.Admin.EntityFramework.MySql

**Comment by chen1tian** [comment]
build失败跟迁移没关系，请编译通过后在执行迁移命令。

**Comment by b0** [comment]
@LiWenZi @chen1tian could you write in English please? Thank you.

**Comment by seamusic** [comment]
请将你的编译错误截图出来。

**Comment by hdu7** [comment]
Identity Server and Identity Server Administration UI
Initial setup steps
1. Build solutions
2. Change Database connection inside
		IdentityServer.Admin->appsettings.json
		IdentityServer.STS.Identity ->appsettings.json
2. Create DB, Run each commands from nuget package console, selected project should be IdentityServer.Admin
        update-database -context IdentityServerConfigurationDbContext
        update-database -context IdentityServerPersistedGrantDbContext
        update-database -context AdminIdentityDbContext
        update-database -context AdminLogDbContext
3. Done

**Comment by skoruba** [comment]
I am closing now this issue, feel free reopen. Thanks
