### ISSUE TITLE
Skoruba.IdentityServer4.Admin.Api should support client credentials?

### ISSUE THREAD

**Issue by ekjuanrejon** [skoruba/IdentityServer4.Admin#639]
### Question
Should Skoruba.IdentityServer4.Admin.Api also support client credentials apart form the implicit flow

I want to currently use Skoruba.IdentityServer4.Admin.Api and I have an api gateway in front of Skoruba.IdentityServer4.Admin.Api. The Authorization Policy is forcing for some claims to be available.

**Comment by skoruba** [comment]
Client credentials flow is already configured there. Does it work for you?
