### ISSUE TITLE
Add IdentityServer4.Admin.Common project

### ISSUE THREAD

**Issue by cerginio** [skoruba/IdentityServer4.Admin#64]
Add IdentityServer4.Admin.Common project for common interfaces, constants, DTOs, AppSettings.
Move non specific for App, DAL and BLL constants and DTOs to Common project.

Might be must have refactoring for #56

**Comment by skoruba** [comment]
Add `Shared` project in `feature/extensible-aspnet-identity`.

**Comment by skoruba** [comment]
Done on master - #99
