### ISSUE TITLE
how to send new created cliam to project use skoruba / IdentityServer4.Admin?

### ISSUE THREAD

**Issue by dantemayson** [skoruba/IdentityServer4.Admin#641]
hi ,i create new claim for admin,in project i cant see created(other) claims
![2020-06-24 11_14_54-Window](https://user-images.githubusercontent.com/12047513/85510260-5fb85480-b60c-11ea-8b67-8a5d5f9d073d.png)

claims in project use skoruba / IdentityServer4.Admin
![2020-06-24 11_19_32-Window](https://user-images.githubusercontent.com/12047513/85510547-bfaefb00-b60c-11ea-8006-d869e3da948a.png)

how i can add (other) claim to claims in project
thanks for read my Question

**Comment by moemura** [comment]
**Configure Resource**
Go to Admin UI.
Click Clients/Resources -> Identity Resources.
Click Add Identity Resource.
Fill the form bellow. 
![image](https://user-images.githubusercontent.com/26450395/89842228-3e50ff00-db9f-11ea-885c-fc67ceeb39b7.png)
insert resource name and claims then Save.

**Configure Scope**
Click Clients/Resources -> Clients.
Edit Client
Select Basic Tab
Add additional scope / resource name
![image](https://user-images.githubusercontent.com/26450395/89842610-612fe300-dba0-11ea-9b35-dca57bb95396.png)

**Configure Client SourceCode**

`options.GetClaimsFromUserInfoEndpoint = true;`
`options.Scope.Add("kdtambahan");`
` options.ClaimActions.MapUniqueJsonKey("kdpelanggan", "kdpelanggan"); //map single claim`
` //options.ClaimActions.Add(new MapAllClaimsAction()); // map all claims`

in case of I'm missing something [https://code-maze.com/identityserver4-authorization/](https://code-maze.com/identityserver4-authorization/)

I think this issue should be sticky or linked from readme.

**Comment by dantemayson** [comment]
thanks
