### ISSUE TITLE
Is it  possible to add additional details for user?

### ISSUE THREAD

**Issue by luvssti** [skoruba/IdentityServer4.Admin#646]
Hi!

I would like to add additional information of users under Identity/UserProfile is it possible and how?

Thank You!

**Comment by luvssti** [comment]
Hi Mr. Skoruba! I already added the additional data but how to add save it in the database?

Thank You!
![image](https://user-images.githubusercontent.com/3644600/86770237-f6602900-c082-11ea-9756-c85b8a35d13d.png)

**Comment by luvssti** [comment]
Hi Mr. Skoruba!

Thanks for sharing your code. I've learned a lot. I already figured out how to add and save it in my database.

Thank You!

**Comment by skoruba** [comment]
Hi @luvssti - thank you for your feedback, that you solved your use case. I will add guide for this. 😊

**Comment by luvssti** [comment]
Hi Mr. @skoruba looking forward toit. It will be a big help to have a guide. Thank You very much!

**Comment by bassely** [comment]
@luvssti  can you share the modification you have done to add these fields?

**Comment by luvssti** [comment]
> @luvssti can you share the modification you have done to add these fields?

Hi sorry for the late reply.
 do you still need my help?
