### ISSUE TITLE
None of Picker controls are displaying data

### ISSUE THREAD

**Issue by kaleshanagineni** [skoruba/IdentityServer4.Admin#647]
### Question
seems like  the picker control below is not displaying any scopes in UI. Please let me know what I'm missing here
	<picker id="AllowedScopesItems" multiple-select="true" min-search-text="2"
				        selected-items="@Model.AllowedScopes" url="@Url.Action("SearchScopes","Configuration")?scope"
				        search-input-placeholder="@Localizer["PickerSearchItemPlaceholder"].Value"
				        selected-items-title="@Localizer["PickerSelectedItemsTitle"].Value" 
				        search-result-title="@Localizer["PickerSearchResultTitle"].Value"
				        suggested-items-title="@Localizer["PickerSuggestedItemsTitle"].Value" 
				        no-item-selected-title="@Localizer["PickerNoItemSelectedTitle"].Value" 
				        show-all-items-title="@Localizer["PickerShowAllItemsTitle"].Value"
				        item-already-selected-title="@Localizer["PickerItemAlreadySelectedTitle"].Value">
				</picker>
### Relevant parts of the log file

```
   <log goes here>
```

**Comment by kaleshanagineni** [comment]
As dig in more I found out picker component in knockout is not receiving any data from  MVC

**Comment by skoruba** [comment]
It looks like that your taghelpers are not loaded correctly. Please, check if you have correctly loaded taghelpers in your solution.
Thanks.

**Comment by skoruba** [comment]
I am closing now, feel free reopen. Thank you
