### ISSUE TITLE
Forgot password fails on email validation

### ISSUE THREAD

**Issue by aznarepse** [skoruba/IdentityServer4.Admin#664]
When trying to reset the password from the Forgot password view,
/Account/ForgotPassword fails if an email on the form **name@domain.co.uk** is introduced with the following error:
An unhandled exception occurred while processing the request.
FormatException: The specified string is not in the form required for an e-mail address.

System.Net.Mail.MailAddressParser.ReadCfwsAndThrowIfIncomplete(string data, int index)
System.Net.Mail.MailAddressParser.ParseDomain(string data, ref int index)
System.Net.Mail.MailAddressParser.ParseAddress(string data, bool expectMultipleAddresses, ref int index)
System.Net.Mail.MailAddressParser.ParseAddress(string data)
System.Net.Mail.MailAddress..ctor(string address, string displayName, Encoding displayNameEncoding)
System.Net.Mail.Message..ctor(string from, string to)
System.Net.Mail.MailMessage..ctor(string from, string to)
...

It works well with emails **name@domain.com**

**UPDATE**
Please see comment below. This comment is misleading on the error; apologies.

**Comment by aznarepse** [comment]
My previous comment is misleading. Unfortunately, I made some wrong conclusions... late and tired I am afraid...

It throws the exception always, regardless of the email provided. I have looked at the code in the sender now and I can see that the function SendEmailAsync gets the From address from the settings:

`var from = String.IsNullOrEmpty(_configuration.From) ? _configuration.Login : _configuration.From;`

For some reason my deployment is not reading the SMTP settings and both the _configuration.Login and _configuration.From are null. Incidentally, _configuration.From, seems to be always null since the SmtpSettings model does not implement it.

**Comment by aznarepse** [comment]
All right, further debugging here:
The problem is that the code is using the SmtpSettings.Login as 'From' email address and it is hence assuming that it is an email.
However, in my case, the user login name for SMTP is not an email.
Then, if I use an email as user name I have a different exception:

```
Win32Exception: GSSAPI operation failed with error - Unspecified GSS failure. Minor code may provide more information (Cannot find KDC for realm "geared.co.uk").

    System.Net.Security.NegotiateStreamPal.AcquireCredentialsHandle(string package, bool isServer, NetworkCredential credential)
    System.Net.NTAuthentication.Initialize(bool isServer, string package, NetworkCredential credential, string spn, ContextFlagsPal requestedContextFlags, ChannelBinding channelBinding)
    System.Net.Mail.SmtpNegotiateAuthenticationModule.Authenticate(string challenge, NetworkCredential credential, object sessionCookie, string spn, ChannelBinding channelBindingToken)
    System.Net.Mail.SmtpConnection.SetContextAndTryAuthenticate(ISmtpAuthenticationModule module, NetworkCredential credential, ContextAwareResult context)
    System.Net.Mail.SmtpConnection.GetConnection(string host, int port)
    System.Net.Mail.SmtpTransport.GetConnection(string host, int port)
    System.Net.Mail.SmtpClient.GetConnection()
    System.Net.Mail.SmtpClient.Send(MailMessage message)
```
Which seems the same as this [https://github.com/dotnet/runtime/issues/2174](url), since I am using the solution in linux containers.

**Comment by aznarepse** [comment]
The code in the comment above for SendEmailAsync is from the development branch.
The code in the solution that I am using is:
```
public Task SendEmailAsync(string email, string subject, string htmlMessage)
        {
            _logger.LogInformation($"Sending email: {email}, subject: {subject}, message: {htmlMessage}");
            try
            {
                var mail = new MailMessage(_configuration.Login, email);
                mail.IsBodyHtml = true;
                mail.Subject = subject;
                mail.Body = htmlMessage;
                _client.Send(mail);
                _logger.LogInformation($"Email: {email}, subject: {subject}, message: {htmlMessage} successfully sent");
                return Task.CompletedTask;
            }
            catch (Exception ex)
            {
                _logger.LogError($"Exception {ex} during sending email: {email}, subject: {subject}");
                throw;
            }
        }
```
Which explicitly uses the Login as From..

**Comment by skoruba** [comment]
Thank you for your feedback on this. Please tame a loom at dev branch, there was added new field From for Smtp configuration.

**Comment by skoruba** [comment]
Fixed in master, thanks😊
