### ISSUE TITLE
How to I access to the Admin?

### ISSUE THREAD

**Issue by ngaisteve1** [skoruba/IdentityServer4.Admin#667]
### Question
I could start all the 3 projects successfully. All 3 projects can be loaded:

- http://localhost:5001/swagger/index.html
- http://localhost:5000/ (Client)
- http://localhost:9000/ (Admin)

 I access to http://localhost:5000/ (Client) and register new account and it is inserted into database. But for Admin, it first goes to http://localhost:9000/ and later on redirected to http://localhost:5000/Account/Login?ReturnUrl=xxx

So, my question is how do I then access to the Admin login page at http://localhost:9000/? Once, I could see this, I believe I should use the username and password at identitydata.json to login, right?

### Relevant parts of the log file

```
   <log goes here>
```

**Comment by skoruba** [comment]
Yes, for first login - please use your credentials from identitydata.json.
Thanks

**Comment by skoruba** [comment]
I am closing this issue, feel free to reopen. Thnx
