### ISSUE TITLE
After login does not redirect to Admin page

### ISSUE THREAD

**Issue by luvssti** [skoruba/IdentityServer4.Admin#674]
Hi Mr. @skoruba,

I don't know if this is a bug. It was working fine yesterday and did not change any in the settings or configuration. Then suddenly today upon logging in it doesn't redirect to the admin page. Do you have any idea regarding this issue?

Thank You!

**Comment by skoruba** [comment]
Hi @luvssti 
do you get any errors?

**Comment by luvssti** [comment]
Hi Mr. @skoruba ,

It is working with Microsoft Edge but not in chrome and I also try it on other computer it is working on both browser.. Maybe my google chrome got some problem. I will try to re-install it.

Thank You for the immediate response.

**Comment by skoruba** [comment]
Could you please switch to dev branch and test it latest RC2? Thanks.

**Comment by luvssti** [comment]
Hi Mr. @skoruba,

Yes I will try it. Thanks!

**Comment by phorozan** [comment]
Seems that there was an update on Chrome which blocks cross-site cookies to be set. The error message from the Developer console: "Mark cross-site cookies as Secure to allow setting them in cross-site contexts".

**Comment by samBiggs32** [comment]
Has anyone had any luck with this so far? Also keen for a solution

**Comment by skoruba** [comment]
> Could you please switch to dev branch and test it latest RC2? Thanks.
> https://github.com/skoruba/IdentityServer4.Admin/tree/dev
Please, try it in dev branch. 😊

**Comment by phorozan** [comment]
The master branch works with Https. So using the dev branch which provides local Https via nginx should be OK!

**Comment by samBiggs32** [comment]
> > Could you please switch to dev branch and test it latest RC2? Thanks.
> > https://github.com/skoruba/IdentityServer4.Admin/tree/dev
> > Please, try it in dev branch. 😊

Dev branch is fine, thanks!

**Comment by skoruba** [comment]
Thanks guys for feedback

**Comment by skoruba** [comment]
Fixed in master, thanks 👍🏼
