### ISSUE TITLE
Cannot do login with usename/password in identitydata.json

### ISSUE THREAD

**Issue by fuentco** [skoruba/IdentityServer4.Admin#676]
Hello, Congratulations for the great project.

I am testing the project but cannot do login with parameter configured in identitydata.json. The username and password should be in Users table or the initial admin login info is in memory?

Thanks

**Comment by thunguyen1012** [comment]
You can switch to the dev branch and login successfully.

**Comment by fuentco** [comment]
> You can switch to the dev branch and login successfully.

Great. Now I can login. Thanks.
