### ISSUE TITLE
Register User

### ISSUE THREAD

**Issue by cvnfactory** [skoruba/IdentityServer4.Admin#677]
Hello

Thank you for sharing your work.

There is an error in the register form

https://localhost:44310/Account/Register

1. The button has not the correct text

2. When the user tries to register there is an error:

![image](https://user-images.githubusercontent.com/48703068/89970536-a72b8c00-dc1e-11ea-8d98-5b930a2f06eb.png)

Thanks in advance

**Comment by skoruba** [comment]
Hi,
What text do you see in button?
Thanks

**Comment by cvnfactory** [comment]
Hello

Thanks for the response,

it looks like this (my culture is es-CO)

[cid:59b8cfc2-3233-4f1e-8d27-35ad89335af5]

but in the login it is ok


[cid:45bcd815-019b-4fbc-b40a-ecbbfea66be0]
________________________________

**Comment by skoruba** [comment]
Could you provide screen? Thanks

**Comment by skoruba** [comment]
Thanks for reporting, there is a bug, I will fix it.

**Comment by cvnfactory** [comment]
Thank you

**Comment by Walid-Abdulrazik** [comment]
I have a proposed fix

https://github.com/skoruba/IdentityServer4.Admin/pull/698

sorry for the repeated issue https://github.com/skoruba/IdentityServer4.Admin/issues/697 , i did not see this issue untill i posted mine ...

**Comment by skoruba** [comment]
Thank you! Fixed in 1.0.0-rc3 #703
