### ISSUE TITLE
beginner’s question , admin web site gets redirected with error.

### ISSUE THREAD

**Issue by GitMW** [skoruba/IdentityServer4.Admin#679]
### Question
Hi 
I was hoping someone could help, this is a beginner’s question, 
When I try and run the three web site, two get displayed, the api and the Id server, but the Admin website fails to log in and gets redirected to https://localhost:44310/home/error?errorId=.... error Unauthorized_Client.
Looking in the log for STS.Idenity service it has the following error.
Unknown client or not enabled AdministratorClientId not found.
The website database is being created and populated.

I create a solution from the dot net template.
I have all three services running, vs 2019 
If is probably something I missed, but just not making any headway on this problem.

### Relevant parts of the log file

```
  2020-08-13 11:05:49.536 +01:00 [ERR] Unknown client or not enabled: AdministratorClientId
{"ClientId":null,"ClientName":null,"RedirectUri":null,"AllowedRedirectUris":null,"SubjectId":"anonymous","ResponseType":null,"ResponseMode":null,"GrantType":null,"RequestedScopes":"","State":null,"UiLocales":null,"Nonce":null,"AuthenticationContextReferenceClasses":null,"DisplayMode":null,"PromptMode":null,"MaxAge":null,"LoginHint":null,"SessionId":null,"Raw":{"client_id":"AdministratorClientId","redirect_uri":"https://localhost:44303/signin-oidc","response_type":"code","scope":"openid profile email roles","code_challenge":"MXzbjshgPlCKrzBNzdMNIBaS5peNaLkayayom5ppgCk","code_challenge_method":"S256","response_mode":"form_post","nonce":"637329099495137717.NTk1ODhiYjgtOWYwOS00MDY5LTg0NDItYTI2ZDkyNTAyNzA5MTYzY2VlMDEtYTJiOC00ZjZiLTg3YjUtOWI0YTgzODQyM2U5","state":"CfDJ8K9mjW-1JxdKk2buPBSoVbfgStDBW5f3IyrIwQRW4Y0XRjE0OXlQ9dv1cr-A6hKYQDumQETt8QCA9LfIwVinWQwt5hzohvCuadiLxSmwDGBaZq1jp4CIdaWEBxVt2qALOk2TpwJm4q5S7lj4aMCt7UUZtpIuzncwK4Z3fPubt8Z8tk29ljGS3b0F3UzVa7if0o_Zg51_QYiARh-dDW8z9Fht24J8FvF6dtPx-wm44CX14sk_m6gqM6zNby0SccSnROeopDfdhIkXUdPqHikvJn-NL1bH2Piq4vvp-zD-BJknQFPw4JR2fGP4yngXd-XzvcE8BMiXiKpgDhg8I5rcLHPK92C5mLBvE6bkgB9d2piAh1EGi-zJT73eBPbZpgmYCA","x-client-SKU":"ID_NETSTANDARD2_0","x-client-ver":"5.5.0.0"},"$type":"AuthorizeRequestValidationLog"}
2020-08-13 11:05:49.536 +01:00 [ERR] Request validation failed

```

**Comment by moemura** [comment]
Did you run => dotnet run /seed on Admin project or uncomment DbMigrationHelpers.EnsureSeedData(host).
It's in the readme.
Most likely it's not seeded.

**Comment by skoruba** [comment]
Now it is possible to configure seed and db migrations from appsettings.json

**Comment by GitMW** [comment]
It was a database permissions issue in the end. Thank you for your help,

**Comment by skoruba** [comment]
Thank you for your feedback.
