### ISSUE TITLE
Forgot your password fails when RequireUniqueEmail is false

### ISSUE THREAD

**Issue by ahmedabdelkafy** [skoruba/IdentityServer4.Admin#681]
### When we set RequireUniqueEmail = false in the appsettings.json and allow users to repeat the email with different accounts then "Forgot your password" page with "Email" option not sending any email.
I think "User Name" as textbox must added with the "Email" Textbox in this case or email option must be disabled.

### To Reproduce
1- Change RequireUniqueEmail in the appsettings.json of Admin UI
2- register more than one account with the same email
3- try forgot password from the login page
4- select Email option
5- enter the repeated email

**Comment by skoruba** [comment]
@ahmedabdelkafy - thanks for reporting this issue, I will check it.

**Comment by skoruba** [comment]
Thank you! Fixed in 1.0.0-rc3 #703
