### ISSUE TITLE
AutoMapperMappingException: Missing type map configuration or unsupported mapping.

### ISSUE THREAD

**Issue by maqeelqureshi** [skoruba/IdentityServer4.Admin#689]
Following Mapping types are missing, 

UserIdentityRoleClaim -> RoleClaimDto`1

PagedList`1 -> IdentityRoleClaimsDto

PagedList`1 -> IdentityRoleClaimsDto

### To Reproduce
Clone code, 
Run migration and seed
Add Role claims

**Comment by skoruba** [comment]
Thanks for reporting this issue, did you faced this issue with latest version from master?
Thanks

**Comment by maqeelqureshi** [comment]
> 
> 
> Thanks for reporting this issue, did you get this exception with latest version from master?
> Thanks

Yes, its is producible on master branch.

**Comment by skoruba** [comment]
Ok, let me check it. Can you send a PR with your fix? Thanks

**Comment by maqeelqureshi** [comment]
Not sure how to create pull request from source-tree.

Adding following mapping to IdentityServer4.Admin\src\Skoruba.IdentityServer4.Admin.BusinessLogic.Identity\Mappers\IdentityMapperProfile.cs resolves this issue,
            CreateMap<UserIdentityRoleClaim, RoleClaimDto<TKey>>(MemberList.Source);
            CreateMap<RoleClaimDto<TKey>, UserIdentityRoleClaim>(MemberList.Source);
            CreateMap<UserIdentityRoleClaim, RoleClaimDto<TKey>>(MemberList.Destination);

**Comment by skoruba** [comment]
Oki, I will add it manualy. Thank you @maqeelqureshi  👍

**Comment by fuentco** [comment]
Hello,

Could you point me in the direction to solve this issue? I see that UserIdentityRoleClaim class (Skoruba.IdentityServer4.Admin.EntityFramework.Shared.Entities.Identity) is empty.

Regards,

erick

**Comment by zinkpad** [comment]
Hi,

I added these lines to IdentityMapperProfile.cs to resolve automapper exceptions with UserLoginInfo -> UserProviderDto (when you list user providers) and RoleClaimDto exceptions:

`            // Fix user providers error
            CreateMap<UserLoginInfo, UserProviderDto<TKey>>(MemberList.Destination);

            // Fix role claims
            CreateMap<IdentityRoleClaim<TKey>, RoleClaimDto<TKey>>(MemberList.Source)
                .ForMember(x => x.ClaimId, opt => opt.MapFrom(src => src.Id));
            CreateMap<RoleClaimDto<TKey>, IdentityRoleClaim<TKey>>(MemberList.Source)
                .ForMember(x => x.Id, opt => opt.MapFrom(src => src.ClaimId));
            CreateMap<IdentityRoleClaim<TKey>, RoleClaimDto<TKey>>(MemberList.Destination)
                .ForMember(x => x.ClaimId, opt => opt.MapFrom(src => src.Id));
            // end fix role claims`

I think mappings needs a review.

**Comment by skoruba** [comment]
Thank you! Fixed in 1.0.0-rc3 #703
