### ISSUE TITLE
Error deleting logs and auditlogs

### ISSUE THREAD

**Issue by zinkpad** [skoruba/IdentityServer4.Admin#690]
On dev branch I cant delete auditlogs and logs by date because datepicker locale for spanish language 'es' is not included in gulpfile.js and dateformat is in english format, but the AspNetCore culture is established  as spanish, then the viewmodel cant be validated on controller and always show an error due wrong date format.

To avoid this issue I just added this line to gulp file:

function processScripts() {
    return gulp
        .src([....]
**'./node_modules/bootstrap-datepicker/dist/locales/bootstrap-datepicker.es.min.js',**

[...]

Thanks!!

**Comment by skoruba** [comment]
Thanks for reporting this issue, could you please send a PR with this fix?

**Comment by zinkpad** [comment]
Yes, sure... you can check it at https://github.com/skoruba/IdentityServer4.Admin/pull/691

Thanks.

**Comment by skoruba** [comment]
Thank you! Fixed in 1.0.0-rc3 #703
