### ISSUE TITLE
API Error : Missing type map configuration

### ISSUE THREAD

**Issue by berajkumar12** [skoruba/IdentityServer4.Admin#693]
### Describe the bug
User/PostChangePassword,
on this line: 

var userChangePasswordDto = _mapper.Map < TUserChangePasswordDto > (password);

UserChangePasswordApiDto < TUserDtoKey > to UserChangePasswordDto < TUserDtoKey >

### Relevant parts of the log file

AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.

Mapping types:
UserChangePasswordApiDto`1 -> UserChangePasswordDto`1
Auth.AutoSec.Admin.Api.Dtos.Users.UserChangePasswordApiDto`1[[System.Guid, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]] -> Skoruba.IdentityServer4.Admin.BusinessLogic.Identity.Dtos.Identity.UserChangePasswordDto`1[[System.Guid, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]

**Comment by skoruba** [comment]
I will check it, are you able to send a PR? 
Thanks

**Comment by berajkumar12** [comment]
Not able to find fix.

**Comment by skoruba** [comment]
Oki, I will find it and fix it. Thanks for reporting

**Comment by berajkumar12** [comment]
I temporarily fixed on my application by creating UserChangePasswordDto < TUserDtoKey > object directly instead of Mapper. Please do share fix for mapper.
or
tips to fix where i can raise PR

**Comment by skoruba** [comment]
Please, check master branch - I tested this feature and everything works great.
