### ISSUE TITLE
Bug:  Log paging must show reasonable amount of page links

### ISSUE THREAD

**Issue by cerginio** [skoruba/IdentityServer4.Admin#70]
Log paging shows all existing links - NOK

![image](https://user-images.githubusercontent.com/2261603/44785465-a916f480-ab99-11e8-91d2-5ed5923ec694.png)

**Comment by skoruba** [comment]
I'll fix it. 

Thanks for reporting!

**Comment by skoruba** [comment]
Fix it. Please, you can try it from `dev` branch.
Thx.

**Comment by skoruba** [comment]
Done on `master`.
