### ISSUE TITLE
Projects purpose

### ISSUE THREAD

**Issue by DavidDury** [skoruba/IdentityServer4.Admin#704]
Hi,

Thanks a lot for this excellent work. I am trying to learn more and more about IdentityServer and this whole concept so please bear with me. I have some hard time understanding the purpose of the following projects:
- Skoruba.IdentityServer4.Admin.Api
- Skoruba.IdentityServer4.Admin.Api
- Skoruba.IdentityServer4.STS.Identity

Can somebody clarify that to me?

**Comment by skoruba** [comment]
https://github.com/skoruba/IdentityServer4.Admin#solution-structure Please check solution structure

**Comment by DavidDury** [comment]
Sorry for wasting your time mate! My fault here!

**Comment by DavidDury** [comment]
Solved

**Comment by skoruba** [comment]
No problem, if you will have any issue, let me know.
