### ISSUE TITLE
How to get the username in access token

### ISSUE THREAD

**Issue by KiritoStudio** [skoruba/IdentityServer4.Admin#705]
### Question

Hi, I'm new in identityserver4. My request is like the following below:

![image](https://user-images.githubusercontent.com/553215/93091585-e42ce780-f6d0-11ea-8cfc-7c74c70c4a8c.png)

I know the sub is the userid, but I could not get the username. Is there anyway I can get the username or even email or mobile in access token without send http request to the userinfo endpoint?

**Comment by vicentt** [comment]
you can add your custom claims to your access token. Something like this
[https://community.auth0.com/t/is-there-a-way-to-include-username-as-a-claim-using-resource-owner-password-grant-access-tokens/18769](url)
