### ISSUE TITLE
CORS allow * not working

### ISSUE THREAD

**Issue by RioloGiuseppe** [skoruba/IdentityServer4.Admin#713]
Using `*`or `'*'` as Allowed Cors Origins in Token tab in client configuration i have in browser:

`Access to XMLHttpRequest at 'https://login.********.com/connect/token' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

![image](https://user-images.githubusercontent.com/6390660/94361687-8c21b800-00b6-11eb-9942-aba65dadb998.png)

Some ideas?

**Comment by skoruba** [comment]
I think you need specify urls. The star is not valid in this case.

Thank

**Comment by RioloGiuseppe** [comment]
Thanks a lot!
