### ISSUE TITLE
Add Delegation Flow/Grant Type

### ISSUE THREAD

**Issue by martinussuherman** [skoruba/IdentityServer4.Admin#716]
**Is your feature request related to a problem? Please describe.**
- I have front end client that calls an API. This API (API 1) needs to call another API (API 2) on behalf of the interactive user . This will require a Delegation Grant Type for API 1 to call API 2.

**Describe the solution you'd like**
- Enable the use of Delegation Grant Type for client(s).  Reference: https://identityserver4.readthedocs.io/en/latest/topics/extension_grants.html

**Describe alternatives you've considered**
- None

**Additional context**
- None

I've submit PR #717 for this issue. Please kindly review.

**Comment by skoruba** [comment]
Merged and prepared for RC4. Thank you 😊👍🏼

**Comment by martinussuherman** [comment]
Closing since already merged to dev branch. Thanks @skoruba
