### ISSUE TITLE
Heads up: Future of IdentityServer

### ISSUE THREAD

**Issue by DaleyKD** [skoruba/IdentityServer4.Admin#720]
https://leastprivilege.com/2020/10/01/the-future-of-identityserver/

IdentityServer 5 will be licensed.  I just thought you should know in case you missed it.

**Comment by skoruba** [comment]
@DaleyKD - Thank you for your info.

**Comment by skoruba** [comment]
We discuss this topic here #718

**Comment by DaleyKD** [comment]
-eyeroll- at myself.  I TRIED to look before I logged.

**Comment by skoruba** [comment]
No problem. 👍
