### ISSUE TITLE
Why are there EnvironmentVariables in the web.config in project Skoruba.IdentityServer4.Admin?

### ISSUE THREAD

**Issue by sgebhardt** [skoruba/IdentityServer4.Admin#728]
### Question
I have set the ASPNETCORE_ENVIRONMENT variable system-wide on a server. And I was surprised that this was not used.
I found out that this is set to "Development" in the web.config. Is there a reason for that?

The other two environment variables also seem to be unnecessary in the web.config.

### Relevant parts of the log file

https://github.com/sgebhardt/IdentityServer4.Admin/commit/566e610aedcd9ec54ee4ca5b62bf7789ae7648db

**Comment by ioxFR** [comment]
Hi 

I think it's used for local execution during development but not used in production environment.
As application configurations are stored in appsettings...

**Comment by sgebhardt** [comment]
I created #732 to remove these environment variables.

**Comment by skoruba** [comment]
Not sure, I think it is some old default scaffolded web.config. Let me check it.

**Comment by skoruba** [comment]
PR merged, thanks 👍
