### ISSUE TITLE
client_secret in Skoruba IdentityServer4 Admin Api

### ISSUE THREAD

**Issue by hoseinipeyrov** [skoruba/IdentityServer4.Admin#740]
### Question
I just made a clone of the repository. I've left all settings by default and every thing work well.
In 'Skoruba IdentityServer4 Admin Api' what should I write in 'client_secret' input textbox?

**Comment by berendhaan** [comment]
I guess you mean the interface Swagger provides for authenticating? You can proceed without a secret.
The client is configured to not need a (valid) client secret.
