### ISSUE TITLE
Localization language change clears QueryString

### ISSUE THREAD

**Issue by zvasilius** [skoruba/IdentityServer4.Admin#742]
I use some query params for user registration or other purposes:
http://localhost:5000/Controller/Action?queryParam=value

After user changed localization language to different, SelectLanguage.cshtml posts
var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "/" : $"{Context.Request.Path.Value}";
back, page will be re-rendered, but without query params:
http://localhost:5000/Controller/Action

Can be easy fixed by changing SelectLanguage.cshtml to this one:
var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "/" : $"{Context.Request.Path.Value}**{Context.Request.QueryString}**";

I can create PR with fix, just not sure if it's good idea.

**Comment by skoruba** [comment]
@zvasilius - thank you for reporting this issue, for sure, please you can make a PR. 👍
