### ISSUE TITLE
MVC/API different projects

### ISSUE THREAD

**Issue by ruzanowski** [skoruba/IdentityServer4.Admin#756]
What reason lays behind the split API project (Skoruba.IdentityServer4.Admin) and MVC project (Skoruba.IdentityServer4.Admin.Api) and STS? I think I might need to join these three projects altogether to have a single point of deployment instead of 3. 

Do you think it's reasonable or it would have limitations? On the other hand, I'd not like to do it, hence it leads to discrepancies between the master branch and my forked solution and future problems with applying patches.

Best regards,
Sebastian

**Comment by ruzanowski** [comment]
Okay, I've seen that we have a script that merges every project into one solution.

**Comment by vl-bwalocha** [comment]
Hi, have you merged successfully the API, STS and Admin into single solution with 3 areas?
I did separated `IHostingStartup` in each area but have a problem with routing.

**Comment by ruzanowski** [comment]
Hey,

No. I was not merging API, STS, and Admin after all, as they do
different responsibilities, however, you can put what issue you struggle
with and I'd try to help you out.


Best regards,
Sebastian

śr., 24 lut 2021 o 21:32 vl-bwalocha <notifications@github.com> napisał(a):
