### ISSUE TITLE
Unable to assign multiple scopes to a client

### ISSUE THREAD

**Issue by mjisaak** [skoruba/IdentityServer4.Admin#77]
I try to add multiple scopes to a client but I can only add one:

![image](https://user-images.githubusercontent.com/8446917/45821169-d5c9b200-bce8-11e8-955c-d1211fa7984e.png)

Any suggestions?

**Comment by skoruba** [comment]
I'll check it. Thanks!

**Comment by mjisaak** [comment]
Thanks a lot skoruba, looking forward to hear from you. BTW, did you noticed that Identity Server will be directly integrated to #aspnetcore 2.x ? Here is announcement: https://twitter.com/leastprivilege/status/1042311196924432384
Your awesome admin ui will probably get much more users ;-). Well done!

**Comment by skoruba** [comment]
Yes, it is great announcement. 👍 

I will be happy, if this project helps others. :-)

**Comment by skoruba** [comment]
@mjisaak I can't reproduce this issue. Tested in IE, Chrome, FF. :) 
What happens if you click on the "Profile" in the section "Search Result"?
 
Thanks!

**Comment by mjisaak** [comment]
Then one scope gets added. But as soon I try to add another scope, the previously selected scope gets replaced: 

![adding_scopes](https://user-images.githubusercontent.com/8446917/45828707-83dd5800-bcf9-11e8-96ea-7567dba6d46e.gif)

**Comment by mjisaak** [comment]
Yes, I get plenty of the following java script errors, but I don't think that they cause the issue:

`2:1 Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAGVUABEAAAAAxuQAAQABAAAAAAAAAAAAAAAAAAAAAAAAAABHREVGAAABgAAAAC4AAAA0ArgC7UdQT1MAAAGwAAAQ6AAALgxKsqRTR1NVQgAAEpgAAAH3AAAELqI5y+RPUy8yAAAUkAAAAE8AAABgaGyBu2NtYXAAABTgAAABlAAAAkQkRATXY3Z0IAAAFnQAAABeAAAAugDsQf1mcGdtAAAW1AAABZcAAAvNb3/BHGdhc3AAABxsAAAACAAAAAgAAAAQZ2x5ZgAAHHQAAEApAAB3CtbiupxoZWFkAABcoAAAADYAAAA2BkubWWhoZWEAAFzYAAAAIAAAACQHFARfaG10eAAAXPgAAAI6AAAEEk4TN4Nsb2NhAABfNAAAAhIAAAISiLhpam1heHAAAGFIAAAAIAAAACACigzgbmFtZQAAYWgAAACUAAABHhQGLdJwb3N0AABh/AAAAq4AAASRk5y6n3ByZ...QxUajCCFt4p9HP4fzdSWs2XhWl5HvJazrIrFUyB0l5dpqcW10lV2wukjMLuAvyMHNiYpgPsrCVXZDKrkpll6UWkh7kABVAFVCDe7UFmxagDegA+hLHRPbqtMo7ZHCpKdT6tPGXybzo0+RXBLoPZt1tELcXxCmAAyZwYTJvdDFZKnDER44X2451rDqCyunIsRWvLSx6wnWqwPj/uX5/KuEy6DL0z6A/Fn79VihxMFJsrlAFy4DpZOcvNlMeNp+BRDLj0r+XFdRxdSNSNxiI/AL3ojKdAAB4AWPw3sFwIihiIyNjX+QGxp0cDBwMyQUbGdictkUwWDAwsDJogTgOPN4c9iz6bMos4iysHFChUDZXJnMWTSZZJrAQt9M+YQYBBh4GTgY2kEZOoJiA0z4GBxiEiDEzuGxUYewIjNjg0BGxkTnFZaMaiLeLo4GBkcWhIzkkAqQkEggceHw5HFkM2VRZJFlYebR2MP5v3cDSu5GJwWUDW9xG1hQXAFAmKZU=' because it violates the following Content Security Policy directive: "font-src 'self' https://fonts.googleapis.com/ https://fonts.gstatic.com/"`.

I am using the latest version of Chrome (Version 69.0.3497.100 - 64 Bit).  I pulled the sources a week ago, I can try to use the latest version later too.

**Comment by mjisaak** [comment]
I just tried the latest version and that seems to work, I will check whether I changed something in the code but I think you can close this.

**Comment by skoruba** [comment]
Maybe missing property `multiple-select="true"`? 

Anytime, please, if you have any issues, let me know. :)

Thanks!
