### ISSUE TITLE
How to use Admin with exist IdentityServer4

### ISSUE THREAD

**Issue by ekjuanrejon** [skoruba/IdentityServer4.Admin#770]
### Question
Hello, How to use Admin with an existing IdentityServer4

**Comment by pfaustinopt** [comment]
I don't if this link [Follow these steps for setup project to use existing IdentityServer4 and Asp.Net Core Identity](https://github.com/skoruba/IdentityServer4.Admin/blob/master/docs/Configure-Administration.md)  that shows up on [How to configure the Administration - IdentityServer4 and Asp.Net Core Identity](https://github.com/skoruba/IdentityServer4.Admin#how-to-configure-the-administration---identityserver4-and-aspnet-core-identity) is related to your question.

**Comment by skoruba** [comment]
Hi guys, yeah, currently following links above are the guide which I have. 👍 
I will work on simplification of distribution of whole UI, I would transfer UI into nuget package - it would be easier way how to upgrade UI part. 😊
