### ISSUE TITLE
Some const field can read *.settings.json

### ISSUE THREAD

**Issue by mperk** [skoruba/IdentityServer4.Admin#78]
Some information changes in environments. 
For example; 
       
        public const string IdentityAdminCookieName = "IdentityServerAdmin";        
        public const string IdentityAdminRedirectUri = "http://localhost:9000/signin-oidc";
        public const string IdentityServerBaseUrl = "https://devauth.thyteknik.com.tr";
        public const string IdentityAdminBaseUrl = "http://localhost:9000";

The application can take this changing information from the setting.json file.
If you check the issue, I can do it.

**Comment by skoruba** [comment]
Please, take a look here: https://github.com/skoruba/IdentityServer4.Admin/tree/feature/extensible-aspnet-identity - on `feature/extensible-aspnet-identity` branch - I moved some consts into `settings.json` - it's based on @cerginio PR. I'll merge these settings.json changes into `master`.

**Comment by mperk** [comment]
Ok good job, Thank you.

**Comment by skoruba** [comment]
Done on master - #99
