### ISSUE TITLE
It's possible to register user while it's disabled in configurations

### ISSUE THREAD

**Issue by parrot409** [skoruba/IdentityServer4.Admin#783]
### Describe the bug
There is a check to see if registration is enabled [here](https://github.com/skoruba/IdentityServer4.Admin/blob/master/src/Skoruba.IdentityServer4.STS.Identity/Controllers/AccountController.cs#L582), But it's only for GET requests. There isn't any check for POST requests.

### To Reproduce
Send POST request with required parameters to `/account/Register`.

**Comment by skoruba** [comment]
Thanks for reporting this issue! I will fix it. 👍
