### ISSUE TITLE
Client secret validation failed for client

### ISSUE THREAD

**Issue by wv7cherry** [skoruba/IdentityServer4.Admin#786]
I have a client with client id and client secret like this:
- Client id: test_client_secret
- Client secret : 1y77og3EfuqzQ50JeDAtSX6tZvCenW2ADGd+NEcv8a0= (SharedSecret)

When I try to get token by authorization_code, the server returns an error message like this:
- Postman respone:
![image](https://user-images.githubusercontent.com/76938198/105279909-3203b000-5bdb-11eb-9ff1-ff2791850946.png)
- Debug log:
![image](https://user-images.githubusercontent.com/76938198/105279940-421b8f80-5bdb-11eb-88ea-fbfe9c59d40d.png)
- My request in Postman:
![image](https://user-images.githubusercontent.com/76938198/105280067-8444d100-5bdb-11eb-9393-1a6d28a569dd.png)

Can you show me where I went wrong?

**Comment by wv7cherry** [comment]
I used secret which has been hashed on the UI :))

**Comment by Kolyanuss** [comment]
Hi, I encountered the same error. Can you describe in detail how you fixed it?
