### ISSUE TITLE
Updating to latest version after creating from template

### ISSUE THREAD

**Issue by daniel-tejeda** [skoruba/IdentityServer4.Admin#796]
### Question
When installing from template, is there an easy way to get the latest changes from the repo? wondering since I didn't clone the solution and I put some changes already.  
Thanks and awesome work!

Daniel

**Comment by skoruba** [comment]
Hello,
I am working on new release which will include everything inside nuget package, I mean especially UI part. This helps with updates. Please check branch release/2.0.0
Thanks

**Comment by skoruba** [comment]
Now it is possible to easier upgrade UI part via nuget package. 👍 Please check tha latest version from master branch.
