### ISSUE TITLE
release/2.0.0: API Scopes link points to root URL

### ISSUE THREAD

**Issue by agross** [skoruba/IdentityServer4.Admin#808]
### Describe the bug

The "Api Scopes" link in the "Clients/Resources" menu points to the application's root URL instead of `<root URL>/Configuration/ApiScopes`

Manually entering the URL works.

**Comment by skoruba** [comment]
@agross - Thanks, I will check it, I am still working on 2.0.0, I've found few things which are necesarry to rewrite. 😊

**Comment by skoruba** [comment]
Can you please test it now? 
Thanks!

**Comment by agross** [comment]
It's fixed now, thank you!

**Comment by skoruba** [comment]
Thanks for testing it! 👍🎈
