### ISSUE TITLE
redirect to the client details after a client is edit

### ISSUE THREAD

**Issue by mperk** [skoruba/IdentityServer4.Admin#81]
Api Resources work like a client work 
and other manageable areas

**Comment by skoruba** [comment]
I think - it's good idea, I will change it.

**Comment by skoruba** [comment]
Done on `feature/extensible-aspnet-identity` branch - https://github.com/skoruba/IdentityServer4.Admin/commit/546e711e513dc7b0696fa1199f16a24692444df6
I'll merge it into dev/master later.

**Comment by skoruba** [comment]
Done on master - #99
