### ISSUE TITLE
Getting Error "No DbContext named 'AdminIdentityDbContext' was found" when I try to run Migration

### ISSUE THREAD

**Issue by kunleshipo** [skoruba/IdentityServer4.Admin#816]
### Describe the bug
Getting Error "No DbContext named 'AdminIdentityDbContext' was found" when I try to run Migration from the Nuget Package Manager Console

### To Reproduce

- Create a new project with dotnet new skoruba.is4admin
- Update all connection strings
- Run Add-Migration or Update-Database from the Management Console

### Relevant parts of the log file

```
<log goes here>
```

**Comment by skoruba** [comment]
Check this script: https://github.com/skoruba/IdentityServer4.Admin/blob/master/build/add-migrations.ps1

**Comment by kunleshipo** [comment]
I have run the script and everything works now. Thanks a lot for your help.
