### ISSUE TITLE
How to customize CSS styles in 2.0.0 RC versions?

### ISSUE THREAD

**Issue by ericwscott** [skoruba/IdentityServer4.Admin#824]
### Question
In 2.0.0-beta1 I was able to use SASS with Bootstrap to change bootstrap defaults and create a customized bootstrap CSS file based on SASS variables.

With the move to Razor Class Libraries in the RC versions, there seems to be no way to do this because the source files are gone.

Is SASS still supported?  What is the recommended way to customize CSS styles?

**Comment by ericwscott** [comment]
I was able to make this work by adding a wwwroot folder and the necessary npm packages to the Admin project generated by the 2.0.0-rc3 template.  You can specify the custom css file using the CustomThemeCss property as documented in the Readme.

The downside to this approach is that the standard bootstrap css is always included in the vendor bundle so it is a bit bloated when you include sass generated bootstrap css in your custom theme.

In the previous version, I could edit the gulp tasks to drop the bootstrap css file from the vendor bundle and include the sass generated bootstrap css along with the other custom css.  This was a cleaner and more flexible approach.

**Comment by skoruba** [comment]
Hey @ericwscott - thanks for your feedback, it is great that you figure out how to solve it. 👍
