### ISSUE TITLE
Unable to edit localization resource files

### ISSUE THREAD

**Issue by ericwscott** [skoruba/IdentityServer4.Admin#825]
### Describe the bug
Unable to edit localization resource files in Admin project.  Filing as a bug report because this functionality existed in previous versions of the template.  In particular, I would like to change the SubTitle value and it is not possible.

### To Reproduce
1. Create a new project from the 2.0.0-rc3 version of the skoruba.is4admin template.
2. Resource files are not present in the project and cannot be edited.
3. Resource files are part of the Razor Class Library nuget package and are only accessible as a build artifact.

**Comment by skoruba** [comment]
Hey @ericwscott - you can override existing resources in same path like in Razor Class Library, for example:

in your project you can create folder `Resources and copy files from Razor Class Library and modify them.

Please, give me feedback how it works.

Thanks!
