### ISSUE TITLE
Database tables not created

### ISSUE THREAD

**Issue by akshetty9** [skoruba/IdentityServer4.Admin#826]
### Question
I am trying to run the project with PostGreSQL as store. When the application runs, it throws errors related to DataProtectionKeys  tables not being present. Do we need to run the migration manually?

**Comment by akshetty9** [comment]
My Bad. I figured it out from the documentation. Thanks for the great work.

**Comment by hamzarhaiem** [comment]
Hey, i'am facing same problem. How do you figure it out please?
