### ISSUE TITLE
Applying duende license key

### ISSUE THREAD

**Issue by egbertn** [skoruba/IdentityServer4.Admin#844]
### Question
It seems that a valid license key is ignored.

    "AdvancedConfiguration": {
        "IssuerUri": "",
        "IdentityServerLicenseKey": "eyJhbG.........................."
    },

(Other options are off)

 "CertificateConfiguration": {

    
        "UseSigningCertificatePfxFile": true,
        "SigningCertificatePfxFilePath": "./mycerttttttttttttttttttt.pfx",
        "SigningCertificatePfxFilePassword": "***********",
### Relevant parts of the log file

*PROBLEM*

Though this option is really FALSE   (seen through debugging)      "UseTemporarySigningKeyForDevelopment": true,
The identity server keeps using a 'localhost' self generated certificate.

How to get around this???

```
   <log goes here>
```

**Comment by skoruba** [comment]
Hello, for Duende IS Admin UI, please use this repo: https://github.com/skoruba/Duende.IdentityServer.Admin
There is option for applying the license key.
Thanks!
