### ISSUE TITLE
Add missing Chinese Localization Resources

### ISSUE THREAD

**Issue by skoruba** [skoruba/IdentityServer4.Admin#85]
I've added new localization for Picker component.

@Seaear @zhulige @snys98 - Please, can you help me with these missing localization resources?

In this commit is list of missing resources: https://github.com/skoruba/IdentityServer4.Admin/commit/2a67acd23ba3a7fbe6e08fe03e4e6185c20fd640

Here is a file that contains all new resources:
https://github.com/skoruba/IdentityServer4.Admin/blob/feature/extensible-aspnet-identity/src/Skoruba.IdentityServer4.Admin/Resources/Views/Configuration/ClientClaims.zh-cn.resx#L138-L161

Thank you!

**Comment by skoruba** [comment]
@gebiWangshushu - can you help me with this translation above?

**Comment by zhulige** [comment]
<data name="PickerItemAlreadySelectedTitle" xml:space="preserve">
    <value>已经选中项</value>
  </data>
  <data name="PickerNoItemSelectedTitle" xml:space="preserve">
    <value>没有选中项</value>
  </data>
  <data name="PickerRequiredMessage" xml:space="preserve">
    <value>必填“类型”</value>
  </data>
  <data name="PickerSearchItemPlaceholder" xml:space="preserve">
    <value>输入2个以上字符</value>
  </data>
  <data name="PickerSearchResultTitle" xml:space="preserve">
    <value>搜索结果:(点击选择)</value>
  </data>
  <data name="PickerSelectedItemsTitle" xml:space="preserve">
    <value>选择: </value>
  </data>
  <data name="PickerShowAllItemsTitle" xml:space="preserve">
    <value>更多...</value>
  </data>
  <data name="PickerSuggestedItemsTitle" xml:space="preserve">
    <value>建议事项： </value>
  </data>

**Comment by skoruba** [comment]
@zhulige Thank you for you translation - may I ask you - can you split following text into rows? I don't know how to use it. :)

**Comment by skoruba** [comment]
Maybe like this @zhulige :
已经选中项 
没有选中项
必填“类型” 
输入2个以上字符
搜索结果:(点击选择)
选择:
更多...
建议事项：

Is it correct? :)

**Comment by zhulige** [comment]
@skoruba yes, no problem.

**Comment by ymind** [comment]
'.zh-cn.resx' is should be '.zh-CN.resx'.
Use lowercase, will can not find the resources under linux/macOS.

**Comment by skoruba** [comment]
@ymind - I will check it.
Thanks!

**Comment by skoruba** [comment]
@ymind - I have change all resources to `.zh-CN.resx` - please - can you check it?
Thanks!

**Comment by Seaear** [comment]
@skoruba 
I tested in Ubuntu 18.04, use '.zh-CN.resx' or '.zh-cn.resx' can not find the resource file, but changed to '.zh.resx' can be found, my browser Accept-Language: zh-CN,zh;q=0.9,zh-HK;q=0.8,zh-TW;q=0.7,en;q=0.6

**Comment by skoruba** [comment]
@Seaear - OK, is it necessary to change all resource files to '.zh.resx'?
Thanks!

**Comment by Seaear** [comment]
@skoruba 
It is best not to change to '.zh.resx', I am translated Simplified Chinese, mainly used in mainland China, there is a big difference between translations in other regions.

**Comment by skoruba** [comment]
@Seaear - I see, what do you suggest?
Thanks!

**Comment by Seaear** [comment]
@skoruba 
I don't have any good suggestions for the time being, or wait for me to study the problems under Linux in a few days, or wait for someone who knows Linux to solve them.

**Comment by skoruba** [comment]
@Seaear I will be happy for any feedback from you. I'll be waiting - thanks!

**Comment by Seaear** [comment]
@ymind @skoruba 
This issue has nothing to do with uppercase and lowercase. This is an msbuild bug.
https://github.com/dotnet/coreclr/issues/20388
https://github.com/Microsoft/msbuild/issues/3897

**Comment by skoruba** [comment]
Done
