### ISSUE TITLE
How can I enable Facebook and Google Login

### ISSUE THREAD

**Issue by kunleshipo** [skoruba/IdentityServer4.Admin#856]
### Question
Please I am trying to use this to implement a single sign on solution for my organization, but I can't find my way around configuring it for facebook and google login. Please how can I do this? I also don't mind if you can refer me to relevant resources. Thanks a lot
### Relevant parts of the log file

```
   <log goes here>
```

**Comment by martinussuherman** [comment]
@kunleshipo I also have the same requirement as yours for my next project. I will try to create PR to implement the google and facebook external login to this repository. 

@skoruba any thoughts? I think it will add some dependencies.

**Comment by kunleshipo** [comment]
@martinussuherman thanks for this, it is exactly what I was looking for.
