### ISSUE TITLE
How can I add Roles Claim to My Access Token?

### ISSUE THREAD

**Issue by kunleshipo** [skoruba/IdentityServer4.Admin#869]
### Question
Hello, please I have been struggling with this for the past 24hours and I will appreciate any help I can get. `i have registered a user on the identity 4 server and I can login with the user with the openid flow. But I noticed that the roles claim does not get added to my access token. I created a new api scope and api resource to add the roles claim to the user claims for my client, but I can't find the roles claim on the list of suggestion and when i add it manually, it still doesn't show. Please what can I do?

### Relevant parts of the log file

```
   <log goes here>
```

**Comment by kunleshipo** [comment]
I have been able to resolve it by adding **response_type** **id_token token** to my token request

**Comment by Sen-Gupta** [comment]
I have the same issue, I'm using OpenIdConnect and never see role claims. Is there a sample you can share?
