### ISSUE TITLE
PasswordHash is set to NULL when saving user settings

### ISSUE THREAD

**Issue by MikhailKrasnobaev** [skoruba/IdentityServer4.Admin#89]
Hi,

ran into a bug, when saving user settings from /Identity/UserProfile/X  - password of a user is set to NULL (PasswordHash field in dbo.Users). Everything else saves normally.
Maybe some mapping issue?

Best regards.

**Comment by skoruba** [comment]
Hi @MikhailKrasnobaev 

which version of IS4 Admin have you used? Latest version from `master` branch or via dotnet new template?

I will try to reproduce this issue.

Thanks!

**Comment by MikhailKrasnobaev** [comment]
Hi @skoruba 

yes, it was the latest master at that time https://github.com/skoruba/IdentityServer4.Admin/tree/d62891609ba167d6b4b0cb27aaeaf7cfd8e0a189 

Best regards.
