### ISSUE TITLE
Client Secret Key can a Guid

### ISSUE THREAD

**Issue by mperk** [skoruba/IdentityServer4.Admin#92]
Can you develop this feature? 
When I click a button then guid generate and set in secret key textbox

**Comment by mperk** [comment]
Is that the strong secret key generated automatically ?

**Comment by mperk** [comment]
Ex secret key:
Guid.NewGuid() = dbe55dc8-0ce3-4464-bba1-8c625eb2474a

**Comment by skoruba** [comment]
@mperk Of course - you can definitely use guid as the value for secret and create a hash from it. 
Is it your request - create a button for generating new random guid as the value for secret?

**Comment by skoruba** [comment]
Done in latest release, please check it. :)
Thanks
