### ISSUE TITLE
DATABASE MIGRATION, what a mass

### ISSUE THREAD

**Issue by jafsuen** [skoruba/IdentityServer4.Admin#921]
There are no clear steps. So many problem. Waste a lot of time.

**Comment by josephwambura** [comment]
> What errors did you get?

How does one run MSSQL Server migrations? Tried with:

`Add-Migration TestMigrationInIdentity -Project Src\App.IdentityServer\App.STS.Identity -Context AdminIdentityDbContext`

but I get an error

**Comment by josephwambura** [comment]
Got the answer here [How to create new set of migrations](https://github.com/skoruba/IdentityServer4.Admin/discussions/860)

**Comment by skoruba** [comment]
Thanks!
