### ISSUE TITLE
Database Migration Issue (see attached details)

### ISSUE THREAD

**Issue by CardboardCrusader** [skoruba/IdentityServer4.Admin#925]
I went and I ran your PS1 script and everything generated just fine .
The problem I am having is how do you run your update to the database?

### DETAILS:
I am on windows 10 using SQL Server 2019 
I run the update-database command using appropriate syntax for each window both Developer PowerShell and Manager Console
I run these commands inside the <appname>.Admin.EntityFramework.SqlServer directory

``` 
dotnet ef database update
```
```
database-update
```
I get the following error:

More than one DbContext was found. Specify which one to use. Use the '-Context' parameter for PowerShell commands and the '--context' parameter for dotnet commands.

so I tried adding context to both commands and I get:

Unable to create an object of type 'AdminIdentityDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728 

Please help it is much appreciated and thanks again.

**Comment by CardboardCrusader** [comment]
This was meant for Duende Server :/

**Comment by CardboardCrusader** [comment]
I have figured it out I will be producing a guide to go over how I fixed it

**Comment by skoruba** [comment]
Hello, how did you fix it?
Thanks!
