### ISSUE TITLE
Net 6 has been released, please adapt to it.^_^

### ISSUE THREAD

**Issue by pigwing** [skoruba/IdentityServer4.Admin#926]
Net 6 has been released. Please adapt to it. At present, all projects depend on net 5. thank you.^_^

**Comment by skoruba** [comment]
Sure, I will do it

**Comment by pigwing** [comment]
thank you

**Comment by JonasBRasmussen** [comment]
@skoruba, I've pushed #928 to fix this issue. Version numbers have not been updated, so you might want to take a look.

**Comment by skoruba** [comment]
@JonasBRasmussen Thanks! Great job 👍

**Comment by beaver383** [comment]
Any progress？

**Comment by skoruba** [comment]
Sorry for delay - now it is released for .NET 6. 😊
Thank you
