### ISSUE TITLE
Use mysql when using template

### ISSUE THREAD

**Issue by ekjuanrejon** [skoruba/IdentityServer4.Admin#95]
Hello

I am following the instructions to create a brand new project using the templates.

My problem is that I want to be able to use MySql. How can I change Log.cs

**Comment by skoruba** [comment]
Hello @ekjuanrejon 
It's great question - please take a look here: https://github.com/saleem-mirza/serilog-sinks-mysql
What error did you get?

I think you need change logging here: https://github.com/skoruba/IdentityServer4.Admin/blob/feature/extensible-aspnet-identity/src/Skoruba.IdentityServer4.Admin/Helpers/StartupHelpers.cs#L139-L142

@xmichaelx @svendu - can you help us with settings of mysql and serilog? 

Thanks!

**Comment by svendu** [comment]
Hello @ekjuanrejon,

sadly the documentation is not up to date, yet and there is one incompatibility with mysql yet wich has to be fixed. I tried it myself.

**Comment by skoruba** [comment]
@ekjuanrejon Have you tried to use MySQL sink? Does it work for you?

Thanks!

**Comment by skoruba** [comment]
Mysql sink is not part of this solution. Thanks
