### ISSUE TITLE
Cannot write DateTime with Kind=Local to PostgreSQL type 'timestamp with time zone'

### ISSUE THREAD

**Issue by almamunx** [skoruba/IdentityServer4.Admin#963]
### The bug
I got the error below from Admin project. the endpoint was "https://localhost:44303/Configuration/Clients"

InvalidCastException: Cannot write DateTime with Kind=Local to PostgreSQL type 'timestamp with time zone', only UTC is supported. Note that it's not possible to mix DateTimes with different Kinds in an array/range. See the Npgsql.EnableLegacyTimestampBehavior AppContext switch to enable legacy behavior.

### To Reproduce
Added `AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);` at the startup of Admin and STS.Identity project

### Relevant parts of the log file

```
System.InvalidCastException: Cannot write DateTime with Kind=Local to PostgreSQL type 'timestamp with time zone', only UTC is supported. Note that it's not possible to mix DateTimes with different Kinds in an array/range. See the Npgsql.EnableLegacyTimestampBehavior AppContext switch to enable legacy behavior.
   at Npgsql.Internal.TypeHandlers.DateTimeHandlers.TimestampTzHandler.ValidateAndGetLength(DateTime value, NpgsqlParameter parameter)
   at Npgsql.Internal.TypeHandlers.DateTimeHandlers.TimestampTzHandler.ValidateObjectAndGetLength(Object value, NpgsqlLengthCache& lengthCache, NpgsqlParameter parameter)
   at Npgsql.NpgsqlParameter.ValidateAndGetLength()
   at Npgsql.NpgsqlParameterCollection.ValidateAndBind(ConnectorTypeMapper typeMapper)
```

**Comment by JudahMorrison** [comment]
@almamunx Did you ever figure out how to fix this?

**Comment by JudahMorrison** [comment]
What worked for me was adding: "
AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);
AppContext.SetSwitch("Npgsql.DisableDateTimeInfinityConversions", true);
" to Admin.Api, Admin, and STS.identity, in the beginning of my Main() functions.

![image](https://user-images.githubusercontent.com/66790728/167144203-360a80f8-f0f2-4ae5-9242-6247005268af.png)

**Comment by tvtrung206** [comment]
> What worked for me was adding: " AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true); AppContext.SetSwitch("Npgsql.DisableDateTimeInfinityConversions", true); " to Admin.Api, Admin, and STS.identity, in the beginning of my Main() functions.
> 
> ![image](https://user-images.githubusercontent.com/66790728/167144203-360a80f8-f0f2-4ae5-9242-6247005268af.png)

Thanks,  @JudahMorrison

**Comment by LinQiaoPorco** [comment]
```
AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);
AppContext.SetSwitch("Npgsql.DisableDateTimeInfinityConversions", true);
```

That solves my problem, too.
Thanks a lot! @JudahMorrison
