### ISSUE TITLE
IOException: IDX20807: Unable to retrieve document from: 'System.String'. HttpResponseMessage: 'System.Net.Http.HttpResponseMessage', HttpResponseMessage.Content: 'System.String'.

### ISSUE THREAD

**Issue by oblin** [skoruba/IdentityServer4.Admin#979]
### Question
I deploy to Rocky linux, using: / for STS, /admin for Identity.Admin
running STS is OK, but navigate to https://192.168.1.1/admin will show the error:

`IOException: IDX20807: Unable to retrieve document from: 'System.String'. HttpResponseMessage: 'System.Net.Http.HttpResponseMessage', HttpResponseMessage.Content: 'System.String'.`

### Relevant parts of the log file

```
An unhandled exception occurred while processing the request.
IOException: IDX20807: Unable to retrieve document from: 'System.String'. HttpResponseMessage: 'System.Net.Http.HttpResponseMessage', HttpResponseMessage.Content: 'System.String'.
Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(string address, CancellationToken cancel)

InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'.
Microsoft.IdentityModel.Protocols.ConfigurationManager<T>.GetConfigurationAsync(CancellationToken cancel)
```

google it but invain, please help. Thanks.

**Comment by MAXIMMAS1** [comment]
I'm facing the same issue for the past 4 days. Still haven't been able to fix this. How did you get this working? I'm running my application on a Linux server.

**Comment by oblin** [comment]
It's SSL certification issue, must have valid ssl certification issuer on my site.
Very hard to figure out how to bypass self certification on client side, use ngork if you just want to test.
